CREATE TABLE "cc_alerts" (
	"id" serial PRIMARY KEY NOT NULL,
	"ventureId" varchar(64) NOT NULL,
	"alertType" text DEFAULT 'weak_evidence',
	"alertTitle" varchar(255) NOT NULL,
	"alertDescription" text,
	"severity" text DEFAULT 'medium' NOT NULL,
	"linkedModule" varchar(64),
	"linkedRecordId" integer,
	"recommendedAction" text,
	"status" text DEFAULT 'open' NOT NULL,
	"owner" varchar(255),
	"dueDate" varchar(32),
	"autoGenerated" boolean DEFAULT false,
	"dedupeKey" varchar(255),
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cc_decisions" (
	"id" serial PRIMARY KEY NOT NULL,
	"ventureId" varchar(64) NOT NULL,
	"decisionType" text DEFAULT 'persevere',
	"decisionTitle" varchar(255) NOT NULL,
	"decisionSummary" text,
	"evidenceConfidenceScore" integer DEFAULT 0,
	"riskScore" integer DEFAULT 0,
	"recommendedAction" text,
	"decisionStatus" text DEFAULT 'recommended' NOT NULL,
	"reviewerNotes" text,
	"approvedBy" varchar(255),
	"decisionDate" varchar(32),
	"nextReviewDate" varchar(32),
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cc_evidence" (
	"id" serial PRIMARY KEY NOT NULL,
	"ventureId" varchar(64) NOT NULL,
	"hypothesisId" integer,
	"experimentId" integer,
	"moduleSource" varchar(64),
	"evidenceType" text DEFAULT 'interview',
	"evidenceTitle" varchar(255) NOT NULL,
	"evidenceSummary" text,
	"evidenceStrengthScore" integer DEFAULT 1,
	"evidenceRelevanceScore" integer DEFAULT 1,
	"evidenceRecencyScore" integer DEFAULT 1,
	"evidenceConfidenceScore" integer DEFAULT 0,
	"contradictsHypothesis" boolean DEFAULT false,
	"sourceReference" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cc_experiments" (
	"id" serial PRIMARY KEY NOT NULL,
	"ventureId" varchar(64) NOT NULL,
	"hypothesisId" integer,
	"experimentName" varchar(255) NOT NULL,
	"experimentType" text DEFAULT 'customer_interview',
	"moduleSource" varchar(64),
	"experimentOwner" varchar(255),
	"experimentStatus" text DEFAULT 'proposed' NOT NULL,
	"method" text,
	"successThreshold" text,
	"startDate" varchar(32),
	"dueDate" varchar(32),
	"result" text,
	"learningSummary" text,
	"decisionRecommendation" text,
	"nextStep" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cc_hypotheses" (
	"id" serial PRIMARY KEY NOT NULL,
	"ventureId" varchar(64) NOT NULL,
	"moduleSource" varchar(64),
	"hypothesisType" text DEFAULT 'problem' NOT NULL,
	"hypothesisStatement" text NOT NULL,
	"assumptionRiskLevel" text DEFAULT 'medium',
	"status" text DEFAULT 'untested' NOT NULL,
	"confidenceScore" integer DEFAULT 0,
	"evidenceSummary" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cc_pivot_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"ventureId" varchar(64) NOT NULL,
	"previousHypothesis" text,
	"newHypothesis" text,
	"pivotType" text DEFAULT 'problem',
	"reasonForPivot" text,
	"evidenceTrigger" text,
	"decisionId" integer,
	"hypothesisId" integer,
	"dateLogged" varchar(32),
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cc_stage_gate_reviews" (
	"id" serial PRIMARY KEY NOT NULL,
	"ventureId" varchar(64) NOT NULL,
	"fromStage" text,
	"toStage" text,
	"reviewStatus" text DEFAULT 'not_started' NOT NULL,
	"evidenceScore" integer DEFAULT 0,
	"marketScore" integer DEFAULT 0,
	"commercialScore" integer DEFAULT 0,
	"technicalScore" integer DEFAULT 0,
	"operationalScore" integer DEFAULT 0,
	"riskScore" integer DEFAULT 0,
	"investmentReadinessScore" integer DEFAULT 0,
	"reviewerNotes" text,
	"approvalDecision" text,
	"requiredActions" text,
	"reviewDate" varchar(32),
	"nextReviewDate" varchar(32),
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ventures" ADD COLUMN "currentStage" text;--> statement-breakpoint
ALTER TABLE "ventures" ADD COLUMN "validationStatus" text;--> statement-breakpoint
ALTER TABLE "ventures" ADD COLUMN "ventureType" text;--> statement-breakpoint
ALTER TABLE "ventures" ADD COLUMN "owner" varchar(255);