-- D7 Evidence Enforcement — journaled migration
-- Generated by drizzle-kit; guarded with IF NOT EXISTS for idempotency
-- (columns may already exist if the hand-authored 0007_d7_evidence.sql was applied first).

CREATE TABLE IF NOT EXISTS "vrl_evidence_confirmations" (
"id" varchar(64) PRIMARY KEY NOT NULL,
"assessment_id" varchar(64) NOT NULL,
"dimension_key" varchar(32) NOT NULL,
"evidence_url" text NOT NULL,
"confirmed_by" varchar(128),
"confirmed_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "vrl_assessments" ADD COLUMN IF NOT EXISTS "evidence_status" varchar(32);--> statement-breakpoint
ALTER TABLE "vrl_assessments" ADD COLUMN IF NOT EXISTS "self_assessed_dimensions" text[];--> statement-breakpoint
ALTER TABLE "vrl_assessments" ADD COLUMN IF NOT EXISTS "has_unverified_inputs" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "vrl_assessments" ADD COLUMN IF NOT EXISTS "evidence_confirmed_at" timestamp;--> statement-breakpoint
ALTER TABLE "vrl_assessments" ADD COLUMN IF NOT EXISTS "evidence_confirmed_by" varchar(128);--> statement-breakpoint
ALTER TABLE "vrl_assessments" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now() NOT NULL;

-- Historical backfill: all pre-D7 rows are unverified and fully self-assessed
UPDATE "vrl_assessments"
SET
  "evidence_status"          = 'unverified',
  "has_unverified_inputs"    = true,
  "self_assessed_dimensions" = ARRAY[
    'trlScore','mrlScore','brlScore','ecoScore',
    'prlScore','ipScore','frlScore','regScore','srlScore'
  ]
WHERE "evidence_status" IS NULL;
