CREATE TABLE `certification_tracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`certificationName` enum('B Corp','ISO 14001','ISO 26000','ISO 50001','ISO 9001','ISO 45001','GRI Standards','UN Global Compact','Science Based Target') NOT NULL,
	`status` enum('Not Started','Gap Analysis','In Progress','Under Review','Certified','Lapsed') NOT NULL DEFAULT 'Not Started',
	`progressPercent` int DEFAULT 0,
	`certificationScore` float DEFAULT 0,
	`targetCertificationDate` timestamp,
	`certificationDate` timestamp,
	`expiryDate` timestamp,
	`lastAuditDate` timestamp,
	`bImpactScore` float,
	`bImpactGovernance` float,
	`bImpactWorkers` float,
	`bImpactCommunity` float,
	`bImpactEnvironment` float,
	`bImpactCustomers` float,
	`certifyingBody` varchar(128),
	`certificateUrl` varchar(512),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `certification_tracking_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `csr_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`philanthropyScore` float DEFAULT 0,
	`ethicalSourcingScore` float DEFAULT 0,
	`communityInvestmentScore` float DEFAULT 0,
	`employeeVolunteeringScore` float DEFAULT 0,
	`transparencyReportingScore` float DEFAULT 0,
	`csrScore` float DEFAULT 0,
	`csrReportPublished` boolean DEFAULT false,
	`reportingFramework` varchar(128),
	`sdgAlignments` text,
	`lastReportedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `csr_metrics_id` PRIMARY KEY(`id`),
	CONSTRAINT `csr_metrics_ventureId_unique` UNIQUE(`ventureId`)
);
--> statement-breakpoint
CREATE TABLE `esg_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`carbonEmissionsScore` float DEFAULT 0,
	`energyEfficiencyScore` float DEFAULT 0,
	`waterManagementScore` float DEFAULT 0,
	`wasteCircularityScore` float DEFAULT 0,
	`biodiversityScore` float DEFAULT 0,
	`environmentalScore` float DEFAULT 0,
	`workerWellbeingScore` float DEFAULT 0,
	`diversityInclusionScore` float DEFAULT 0,
	`communityEngagementScore` float DEFAULT 0,
	`supplyChainEthicsScore` float DEFAULT 0,
	`socialScore` float DEFAULT 0,
	`boardTransparencyScore` float DEFAULT 0,
	`ethicsAntiCorruptionScore` float DEFAULT 0,
	`stakeholderEngagementScore` float DEFAULT 0,
	`dataPrivacyScore` float DEFAULT 0,
	`governanceScore` float DEFAULT 0,
	`esgScore` float DEFAULT 0,
	`esgFrameworkUsed` varchar(128),
	`lastReviewedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `esg_metrics_id` PRIMARY KEY(`id`),
	CONSTRAINT `esg_metrics_ventureId_unique` UNIQUE(`ventureId`)
);
--> statement-breakpoint
CREATE TABLE `irl_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`esgScore` float DEFAULT 0,
	`lcaScore` float DEFAULT 0,
	`pcfScore` float DEFAULT 0,
	`csrScore` float DEFAULT 0,
	`certificationScore` float DEFAULT 0,
	`irlScore` float DEFAULT 0,
	`vrlScore` float DEFAULT 0,
	`totalVentureIntelligenceScore` float DEFAULT 0,
	`computedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `irl_scores_id` PRIMARY KEY(`id`),
	CONSTRAINT `irl_scores_ventureId_unique` UNIQUE(`ventureId`)
);
--> statement-breakpoint
CREATE TABLE `lca_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`stage` enum('Raw Material Extraction','Manufacturing','Distribution & Logistics','Use Phase','End of Life') NOT NULL,
	`climateChangeImpact` float DEFAULT 0,
	`acidificationImpact` float DEFAULT 0,
	`eutrophicationImpact` float DEFAULT 0,
	`waterUsageImpact` float DEFAULT 0,
	`landUseImpact` float DEFAULT 0,
	`resourceDepletionImpact` float DEFAULT 0,
	`assessmentMaturityScore` float DEFAULT 0,
	`improvementActions` text,
	`targetReductionPercent` float,
	`baselineYear` int,
	`assessedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lca_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pcf_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`scope1Emissions` float DEFAULT 0,
	`scope2Emissions` float DEFAULT 0,
	`scope3Emissions` float DEFAULT 0,
	`totalEmissions` float DEFAULT 0,
	`emissionIntensity` float,
	`baselineYear` int,
	`baselineEmissions` float,
	`targetYear` int,
	`targetReductionPercent` float,
	`netZeroCommitment` boolean DEFAULT false,
	`scienceBasedTarget` boolean DEFAULT false,
	`offsetsUsed` float DEFAULT 0,
	`offsetProvider` varchar(128),
	`pcfScore` float DEFAULT 0,
	`measurementStandard` varchar(128),
	`lastMeasuredAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pcf_records_id` PRIMARY KEY(`id`),
	CONSTRAINT `pcf_records_ventureId_unique` UNIQUE(`ventureId`)
);
