CREATE TABLE `founder_suitability_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`talentProfileId` int NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`domainKnowledge` int DEFAULT 0,
	`executionCapability` int DEFAULT 0,
	`leadershipStrength` int DEFAULT 0,
	`networkRelevance` int DEFAULT 0,
	`stageReadiness` int DEFAULT 0,
	`riskProfile` int DEFAULT 0,
	`commitmentLevel` int DEFAULT 0,
	`overallScore` float DEFAULT 0,
	`recommendation` enum('Highly Suitable','Suitable','Conditionally Suitable','Not Suitable') DEFAULT 'Conditionally Suitable',
	`readinessToExecute` enum('Ready Now','Ready in 3 Months','Ready in 6 Months','Not Ready') DEFAULT 'Ready in 3 Months',
	`assessmentNotes` text,
	`assessedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `founder_suitability_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `people_venture_fit` (
	`id` int AUTO_INCREMENT NOT NULL,
	`talentProfileId` int NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`roleRequirementId` int,
	`skillsMatch` float DEFAULT 0,
	`industryMatch` float DEFAULT 0,
	`stageMatch` float DEFAULT 0,
	`networkValue` float DEFAULT 0,
	`availabilityFit` float DEFAULT 0,
	`pvfScore` float DEFAULT 0,
	`recommendation` enum('Highly Recommended','Recommended','Possible','Not Recommended') DEFAULT 'Possible',
	`notes` text,
	`computedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `people_venture_fit_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `talent_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(128) NOT NULL,
	`email` varchar(255),
	`linkedIn` varchar(255),
	`location` varchar(128),
	`profileType` enum('Founder','Operator','Executive','Technical Expert','Advisor','Mentor','Supplier','Partner','Investor') NOT NULL DEFAULT 'Operator',
	`currentRole` varchar(128),
	`availability` enum('Immediately Available','Available in 1 Month','Available in 3 Months','Part-Time Only','Advisory Only','Not Available') DEFAULT 'Immediately Available',
	`availabilityHoursPerWeek` int DEFAULT 0,
	`yearsExperience` int DEFAULT 0,
	`industryExpertise` text,
	`previousVentures` int DEFAULT 0,
	`previousExits` int DEFAULT 0,
	`previousLeadershipRoles` int DEFAULT 0,
	`stageIdea` int DEFAULT 0,
	`stageValidation` int DEFAULT 0,
	`stageBuild` int DEFAULT 0,
	`stageScale` int DEFAULT 0,
	`capTechnical` int DEFAULT 0,
	`capCommercial` int DEFAULT 0,
	`capOperational` int DEFAULT 0,
	`capRegulatory` int DEFAULT 0,
	`capManufacturing` int DEFAULT 0,
	`capSupplyChain` int DEFAULT 0,
	`capFinancial` int DEFAULT 0,
	`capMarketing` int DEFAULT 0,
	`networkInvestors` int DEFAULT 0,
	`networkCustomers` int DEFAULT 0,
	`networkSuppliers` int DEFAULT 0,
	`networkRegulators` int DEFAULT 0,
	`networkIndustry` int DEFAULT 0,
	`attrLeadership` int DEFAULT 0,
	`attrExecution` int DEFAULT 0,
	`attrCollaboration` int DEFAULT 0,
	`attrRiskTolerance` int DEFAULT 0,
	`attrResilience` int DEFAULT 0,
	`bio` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `talent_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `team_compositions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`talentProfileId` int NOT NULL,
	`roleRequirementId` int,
	`assignedRole` varchar(128) NOT NULL,
	`assignmentType` enum('Recommended','Confirmed','Proposed') DEFAULT 'Recommended',
	`engagementType` enum('Full-Time','Part-Time','Advisory','Contract') DEFAULT 'Full-Time',
	`pvfScore` float DEFAULT 0,
	`isFounder` boolean DEFAULT false,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `team_compositions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `team_gap_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`gapArea` enum('Technical','Commercial','Operational','Regulatory','Manufacturing','Supply Chain','Financial','Marketing','Leadership','Network','Stage Experience') NOT NULL,
	`severity` enum('Critical','High','Medium','Low') DEFAULT 'Medium',
	`description` text,
	`currentScore` float DEFAULT 0,
	`requiredScore` float DEFAULT 7,
	`gapScore` float DEFAULT 0,
	`status` enum('Open','In Progress','Resolved') DEFAULT 'Open',
	`resolutionNotes` text,
	`computedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `team_gap_analysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `venture_role_requirements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`roleTitle` varchar(128) NOT NULL,
	`functionalArea` enum('Technical','Commercial','Operational','Regulatory','Manufacturing','Supply Chain','Financial','Marketing','Leadership') NOT NULL,
	`priority` enum('Critical','High','Medium','Low') DEFAULT 'High',
	`status` enum('Open','Filled','On Hold') DEFAULT 'Open',
	`minYearsExperience` int DEFAULT 0,
	`minCapScore` int DEFAULT 5,
	`minNetworkScore` int DEFAULT 3,
	`minStageExperience` enum('Idea','Validation','Build','Scale') DEFAULT 'Validation',
	`requiredSectors` text,
	`engagementType` enum('Full-Time','Part-Time','Advisory','Contract') DEFAULT 'Full-Time',
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `venture_role_requirements_id` PRIMARY KEY(`id`)
);
