CREATE TABLE `ip_assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`ventureName` varchar(128),
	`ventureColor` varchar(16) DEFAULT '#22c55e',
	`ipType` varchar(32) NOT NULL,
	`title` varchar(256) NOT NULL,
	`reference` varchar(64),
	`description` text,
	`status` varchar(32) NOT NULL DEFAULT 'Draft',
	`jurisdiction` varchar(64) DEFAULT 'UK',
	`filedDate` varchar(16),
	`grantedDate` varchar(16),
	`expiryDate` varchar(16),
	`renewalDueDate` varchar(16),
	`commercialPotential` varchar(16) DEFAULT 'Medium',
	`estimatedValue` float DEFAULT 0,
	`trl` int DEFAULT 1,
	`claimsCount` int DEFAULT 0,
	`priorArtSummary` text,
	`trademarkClass` varchar(64),
	`trademarkType` varchar(32),
	`copyrightWork` varchar(64),
	`author` varchar(128),
	`designType` varchar(32),
	`secretCategory` varchar(64),
	`protectionMeasures` text,
	`ownedBy` varchar(128) DEFAULT 'EcoRace Ltd',
	`assignedTo` varchar(128),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ip_assets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ip_licenses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ipAssetId` int NOT NULL,
	`licensee` varchar(128) NOT NULL,
	`country` varchar(64),
	`region` varchar(64),
	`licenseType` varchar(32) NOT NULL DEFAULT 'Non-Exclusive',
	`status` varchar(32) NOT NULL DEFAULT 'Negotiating',
	`annualValue` float DEFAULT 0,
	`upfrontFee` float DEFAULT 0,
	`royaltyRate` float DEFAULT 0,
	`startDate` varchar(16),
	`endDate` varchar(16),
	`valuesAligned` boolean DEFAULT true,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ip_licenses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patent_hypotheses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`title` varchar(256) NOT NULL,
	`description` text NOT NULL,
	`rationale` text,
	`claimImpact` text,
	`included` boolean DEFAULT false,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `patent_hypotheses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patent_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ipAssetId` int,
	`ventureId` varchar(64) NOT NULL,
	`title` varchar(256) NOT NULL,
	`phase` varchar(32) NOT NULL DEFAULT 'Ingestion',
	`coreInventionNotes` text,
	`priorArtNotes` text,
	`draftAbstract` text,
	`draftBackground` text,
	`draftSummary` text,
	`draftDetailedDesc` text,
	`draftClaims` text,
	`jurisdiction` varchar(64) DEFAULT 'UK/EPO',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patent_projects_id` PRIMARY KEY(`id`)
);
