CREATE TABLE `lcssa_decision_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`decisionTitle` varchar(256) NOT NULL,
	`decisionType` enum('Environmental','Social','Economic','Integrated') NOT NULL DEFAULT 'Integrated',
	`lcaDimension` varchar(64),
	`rationale` text,
	`environmentalImpact` varchar(16) DEFAULT 'Neutral',
	`socialImpact` varchar(16) DEFAULT 'Neutral',
	`economicImpact` varchar(16) DEFAULT 'Neutral',
	`status` enum('Proposed','Approved','Implemented','Reviewed') NOT NULL DEFAULT 'Proposed',
	`decisionDate` timestamp DEFAULT (now()),
	`reviewDate` timestamp,
	`owner` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lcssa_decision_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lcssa_environmental` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`carbonFootprintKg` float DEFAULT 0,
	`carbonFootprintScope1` float DEFAULT 0,
	`carbonFootprintScope2` float DEFAULT 0,
	`carbonFootprintScope3` float DEFAULT 0,
	`carbonReductionTarget` float DEFAULT 0,
	`energyConsumptionKwh` float DEFAULT 0,
	`waterUsageLitres` float DEFAULT 0,
	`renewableEnergyPct` float DEFAULT 0,
	`materialEfficiencyPct` float DEFAULT 0,
	`wasteGeneratedKg` float DEFAULT 0,
	`wasteRecycledPct` float DEFAULT 0,
	`airPollutionIndex` float DEFAULT 0,
	`waterPollutionIndex` float DEFAULT 0,
	`biodiversityScore` float DEFAULT 0,
	`landUseHectares` float DEFAULT 0,
	`ecosystemServicesScore` float DEFAULT 0,
	`environmentalScore` float DEFAULT 0,
	`notes` text,
	`assessmentDate` timestamp DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lcssa_environmental_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lcssa_life_cycle_cost` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`rawMaterialCostGbp` float DEFAULT 0,
	`manufacturingCostGbp` float DEFAULT 0,
	`labourCostGbp` float DEFAULT 0,
	`overheadCostGbp` float DEFAULT 0,
	`inboundLogisticsCostGbp` float DEFAULT 0,
	`outboundLogisticsCostGbp` float DEFAULT 0,
	`warehouseCostGbp` float DEFAULT 0,
	`plannedMaintenanceCostGbp` float DEFAULT 0,
	`unplannedMaintenanceCostGbp` float DEFAULT 0,
	`assetLifespanYears` float DEFAULT 0,
	`disposalCostGbp` float DEFAULT 0,
	`recyclingRevGbp` float DEFAULT 0,
	`remediationCostGbp` float DEFAULT 0,
	`totalLccGbp` float DEFAULT 0,
	`lccScore` float DEFAULT 0,
	`currency` varchar(8) DEFAULT 'GBP',
	`notes` text,
	`assessmentDate` timestamp DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lcssa_life_cycle_cost_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lcssa_oversight` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`iso14001Certified` boolean DEFAULT false,
	`iso26000Adopted` boolean DEFAULT false,
	`griReportingLevel` varchar(32) DEFAULT 'None',
	`sdgAlignmentCount` int DEFAULT 0,
	`policyDocumentUrl` varchar(512),
	`complianceScore` float DEFAULT 0,
	`reportingFrequency` varchar(32) DEFAULT 'Annual',
	`lastReportDate` timestamp,
	`nextReportDate` timestamp,
	`dataQualityScore` float DEFAULT 0,
	`thirdPartyVerified` boolean DEFAULT false,
	`verifierName` varchar(128),
	`reportUrl` varchar(512),
	`boardOversight` boolean DEFAULT false,
	`sustainabilityCommittee` boolean DEFAULT false,
	`stakeholderEngagementScore` float DEFAULT 0,
	`oversightScore` float DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lcssa_oversight_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lcssa_social` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`livingWageCompliance` boolean DEFAULT false,
	`avgWorkingHoursPerWeek` float DEFAULT 0,
	`employeeTurnoverPct` float DEFAULT 0,
	`collectiveBargaining` boolean DEFAULT false,
	`humanRightsDueDiligence` boolean DEFAULT false,
	`supplyChainAuditScore` float DEFAULT 0,
	`childLaborRisk` varchar(16) DEFAULT 'Low',
	`forcedLaborRisk` varchar(16) DEFAULT 'Low',
	`localHiringPct` float DEFAULT 0,
	`communityInvestmentGbp` float DEFAULT 0,
	`communityEngagementScore` float DEFAULT 0,
	`ltifr` float DEFAULT 0,
	`nearMissReports` int DEFAULT 0,
	`safetyTrainingHours` float DEFAULT 0,
	`healthSafetyScore` float DEFAULT 0,
	`socialScore` float DEFAULT 0,
	`notes` text,
	`assessmentDate` timestamp DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lcssa_social_id` PRIMARY KEY(`id`)
);
