CREATE TABLE `business_risk_inputs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`sourceType` enum('research_paper','market_report','ip_document','academic_model','manual') NOT NULL DEFAULT 'manual',
	`inputCategory` enum('University','Founder','Joint') NOT NULL DEFAULT 'University',
	`marketRiskScore` float DEFAULT 50,
	`marketSizeScore` float DEFAULT 50,
	`competitorIntensity` float DEFAULT 50,
	`demandValidation` float DEFAULT 50,
	`esgRiskScore` float DEFAULT 50,
	`carbonFootprintRisk` float DEFAULT 50,
	`socialLicenceRisk` float DEFAULT 50,
	`supplyChainEsgRisk` float DEFAULT 50,
	`regulatoryRiskScore` float DEFAULT 50,
	`complianceComplexity` float DEFAULT 50,
	`certificationBarrier` float DEFAULT 50,
	`jurisdictionRisk` float DEFAULT 50,
	`commercialViabilityScore` float DEFAULT 50,
	`revenueModelClarity` float DEFAULT 50,
	`unitEconomicsScore` float DEFAULT 50,
	`partnershipReadiness` float DEFAULT 50,
	`strategicRiskScore` float DEFAULT 50,
	`ipProtectionStrength` float DEFAULT 50,
	`teamCapabilityRisk` float DEFAULT 50,
	`executionTrack` enum('BEBUS','ECORACE','Both') DEFAULT 'BEBUS',
	`businessRiskIndex` float DEFAULT 50,
	`notes` text,
	`lastUpdatedBy` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `business_risk_inputs_id` PRIMARY KEY(`id`),
	CONSTRAINT `business_risk_inputs_ventureId_unique` UNIQUE(`ventureId`)
);
--> statement-breakpoint
CREATE TABLE `dual_risk_decisions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`businessRiskIndex` float NOT NULL,
	`productRiskIndex` float NOT NULL,
	`trlScore` float NOT NULL,
	`brlScore` float NOT NULL,
	`esgScore` float DEFAULT 50,
	`vrlScore` float NOT NULL,
	`vrlLevel` int NOT NULL,
	`confidenceScore` float DEFAULT 0.5,
	`decision` enum('Build','Validate','Partner','Reject') NOT NULL,
	`decisionRationale` text,
	`executionTrack` enum('BEBUS','ECORACE','Both','None') DEFAULT 'None',
	`marketFeedback` text,
	`feedbackScore` float,
	`decidedBy` varchar(128),
	`sourceType` enum('University','Founder','Joint') DEFAULT 'Joint',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dual_risk_decisions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `product_risk_inputs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`sourceType` enum('problem_statement','industry_pain_point','product_idea','performance_gap','manual') NOT NULL DEFAULT 'manual',
	`inputCategory` enum('University','Founder','Joint') NOT NULL DEFAULT 'Founder',
	`technicalFeasibilityScore` float DEFAULT 50,
	`prototypeMaturity` float DEFAULT 50,
	`technologyReadiness` float DEFAULT 50,
	`performanceRiskScore` float DEFAULT 50,
	`benchmarkGap` float DEFAULT 50,
	`qualityRisk` float DEFAULT 50,
	`reliabilityRisk` float DEFAULT 50,
	`scalabilityRiskScore` float DEFAULT 50,
	`manufacturingRisk` float DEFAULT 50,
	`supplyChainRisk` float DEFAULT 50,
	`unitCostScalability` float DEFAULT 50,
	`engineeringComplexity` float DEFAULT 50,
	`integrationRisk` float DEFAULT 50,
	`dependencyRisk` float DEFAULT 50,
	`rdMaturityScore` float DEFAULT 50,
	`labValidationScore` float DEFAULT 50,
	`pilotTestScore` float DEFAULT 50,
	`executionTrack` enum('BEBUS','ECORACE','Both') DEFAULT 'ECORACE',
	`productRiskIndex` float DEFAULT 50,
	`notes` text,
	`lastUpdatedBy` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `product_risk_inputs_id` PRIMARY KEY(`id`),
	CONSTRAINT `product_risk_inputs_ventureId_unique` UNIQUE(`ventureId`)
);
