CREATE TABLE `sc_manufacturing` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` int NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`bomJson` text,
	`bomVersion` varchar(32) DEFAULT '1.0',
	`unitCostGbp` float,
	`toolingCostGbp` float,
	`moq` int DEFAULT 1,
	`targetUnitCostGbp` float,
	`primaryProcess` enum('composite_layup','resin_transfer_moulding','injection_moulding','cnc_machining','3d_printing','casting','forging','assembly','other') DEFAULT 'composite_layup',
	`processComplexityIndex` int DEFAULT 50,
	`productionCapacityPerMonth` int,
	`leadTimeDays` int,
	`manufacturingReadinessScore` int DEFAULT 0,
	`readinessNotes` text,
	`toolingStatus` enum('not_started','in_design','ordered','received','validated') DEFAULT 'not_started',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sc_manufacturing_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sc_production_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`productId` int NOT NULL,
	`supplierId` int,
	`orderRef` varchar(64),
	`orderType` enum('pilot','scale','repeat') DEFAULT 'pilot',
	`geography` enum('UK','China','EU','USA','Other') DEFAULT 'China',
	`quantityOrdered` int NOT NULL,
	`unitCostGbp` float,
	`totalCostGbp` float,
	`orderDate` timestamp DEFAULT (now()),
	`expectedDeliveryDate` timestamp,
	`actualDeliveryDate` timestamp,
	`leadTimeDays` int,
	`qaStatus` enum('pending','in_inspection','passed','failed','rework') DEFAULT 'pending',
	`defectRate` float DEFAULT 0,
	`qualityNotes` text,
	`shippingMethod` enum('air','sea','road','rail','courier') DEFAULT 'sea',
	`trackingRef` varchar(128),
	`status` enum('draft','confirmed','in_production','shipped','delivered','cancelled') DEFAULT 'draft',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sc_production_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sc_products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`materialType` enum('carbon_fibre','glass_fibre','hybrid_composite','aluminium','steel','polymer','bio_composite','ceramic','other') DEFAULT 'carbon_fibre',
	`manufacturingProcess` enum('composite_layup','resin_transfer_moulding','injection_moulding','cnc_machining','3d_printing','casting','forging','assembly','other') DEFAULT 'composite_layup',
	`prototypeStatus` enum('concept','design','prototype_v1','prototype_v2','validated','production_ready') DEFAULT 'concept',
	`trlLevel` int DEFAULT 1,
	`productionGeography` enum('UK','China','Both','Other') DEFAULT 'UK',
	`targetMarket` varchar(256),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sc_products_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sc_prototypes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` int NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`version` varchar(32) DEFAULT 'v1',
	`cadStatus` enum('not_started','in_progress','complete','validated') DEFAULT 'not_started',
	`caeStatus` enum('not_started','in_progress','complete','validated') DEFAULT 'not_started',
	`cadFileUrl` varchar(512),
	`labTestStatus` enum('not_started','in_progress','passed','failed') DEFAULT 'not_started',
	`testResults` text,
	`structuralIntegrity` float,
	`weightGrams` float,
	`dimensionsMm` varchar(128),
	`trlAtStart` int DEFAULT 1,
	`trlAtEnd` int DEFAULT 1,
	`lcaScore` float,
	`carbonFootprintKg` float,
	`manufacturingNotes` text,
	`prototypeImageUrl` varchar(512),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sc_prototypes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sc_suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`name` varchar(256) NOT NULL,
	`supplierType` enum('raw_material','component','sub_assembly','contract_manufacturer','tooling','logistics','testing_lab','other') DEFAULT 'contract_manufacturer',
	`geography` enum('UK','China','EU','USA','India','Other') DEFAULT 'China',
	`city` varchar(128),
	`contactName` varchar(128),
	`contactEmail` varchar(256),
	`riskScore` int DEFAULT 50,
	`qualityScore` int DEFAULT 50,
	`leadTimeDays` int,
	`unitCostIndex` float,
	`esgComplianceStatus` enum('unknown','non_compliant','partial','compliant','certified') DEFAULT 'unknown',
	`ethicalSourcingScore` int DEFAULT 50,
	`geopoliticalRiskFlag` boolean DEFAULT false,
	`geopoliticalNotes` text,
	`contractStatus` enum('prospect','negotiating','active','paused','terminated') DEFAULT 'prospect',
	`certifications` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sc_suppliers_id` PRIMARY KEY(`id`)
);
