CREATE TABLE `mfgLogisticsShipments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`shipmentRef` varchar(128),
	`freightType` enum('sea','air','rail','road') NOT NULL DEFAULT 'sea',
	`originPort` enum('shenzhen','shanghai','ningbo','qingdao','guangzhou','tianjin','other') DEFAULT 'shenzhen',
	`destinationPort` varchar(128) DEFAULT 'Felixstowe, UK',
	`volume` int,
	`weightKg` float,
	`freightCostGbp` float,
	`dutiesGbp` float,
	`insuranceGbp` float,
	`leadTimeDays` int,
	`departureDate` timestamp,
	`arrivalDate` timestamp,
	`status` enum('planned','booked','in_transit','customs','delivered','delayed') DEFAULT 'planned',
	`trackingRef` varchar(128),
	`forwarder` varchar(128),
	`incoterms` enum('EXW','FOB','CIF','DDP','DAP') DEFAULT 'FOB',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mfgLogisticsShipments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mfgPlaybookProjects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`productName` varchar(256) NOT NULL,
	`description` text,
	`phase` enum('uk_prototype','china_feasibility','pilot_production','scale_manufacturing') NOT NULL DEFAULT 'uk_prototype',
	`ukPrototypeDone` tinyint DEFAULT 0,
	`chinaFeasibilityDone` tinyint DEFAULT 0,
	`pilotProductionDone` tinyint DEFAULT 0,
	`scaleManufacturingDone` tinyint DEFAULT 0,
	`trlLevel` int DEFAULT 1,
	`prototypeStatus` enum('not_started','in_progress','validated','failed') DEFAULT 'not_started',
	`validationNotes` text,
	`rfqSent` tinyint DEFAULT 0,
	`dfmComplete` tinyint DEFAULT 0,
	`toolingOwnershipAgreement` tinyint DEFAULT 0,
	`pilotVolume` int DEFAULT 0,
	`scaleVolume` int DEFAULT 0,
	`targetUnitCostGbp` float,
	`materialCostGbp` float,
	`labourCostGbp` float,
	`overheadCostGbp` float,
	`logisticsCostGbp` float,
	`marginPercent` float DEFAULT 30,
	`iso9001` tinyint DEFAULT 0,
	`iso14001` tinyint DEFAULT 0,
	`ceCertified` tinyint DEFAULT 0,
	`ukcaCertified` tinyint DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mfgPlaybookProjects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mfgQcReports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`reportType` enum('pre_production','in_line','pre_shipment_aql') NOT NULL,
	`inspectionDate` timestamp,
	`inspector` varchar(128),
	`supplierId` int,
	`sampleSize` int,
	`defectsFound` int DEFAULT 0,
	`aqlLevel` varchar(16) DEFAULT '2.5',
	`result` enum('pass','fail','conditional_pass','pending') DEFAULT 'pending',
	`iso9001Pass` tinyint DEFAULT 0,
	`iso14001Pass` tinyint DEFAULT 0,
	`cePass` tinyint DEFAULT 0,
	`ukcastPass` tinyint DEFAULT 0,
	`findings` text,
	`correctiveActions` text,
	`attachmentUrl` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mfgQcReports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mfgSupplierTiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`supplierName` varchar(256) NOT NULL,
	`tier` enum('tier1_oem','tier2_components','tier3_raw_materials','tier4_tooling') NOT NULL,
	`country` varchar(64) DEFAULT 'China',
	`city` varchar(128),
	`contactName` varchar(128),
	`contactEmail` varchar(256),
	`nnnAgreement` enum('none','sent','signed') DEFAULT 'none',
	`manufacturingContract` enum('none','draft','signed') DEFAULT 'none',
	`toolingOwnership` enum('none','partial','full') DEFAULT 'none',
	`blackBoxComponents` tinyint DEFAULT 0,
	`riskScore` int DEFAULT 50,
	`auditScore` int DEFAULT 0,
	`qualityScore` int DEFAULT 0,
	`isDualSource` tinyint DEFAULT 0,
	`primarySupplierId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mfgSupplierTiers_id` PRIMARY KEY(`id`)
);
