CREATE TABLE `mfgApprovedSuppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`supplierId` varchar(64),
	`onboardingId` int,
	`supplierName` varchar(256) NOT NULL,
	`tierLevel` enum('oem','components','raw_materials','tooling') DEFAULT 'components',
	`capabilities` text,
	`riskRating` enum('low','medium','high','critical') DEFAULT 'medium',
	`performanceScore` float DEFAULT 0,
	`qualityScore` float DEFAULT 0,
	`deliveryScore` float DEFAULT 0,
	`costScore` float DEFAULT 0,
	`lastAuditDate` timestamp,
	`nextAuditDate` timestamp,
	`approvalDate` timestamp,
	`approvedBy` varchar(128),
	`status` enum('active','probationary','suspended','delisted') DEFAULT 'active',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mfgApprovedSuppliers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mfgContractTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`supplierId` int,
	`supplierName` varchar(256),
	`contractType` enum('nnn','manufacturing','tooling_ownership','quality','logistics_supply') NOT NULL,
	`clauseChecklist` text,
	`draftText` text,
	`jurisdiction` varchar(128) DEFAULT 'China',
	`effectiveDate` timestamp,
	`expiryDate` timestamp,
	`penaltyClause` boolean DEFAULT false,
	`ipOwnershipClause` boolean DEFAULT false,
	`incoterms` enum('EXW','FOB','CIF','DDP','DAP') DEFAULT 'FOB',
	`status` enum('draft','under_review','signed','expired','terminated') DEFAULT 'draft',
	`signedDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mfgContractTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mfgFactoryAudits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`supplierId` int,
	`supplierName` varchar(256) NOT NULL,
	`auditDate` timestamp,
	`auditorName` varchar(128),
	`facilityCondition` enum('pass','fail','partial','na') DEFAULT 'na',
	`equipmentCapability` enum('pass','fail','partial','na') DEFAULT 'na',
	`workforceSkills` enum('pass','fail','partial','na') DEFAULT 'na',
	`qcProcesses` enum('pass','fail','partial','na') DEFAULT 'na',
	`healthAndSafety` enum('pass','fail','partial','na') DEFAULT 'na',
	`environmentalCompliance` enum('pass','fail','partial','na') DEFAULT 'na',
	`overallResult` enum('pass','conditional_pass','fail','pending') DEFAULT 'pending',
	`auditScore` int DEFAULT 0,
	`findings` text,
	`correctiveActions` text,
	`followUpDate` timestamp,
	`status` enum('scheduled','in_progress','complete','follow_up_required') DEFAULT 'scheduled',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mfgFactoryAudits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mfgRfqTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`projectId` int,
	`rfqRef` varchar(64),
	`productName` varchar(256) NOT NULL,
	`productSpecs` text,
	`drawingsUrl` varchar(512),
	`materials` text,
	`targetVolumeMoq` int,
	`targetVolumeAnnual` int,
	`targetLeadTimeDays` int,
	`targetUnitCostGbp` float,
	`materialCostGbp` float,
	`labourCostGbp` float,
	`toolingCostGbp` float,
	`overheadCostGbp` float,
	`packagingCostGbp` float,
	`sentToSuppliers` text,
	`responseDeadline` timestamp,
	`status` enum('draft','sent','responses_received','evaluated','awarded','cancelled') DEFAULT 'draft',
	`awardedSupplier` varchar(256),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mfgRfqTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mfgSupplierOnboarding` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`companyName` varchar(256) NOT NULL,
	`location` varchar(256),
	`city` varchar(128),
	`country` varchar(128) DEFAULT 'China',
	`contactName` varchar(128),
	`contactEmail` varchar(256),
	`contactPhone` varchar(64),
	`capabilities` text,
	`certifications` text,
	`productionCapacity` varchar(256),
	`keyClients` text,
	`financialStability` enum('unknown','poor','fair','good','excellent') DEFAULT 'unknown',
	`references` text,
	`technicalCapability` int DEFAULT 0,
	`qualitySystems` int DEFAULT 0,
	`leadTimesScore` int DEFAULT 0,
	`costCompetitiveness` int DEFAULT 0,
	`communication` int DEFAULT 0,
	`complianceStandards` int DEFAULT 0,
	`overallScore` float DEFAULT 0,
	`status` enum('pending','under_review','approved','rejected','on_hold') DEFAULT 'pending',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mfgSupplierOnboarding_id` PRIMARY KEY(`id`)
);
