CREATE TABLE `dmAiPipelines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`pipelineType` varchar(32) NOT NULL DEFAULT 'generation',
	`model` varchar(128),
	`promptTemplate` text,
	`systemPrompt` text,
	`inputSchema` text,
	`outputSchema` text,
	`temperature` float,
	`maxTokens` int,
	`topP` float,
	`linkedAssetIds` text,
	`linkedModule` varchar(64),
	`status` varchar(32) NOT NULL DEFAULT 'draft',
	`totalRuns` int NOT NULL DEFAULT 0,
	`successRate` float,
	`avgLatencyMs` int,
	`avgTokensUsed` int,
	`estimatedCostUsd` float,
	`version` varchar(32) NOT NULL DEFAULT '1.0',
	`tags` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dmAiPipelines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dmDataAssets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`assetType` varchar(32) NOT NULL DEFAULT 'structured',
	`sourceType` varchar(32) NOT NULL DEFAULT 'manual_upload',
	`format` varchar(32) NOT NULL DEFAULT 'csv',
	`sizeKb` int,
	`rowCount` int,
	`columnCount` int,
	`storageUrl` text,
	`storageKey` varchar(512),
	`tags` text,
	`schema` text,
	`sampleData` text,
	`status` varchar(32) NOT NULL DEFAULT 'draft',
	`linkedModule` varchar(64),
	`linkedRecordId` int,
	`overallQuality` float,
	`lastValidated` timestamp,
	`ingestedBy` varchar(128),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dmDataAssets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dmFeedbackEntries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pipelineId` int,
	`runId` int,
	`ragPipelineId` int,
	`ventureId` varchar(64),
	`feedbackType` varchar(32) NOT NULL DEFAULT 'rating',
	`rating` int,
	`thumbs` varchar(8),
	`originalOutput` text,
	`correctedOutput` text,
	`comment` text,
	`inputContext` text,
	`issueCategory` varchar(64),
	`improvementAction` text,
	`status` varchar(16) NOT NULL DEFAULT 'open',
	`submittedBy` varchar(128),
	`reviewedBy` varchar(128),
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dmFeedbackEntries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dmFineTuningDatasets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`taskType` varchar(64),
	`totalSamples` int NOT NULL DEFAULT 0,
	`labelledSamples` int NOT NULL DEFAULT 0,
	`trainSplit` float NOT NULL DEFAULT 0.8,
	`valSplit` float NOT NULL DEFAULT 0.1,
	`testSplit` float NOT NULL DEFAULT 0.1,
	`storageUrl` text,
	`storageKey` varchar(512),
	`format` varchar(32) NOT NULL DEFAULT 'jsonl',
	`linkedAssetIds` text,
	`status` varchar(16) NOT NULL DEFAULT 'draft',
	`qualityScore` float,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dmFineTuningDatasets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dmFineTuningJobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`baseModel` varchar(128) NOT NULL,
	`targetTask` varchar(128),
	`datasetId` int,
	`trainingSamples` int,
	`validationSamples` int,
	`epochs` int,
	`learningRate` float,
	`batchSize` int,
	`trainLoss` float,
	`valLoss` float,
	`accuracy` float,
	`fineTunedModelId` varchar(255),
	`status` varchar(16) NOT NULL DEFAULT 'draft',
	`startedAt` timestamp,
	`completedAt` timestamp,
	`estimatedCostUsd` float,
	`actualCostUsd` float,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dmFineTuningJobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dmPipelineRuns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pipelineId` int NOT NULL,
	`ventureId` varchar(64),
	`status` varchar(16) NOT NULL DEFAULT 'running',
	`inputPayload` text,
	`outputPayload` text,
	`tokensUsed` int,
	`latencyMs` int,
	`costUsd` float,
	`errorMessage` text,
	`triggeredBy` varchar(64),
	`triggeredById` varchar(128),
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `dmPipelineRuns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dmQualityScores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assetId` int NOT NULL,
	`completeness` float,
	`accuracy` float,
	`freshness` float,
	`consistency` float,
	`uniqueness` float,
	`validity` float,
	`overallScore` float,
	`issues` text,
	`recommendations` text,
	`assessedBy` varchar(32) NOT NULL DEFAULT 'manual',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dmQualityScores_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dmRagDocuments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ragPipelineId` int NOT NULL,
	`assetId` int,
	`title` varchar(255) NOT NULL,
	`contentType` varchar(32) NOT NULL DEFAULT 'text',
	`storageUrl` text,
	`storageKey` varchar(512),
	`chunkCount` int NOT NULL DEFAULT 0,
	`sizeKb` int,
	`status` varchar(16) NOT NULL DEFAULT 'pending',
	`indexedAt` timestamp,
	`metadata` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dmRagDocuments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dmRagPipelines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`embeddingModel` varchar(128) NOT NULL DEFAULT 'text-embedding-3-small',
	`chunkSize` int NOT NULL DEFAULT 512,
	`chunkOverlap` int NOT NULL DEFAULT 64,
	`retrievalStrategy` varchar(32) NOT NULL DEFAULT 'similarity',
	`topK` int NOT NULL DEFAULT 5,
	`similarityThreshold` float DEFAULT 0.7,
	`systemPrompt` text,
	`contextTemplate` text,
	`rerankModel` varchar(128),
	`linkedAssetIds` text,
	`documentCount` int NOT NULL DEFAULT 0,
	`chunkCount` int NOT NULL DEFAULT 0,
	`status` varchar(16) NOT NULL DEFAULT 'draft',
	`lastIndexedAt` timestamp,
	`avgRetrievalMs` int,
	`totalQueries` int NOT NULL DEFAULT 0,
	`avgRelevanceScore` float,
	`tags` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dmRagPipelines_id` PRIMARY KEY(`id`)
);
