CREATE TABLE `offeringResearchLinks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offeringId` varchar(64) NOT NULL,
	`researchProjectId` int NOT NULL,
	`offeringResearchLinkType` enum('primary','supporting','validation','market') DEFAULT 'supporting',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `offeringResearchLinks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `uniApprovalReports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`offeringId` varchar(64),
	`portfolioId` varchar(64),
	`title` varchar(255) NOT NULL,
	`uniApprovalReportType` enum('syllabus_approval','research_validation','industry_engagement','ethics_clearance','ip_disclosure','commercialisation_approval') NOT NULL DEFAULT 'syllabus_approval',
	`uniApprovalStatus` enum('draft','under_review','approved','rejected','revision_requested','archived') NOT NULL DEFAULT 'draft',
	`productRiskOwner` varchar(255),
	`businessRiskOwner` varchar(255),
	`executiveSummary` text,
	`problemStatement` text,
	`researchObjectives` text,
	`methodology` text,
	`validationEvidence` text,
	`academicContribution` text,
	`commercialPotential` text,
	`ethicsStatement` text,
	`ipStatement` text,
	`recommendations` text,
	`aiGenerated` boolean DEFAULT false,
	`aiContent` text,
	`confidenceScore` int,
	`submittedBy` varchar(255),
	`reviewedBy` varchar(255),
	`approvedBy` varchar(255),
	`submittedAt` bigint,
	`reviewedAt` bigint,
	`approvedAt` bigint,
	`reviewNotes` text,
	`linkedResearchIds` text,
	`linkedPartnerIds` text,
	`linkedTalentIds` text,
	`linkedGovernanceIds` text,
	`h4Stage` enum('problem_definition','research_discovery','hypothesis_development','validation','commercialisation') DEFAULT 'problem_definition',
	`vrlStage` int,
	`trlLevel` int,
	`brlScore` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `uniApprovalReports_id` PRIMARY KEY(`id`)
);
