CREATE TABLE `blueprintLibraryLinks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`blueprintId` int NOT NULL,
	`blueprintLinkDomain` enum('talent','supply_chain','university','research','finance','market','ip','legal','crm','specialist') NOT NULL,
	`linkedRecordId` varchar(64) NOT NULL,
	`linkedRecordLabel` varchar(255),
	`readinessWeight` int DEFAULT 10,
	`blueprintLinkStatus` enum('proposed','confirmed','contracted','unavailable') DEFAULT 'proposed',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blueprintLibraryLinks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `spinoutBlueprints` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offeringId` varchar(64) NOT NULL,
	`portfolioId` varchar(64) NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`title` varchar(255) NOT NULL,
	`talentScore` int DEFAULT 0,
	`supplyChainScore` int DEFAULT 0,
	`financeScore` int DEFAULT 0,
	`marketScore` int DEFAULT 0,
	`technologyScore` int DEFAULT 0,
	`governanceScore` int DEFAULT 0,
	`overallScore` int DEFAULT 0,
	`blueprintGateStatus` enum('not_ready','approaching','ready_to_review','approved','launched') DEFAULT 'not_ready',
	`spinoffConfigId` int,
	`blueprintMarkdown` text,
	`executionRoadmap` text,
	`gapAnalysis` text,
	`reviewedBy` varchar(128),
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdBy` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `spinoutBlueprints_id` PRIMARY KEY(`id`)
);
