CREATE TABLE `invFundraisingRounds` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offeringId` int,
	`ventureId` varchar(64),
	`roundName` varchar(128) NOT NULL,
	`invRoundType` enum('pre_seed','seed','series_a','series_b','bridge','grant','convertible_note') DEFAULT 'seed',
	`targetAmount` int,
	`raisedAmount` int DEFAULT 0,
	`invRoundStatus` enum('planning','open','closing','closed','cancelled') DEFAULT 'planning',
	`openDate` timestamp,
	`closeDate` timestamp,
	`leadInvestor` varchar(256),
	`pitchDeckId` int,
	`businessPlanId` int,
	`executionPlanId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invFundraisingRounds_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invKpis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offeringId` int,
	`ventureId` varchar(64),
	`askAmount` int,
	`preMoneyVal` int,
	`useOfFunds` text,
	`revenueYear1` int,
	`revenueYear3` int,
	`revenueYear5` int,
	`ebitdaYear3` int,
	`ebitdaYear5` int,
	`burnRate` int,
	`runway` int,
	`customersCount` int,
	`revenueActual` int,
	`growthRate` float,
	`nps` float,
	`cac` int,
	`ltv` int,
	`socialImpactMetric` varchar(256),
	`impactValue` varchar(128),
	`sdgAlignment` varchar(256),
	`periodLabel` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invKpis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invOutputs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offeringId` int,
	`ventureId` varchar(64),
	`scoreId` int,
	`invOutputType` enum('pitch_deck','business_plan','execution_plan','investor_summary') NOT NULL,
	`title` varchar(256) NOT NULL,
	`invOutputStatus` enum('draft','in_review','approved','sent','archived') DEFAULT 'draft',
	`contentJson` text,
	`aiNarrative` text,
	`problemSection` text,
	`opportunitySection` text,
	`solutionSection` text,
	`marketSection` text,
	`tractionSection` text,
	`businessModelSection` text,
	`supplyChainSection` text,
	`teamSection` text,
	`financialsSection` text,
	`askSection` text,
	`executiveSummarySection` text,
	`marketAnalysisSection` text,
	`productServiceSection` text,
	`commercialStrategySection` text,
	`financialProjectionsSection` text,
	`riskAnalysisSection` text,
	`roadmap90DaySection` text,
	`productDevSection` text,
	`supplyChainPlanSection` text,
	`teamPlanSection` text,
	`budgetSection` text,
	`milestonesSection` text,
	`generatedAt` timestamp,
	`version` int DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invOutputs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invReadinessScores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offeringId` int,
	`ventureId` varchar(64),
	`commercialScore` float DEFAULT 0,
	`technicalScore` float DEFAULT 0,
	`validationScore` float DEFAULT 0,
	`supplyChainScore` float DEFAULT 0,
	`impactScore` float DEFAULT 0,
	`investmentAttractiveness` float DEFAULT 0,
	`compositeScore` float DEFAULT 0,
	`h4Stage` varchar(32),
	`vrlScore` float,
	`trlScore` float,
	`brlScore` float,
	`crlScore` float,
	`riskIndex` float,
	`scoreSummary` text,
	`strengthsJson` text,
	`weaknessesJson` text,
	`gapsJson` text,
	`calculatedBy` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invReadinessScores_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invTargets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offeringId` int,
	`ventureId` varchar(64),
	`investorName` varchar(256) NOT NULL,
	`fund` varchar(256),
	`invTargetType` enum('angel','vc','family_office','corporate_vc','impact_fund','grant','crowdfunding','debt') DEFAULT 'vc',
	`geographicFocus` varchar(128),
	`stageFocus` varchar(128),
	`sectorFocus` varchar(256),
	`minCheque` int,
	`maxCheque` int,
	`impactFocused` boolean DEFAULT false,
	`matchScore` float DEFAULT 0,
	`matchRationale` text,
	`invTargetStatus` enum('identified','researching','warm_intro','contacted','meeting_booked','dd_requested','term_sheet','closed','passed') DEFAULT 'identified',
	`contactEmail` varchar(256),
	`linkedinUrl` varchar(512),
	`warmIntroSource` varchar(256),
	`lastContactedAt` timestamp,
	`nextFollowUpAt` timestamp,
	`notes` text,
	`outputSentId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invTargets_id` PRIMARY KEY(`id`)
);
