CREATE TABLE `mrl_assessments` (
	`id` varchar(36) NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`mrlLevel` int NOT NULL,
	`mrlLabel` varchar(64) NOT NULL,
	`trlLevel` int,
	`pdeScore` int,
	`scieScore` int,
	`csmScore` int,
	`qceScore` int,
	`silScore` int,
	`compositeScore` int,
	`vrlContribution` float,
	`riskScoreOverall` int,
	`mrlRiskRag` enum('GREEN','AMBER','RED') DEFAULT 'AMBER',
	`mrlRegion` enum('CN','UK','HYBRID') DEFAULT 'HYBRID',
	`notes` text,
	`assessedBy` varchar(128),
	`assessedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mrl_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mrl_compliance_records` (
	`id` varchar(36) NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`assessmentId` varchar(36),
	`standard` varchar(128) NOT NULL,
	`market` varchar(64) NOT NULL,
	`mrlComplianceCat` enum('Quality Management','Product Safety','Environmental','Materials','Process','Social') DEFAULT 'Quality Management',
	`mrlComplianceStatus` enum('Not Started','Gap Analysis','In Progress','Submitted','Certified','Expired') DEFAULT 'Not Started',
	`gapSummary` text,
	`certificationBody` varchar(255),
	`targetCertDate` date,
	`actualCertDate` date,
	`expiryDate` date,
	`estimatedCostGbp` float,
	`estimatedWeeks` int,
	`isOnCriticalPath` boolean DEFAULT false,
	`qualityKpis` json,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mrl_compliance_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mrl_cost_models` (
	`id` varchar(36) NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`assessmentId` varchar(36),
	`modelName` varchar(255) NOT NULL,
	`mrlCostRegion` enum('CN','UK','HYBRID') DEFAULT 'HYBRID',
	`volumeScenarios` json NOT NULL,
	`targetVolume` int,
	`unitCostGbp` float,
	`unitPriceGbp` float,
	`grossMarginPct` float,
	`breakEvenVolume` int,
	`capexGbp` float,
	`opexAnnualGbp` float,
	`capexOpexRatio` float,
	`labourRates` json,
	`sensitivityFactors` json,
	`csmScore` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mrl_cost_models_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mrl_lcsa_records` (
	`id` varchar(36) NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`assessmentId` varchar(36),
	`carbonScope1` float,
	`carbonScope2` float,
	`carbonScope3` float,
	`carbonIntensityPerUnit` float,
	`lcsaScore` int,
	`circularityIndex` float,
	`socialRiskIndex` float,
	`facilityEnergyMix` json,
	`mrlCbamExposure` enum('None','Low','Medium','High') DEFAULT 'None',
	`cbamEstimatedCostGbp` float,
	`sectorBenchmarkScore` int,
	`silScore` int,
	`notes` text,
	`recordedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mrl_lcsa_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mrl_level_defs` (
	`level` int NOT NULL,
	`label` varchar(64) NOT NULL,
	`trlAlignment` varchar(16),
	`description` text NOT NULL,
	`keyActivities` json,
	`exitCriteria` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `mrl_level_defs_level` PRIMARY KEY(`level`)
);
--> statement-breakpoint
CREATE TABLE `mrl_process_routes` (
	`id` varchar(36) NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`assessmentId` varchar(36),
	`routeName` varchar(255) NOT NULL,
	`operations` json NOT NULL,
	`toolingSpecs` json,
	`bottleneckNodes` json,
	`targetVolumePerYear` int,
	`cycleTimeModelSec` int,
	`pdeScore` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mrl_process_routes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mrl_risk_register` (
	`id` varchar(36) NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`assessmentId` varchar(36),
	`mrlRiskCat` enum('Technical','Supply Chain','Cost','Compliance','Sustainability') NOT NULL,
	`description` text NOT NULL,
	`mrlRag` enum('G','A','R') NOT NULL,
	`probability` int NOT NULL,
	`impact` int NOT NULL,
	`riskScore` int NOT NULL,
	`mrlRiskPriority` enum('LOW','MED','HIGH') DEFAULT 'MED',
	`mitigationAction` text,
	`mitigationOwner` varchar(128),
	`targetResolutionDate` date,
	`mrlRiskStatus` enum('Open','In Progress','Mitigated','Accepted','Closed') DEFAULT 'Open',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mrl_risk_register_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mrl_suppliers` (
	`id` varchar(36) NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`mrlSupplierTier` enum('T1','T2','T3') DEFAULT 'T1',
	`country` varchar(64) NOT NULL,
	`mrlSupplierRegion` enum('CN','UK','EU','US','ROW') DEFAULT 'CN',
	`category` varchar(128),
	`bomComponents` json,
	`riskScore` int DEFAULT 0,
	`mrlScieRag` enum('GREEN','AMBER','RED') DEFAULT 'AMBER',
	`isSingleSource` boolean DEFAULT false,
	`hasDualSource` boolean DEFAULT false,
	`leadTimeWeeks` int,
	`moqUnits` int,
	`mrlFxExposure` enum('LOW','MED','HIGH') DEFAULT 'MED',
	`mrlGeoRisk` enum('LOW','MED','HIGH') DEFAULT 'LOW',
	`mrlAuditStatus` enum('Not Audited','Pending','Passed','Failed') DEFAULT 'Not Audited',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mrl_suppliers_id` PRIMARY KEY(`id`)
);
