CREATE TABLE `vrl_assessments` (
	`id` varchar(64) NOT NULL,
	`ventureId` varchar(64) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`trl_score` int NOT NULL,
	`mrl_score` int NOT NULL,
	`brl_score` int NOT NULL,
	`eco_score` int NOT NULL,
	`prl_score` int NOT NULL,
	`ip_score` int NOT NULL,
	`frl_score` int NOT NULL,
	`reg_score` int NOT NULL,
	`srl_score` int NOT NULL,
	`product_score` decimal(5,2),
	`market_score` decimal(5,2),
	`execution_score` decimal(5,2),
	`structural_score` decimal(5,2),
	`sustainability_score` decimal(5,2),
	`base_average` decimal(5,2),
	`is_vetoed` boolean NOT NULL DEFAULT false,
	`global_vrl_score` int,
	`band_label` varchar(64),
	`submitted_by` varchar(128),
	CONSTRAINT `vrl_assessments_id` PRIMARY KEY(`id`)
);
