// ============================================================================
// MODULE 3 — Market Risk Log (auto + manual risks, decision warnings)
// ============================================================================
import { useState, useMemo } from "react";
import { trpc } from "@/lib/trpc";
import { useSelectedVenture } from "@/contexts/SelectedVentureContext";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { ShieldAlert, Plus, Pencil, Trash2, Sparkles, Flame, FlaskConical } from "lucide-react";
import {
  ModuleHeader, VentureSelector, ScoreCard, EmptyState, NoVentureState, FormModal,
  ScoreSelect, Section, StatusBadge, ToneBadge, DecisionWarning,
  LeanDecisionPanel, NextExperimentPanel,
} from "@/components/discovery/primitives";
import {
  calculateMarketRiskScore, interpretMarketRisk, marketRiskDecisionWarnings,
  normaliseOpenMarketRisk, bandFor0to100, generateMarketRiskDecision,
  RISK_CATEGORIES, RISK_STATUSES,
} from "@shared/discoveryMarket";

export default function MarketRiskLog() {
  const { selectedVentureId: ventureId } = useSelectedVenture();
  const utils = trpc.useUtils();
  const enabled = !!ventureId;
  const v = ventureId ?? "";
  const [statusFilter, setStatusFilter] = useState<string>("__all__");
  const [categoryFilter, setCategoryFilter] = useState<string>("__all__");

  const risks = trpc.discoveryMarket.risks.list.useQuery({ ventureId: v }, { enabled });
  const invalidate = () => { utils.discoveryMarket.risks.list.invalidate(); utils.discoveryMarket.summary.invalidate(); };

  const [open, setOpen] = useState(false);
  const [form, setForm] = useState<any>({});
  const upsert = trpc.discoveryMarket.risks.upsert.useMutation({ onSuccess: () => { invalidate(); setOpen(false); toast.success("Risk saved"); } });
  const del = trpc.discoveryMarket.risks.delete.useMutation({ onSuccess: () => { invalidate(); toast.success("Risk deleted"); } });

  const openForm = (row?: any) => {
    setForm(row ? { ...row } : {
      ventureId: v, riskTitle: "", riskCategory: "problem_risk", probabilityScore: 1, severityScore: 1, evidenceConfidenceScore: 1, status: "open",
    });
    setOpen(true);
  };

  const allRows = risks.data ?? [];
  const rows = useMemo(
    () => allRows.filter(
      (r) => (statusFilter === "__all__" || r.status === statusFilter)
        && (categoryFilter === "__all__" || r.riskCategory === categoryFilter),
    ),
    [allRows, statusFilter, categoryFilter],
  );
  const liveScore = calculateMarketRiskScore({ probabilityScore: form.probabilityScore ?? 1, severityScore: form.severityScore ?? 1, evidenceConfidenceScore: form.evidenceConfidenceScore ?? 1 });

  const warnings = marketRiskDecisionWarnings(allRows.map((r) => ({ riskCategory: r.riskCategory ?? "", marketRiskScore: r.marketRiskScore ?? 0, status: r.status ?? "open" })));
  const openLoad = normaliseOpenMarketRisk(allRows.map((r) => ({ marketRiskScore: r.marketRiskScore ?? 0, status: r.status ?? "open" })));
  const openRisks = allRows.filter((r) => r.status !== "closed" && r.status !== "mitigated");
  const openCount = openRisks.length;
  const autoCount = allRows.filter((r) => r.autoGenerated).length;
  const top5 = openRisks.slice().sort((a, b) => (b.marketRiskScore ?? 0) - (a.marketRiskScore ?? 0)).slice(0, 5);
  const criticalRisks = openRisks.filter((r) => (r.marketRiskScore ?? 0) >= 76);
  const requiredExperiments = Array.from(new Set(openRisks.filter((r) => r.requiredExperiment?.trim()).map((r) => r.requiredExperiment as string)));
  const riskDecision = generateMarketRiskDecision(openLoad, criticalRisks.length);
  const nextExperiment = top5[0]?.requiredExperiment?.trim() || "Prioritise the highest-scoring open risk and design a single decisive de-risking experiment.";

  if (!ventureId) {
    return (
      <div className="flex-1 overflow-y-auto p-8">
        <ModuleHeader title="Market Risk Log" purpose="A living register of market risks, auto-generated from your evidence." icon={<ShieldAlert size={22} />} action={<VentureSelector />} />
        <NoVentureState />
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-8 space-y-6">
      <ModuleHeader title="Market Risk Log" purpose="Auto-generated and manual market risks scored on Probability × Severity × Evidence confidence (1–125)." icon={<ShieldAlert size={22} />} action={<VentureSelector />} />

      <div className="flex flex-wrap items-center gap-4">
        <div className="flex items-center gap-2">
          <span className="text-xs font-semibold uppercase tracking-wider text-gray-400">Category</span>
          <Select value={categoryFilter} onValueChange={setCategoryFilter}>
            <SelectTrigger className="w-44 h-9 text-sm" data-testid="select-category-filter"><SelectValue /></SelectTrigger>
            <SelectContent><SelectItem value="__all__">All categories</SelectItem>{RISK_CATEGORIES.map((c) => <SelectItem key={c} value={c}>{c.replace(/_/g, " ")}</SelectItem>)}</SelectContent>
          </Select>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs font-semibold uppercase tracking-wider text-gray-400">Status</span>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-40 h-9 text-sm" data-testid="select-status-filter"><SelectValue /></SelectTrigger>
            <SelectContent><SelectItem value="__all__">All statuses</SelectItem>{RISK_STATUSES.map((st) => <SelectItem key={st} value={st}>{st}</SelectItem>)}</SelectContent>
          </Select>
        </div>
        <Button size="sm" className="ml-auto" onClick={() => openForm()} style={{ background: "#56A837" }} data-testid="button-add-risk"><Plus size={14} className="mr-1" />Add Risk</Button>
      </div>

      {allRows.length > 0 && (
        <>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <ScoreCard label="Open Market Risk" score={openLoad} band={bandFor0to100(openLoad, "risk")} interpretation={`${openCount} open risk${openCount !== 1 ? "s" : ""}`} />
            <Card className="border shadow-sm"><CardContent className="p-5"><div className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-2">Total Risks</div><div className="text-3xl font-bold text-gray-800">{allRows.length}</div></CardContent></Card>
            <Card className="border shadow-sm"><CardContent className="p-5"><div className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-2">Auto-generated</div><div className="text-3xl font-bold flex items-center gap-2" style={{ color: "#3B85BA" }}><Sparkles size={20} />{autoCount}</div></CardContent></Card>
            <Card className="border shadow-sm"><CardContent className="p-5"><div className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-2">Critical (≥76)</div><div className="text-3xl font-bold" style={{ color: "#b91c1c" }}>{criticalRisks.length}</div></CardContent></Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-3">
            {/* Top 5 risks card */}
            <Card className="border shadow-sm">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-gray-400 mb-3"><ShieldAlert size={14} />Top 5 Risks</div>
                {top5.length > 0 ? (
                  <ol className="space-y-1.5">
                    {top5.map((r) => (
                      <li key={r.id} className="flex items-center justify-between gap-2 text-sm">
                        <span className="truncate text-gray-700">{r.riskTitle}</span>
                        <span className="flex items-center gap-1.5 shrink-0"><span className="font-bold text-gray-700">{r.marketRiskScore}</span><ToneBadge band={interpretMarketRisk(r.marketRiskScore ?? 0)} /></span>
                      </li>
                    ))}
                  </ol>
                ) : <p className="text-sm text-gray-400">No open risks.</p>}
              </CardContent>
            </Card>

            {/* Critical risks card */}
            <Card className="border shadow-sm">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-gray-400 mb-3"><Flame size={14} style={{ color: "#b91c1c" }} />Critical Risks (≥76)</div>
                {criticalRisks.length > 0 ? (
                  <ul className="space-y-1.5">
                    {criticalRisks.slice(0, 5).map((r) => (
                      <li key={r.id} className="flex items-center justify-between gap-2 text-sm">
                        <span className="truncate text-gray-700">{r.riskTitle}</span>
                        <span className="font-bold shrink-0" style={{ color: "#b91c1c" }}>{r.marketRiskScore}</span>
                      </li>
                    ))}
                  </ul>
                ) : <p className="text-sm text-gray-400">No critical risks — good.</p>}
              </CardContent>
            </Card>

            {/* Required experiments card */}
            <Card className="border shadow-sm">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-gray-400 mb-3"><FlaskConical size={14} style={{ color: "#3B85BA" }} />Required Experiments</div>
                {requiredExperiments.length > 0 ? (
                  <ul className="space-y-1.5 list-disc list-inside">
                    {requiredExperiments.slice(0, 5).map((e, i) => <li key={i} className="text-sm text-gray-600">{e}</li>)}
                  </ul>
                ) : <p className="text-sm text-gray-400">No experiments required.</p>}
              </CardContent>
            </Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <LeanDecisionPanel title="Risk Decision" decisions={riskDecision} />
            <NextExperimentPanel recommendation={nextExperiment} />
          </div>

          {warnings.length > 0 && <DecisionWarning messages={warnings} />}
        </>
      )}

      <Section title="Risk Register">
        {rows.length > 0 ? (
          <Card className="border shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b bg-gray-50 text-left text-xs text-gray-500">
                    <th className="px-4 py-2.5 font-semibold">Risk</th>
                    <th className="px-4 py-2.5 font-semibold">Category</th>
                    <th className="px-4 py-2.5 font-semibold text-center">P</th>
                    <th className="px-4 py-2.5 font-semibold text-center">S</th>
                    <th className="px-4 py-2.5 font-semibold text-center">E</th>
                    <th className="px-4 py-2.5 font-semibold">Score</th>
                    <th className="px-4 py-2.5 font-semibold">Status</th>
                    <th className="px-4 py-2.5"></th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((r) => {
                    const band = interpretMarketRisk(r.marketRiskScore ?? 0);
                    return (
                      <tr key={r.id} className="border-b last:border-0 hover:bg-gray-50">
                        <td className="px-4 py-2.5">
                          <div className="flex items-center gap-1.5">
                            {r.autoGenerated && <Sparkles size={12} style={{ color: "#3B85BA" }} />}
                            <span className="font-medium text-gray-800">{r.riskTitle}</span>
                          </div>
                          {r.requiredExperiment && <div className="text-xs text-gray-400 mt-0.5">Experiment: {r.requiredExperiment}</div>}
                        </td>
                        <td className="px-4 py-2.5 text-gray-600 capitalize">{(r.riskCategory ?? "").replace(/_/g, " ")}</td>
                        <td className="px-4 py-2.5 text-center text-gray-600">{r.probabilityScore}</td>
                        <td className="px-4 py-2.5 text-center text-gray-600">{r.severityScore}</td>
                        <td className="px-4 py-2.5 text-center text-gray-600">{r.evidenceConfidenceScore}</td>
                        <td className="px-4 py-2.5"><div className="flex items-center gap-2"><span className="font-bold text-gray-700">{r.marketRiskScore}</span><ToneBadge band={band} /></div></td>
                        <td className="px-4 py-2.5"><StatusBadge status={r.status} /></td>
                        <td className="px-4 py-2.5 text-right whitespace-nowrap">
                          <button onClick={() => openForm(r)} className="text-gray-400 hover:text-gray-700 mr-2"><Pencil size={13} /></button>
                          <button onClick={() => del.mutate({ id: r.id })} className="text-gray-400 hover:text-red-600"><Trash2 size={13} /></button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </Card>
        ) : (
          <EmptyState title="No market risks" description="Risks are auto-created from interviews, competitors, demand and WTP evidence — or add your own." action={<Button size="sm" variant="outline" onClick={() => openForm()}>Add Risk</Button>} />
        )}
      </Section>

      <FormModal wide open={open} onOpenChange={setOpen} title={form.id ? "Edit Risk" : "Add Market Risk"} submitting={upsert.isPending}
        onSubmit={() => { if (!form.riskTitle?.trim()) return toast.error("Risk title required"); upsert.mutate({ ...form, linkedRecordId: form.linkedRecordId ?? null }); }}>
        <Field label="Risk title"><Input value={form.riskTitle ?? ""} onChange={(e) => setForm({ ...form, riskTitle: e.target.value })} data-testid="input-risk-title" /></Field>
        <div className="grid grid-cols-2 gap-3">
          <Field label="Category">
            <Select value={form.riskCategory ?? "problem_risk"} onValueChange={(val) => setForm({ ...form, riskCategory: val })}>
              <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
              <SelectContent>{RISK_CATEGORIES.map((c) => <SelectItem key={c} value={c}>{c.replace(/_/g, " ")}</SelectItem>)}</SelectContent>
            </Select>
          </Field>
          <Field label="Status">
            <Select value={form.status ?? "open"} onValueChange={(val) => setForm({ ...form, status: val })}>
              <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
              <SelectContent>{RISK_STATUSES.map((st) => <SelectItem key={st} value={st}>{st}</SelectItem>)}</SelectContent>
            </Select>
          </Field>
        </div>
        <Field label="Description"><Textarea value={form.riskDescription ?? ""} onChange={(e) => setForm({ ...form, riskDescription: e.target.value })} /></Field>
        <div className="grid grid-cols-3 gap-3">
          <ScoreSelect label="Probability (1-5)" value={form.probabilityScore ?? 1} onChange={(n) => setForm({ ...form, probabilityScore: n })} max={5} />
          <ScoreSelect label="Severity (1-5)" value={form.severityScore ?? 1} onChange={(n) => setForm({ ...form, severityScore: n })} max={5} />
          <ScoreSelect label="Evidence conf. (1-5)" value={form.evidenceConfidenceScore ?? 1} onChange={(n) => setForm({ ...form, evidenceConfidenceScore: n })} max={5} />
        </div>
        <div className="flex items-center justify-end gap-2 p-3 rounded-lg bg-gray-50">
          <span className="text-xs text-gray-500">Live Market Risk Score (P×S×E):</span>
          <span className="font-bold text-gray-700">{liveScore}</span>
          <ToneBadge band={interpretMarketRisk(liveScore)} />
        </div>
        <Field label="Evidence summary"><Textarea value={form.evidenceSummary ?? ""} onChange={(e) => setForm({ ...form, evidenceSummary: e.target.value })} /></Field>
        <Field label="Mitigation plan"><Textarea value={form.mitigationPlan ?? ""} onChange={(e) => setForm({ ...form, mitigationPlan: e.target.value })} /></Field>
        <Field label="Required experiment"><Input value={form.requiredExperiment ?? ""} onChange={(e) => setForm({ ...form, requiredExperiment: e.target.value })} /></Field>
        <div className="grid grid-cols-2 gap-3">
          <Field label="Owner"><Input value={form.owner ?? ""} onChange={(e) => setForm({ ...form, owner: e.target.value })} /></Field>
          <Field label="Review date"><Input type="date" value={form.reviewDate ?? ""} onChange={(e) => setForm({ ...form, reviewDate: e.target.value })} /></Field>
        </div>
      </FormModal>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <div><label className="block text-xs font-medium text-gray-600 mb-1">{label}</label>{children}</div>;
}
