import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Download, FileText, Lock } from "lucide-react";
import { reports } from "../mock/data";
import { useRole } from "../context/RoleContext";
import { SurfaceHeader } from "../components/SurfaceHeader";
import { ConfidenceBadge } from "../components/ConfidenceBadge";

const statusCls: Record<string, string> = {
  published: "bg-emerald-100 text-emerald-800 border-emerald-200",
  approved: "bg-blue-100 text-blue-800 border-blue-200",
  "in review": "bg-amber-100 text-amber-800 border-amber-200",
  draft: "bg-slate-100 text-slate-700 border-slate-200",
};

const accessCls: Record<string, string> = {
  public: "bg-emerald-50 text-emerald-700 border-emerald-200",
  investor: "bg-violet-50 text-violet-700 border-violet-200",
  partner: "bg-blue-50 text-blue-700 border-blue-200",
  internal: "bg-slate-50 text-slate-700 border-slate-200",
};

const dataRoomChecklist = [
  { label: "Venture Readiness Report", ready: true },
  { label: "Technical Validation Report", ready: true },
  { label: "Sustainability Evidence Review", ready: true },
  { label: "Cap table & financial model", ready: false },
  { label: "IP & Data Moat Summary", ready: false },
  { label: "Funding Readiness Checklist", ready: false },
];

export default function ReportsDataRoom() {
  const { ventureId } = useRole();
  const vReports = reports.filter((r) => r.ventureId === ventureId);
  const readyCount = dataRoomChecklist.filter((c) => c.ready).length;

  return (
    <div>
      <SurfaceHeader
        title="Reports & Data Room"
        description="Agent-generated, evidence-backed outputs with confidence, reviewer and access level."
      />

      <div className="grid gap-4 lg:grid-cols-3">
        <div className="space-y-3 lg:col-span-2">
          {vReports.map((r) => (
            <Card key={r.id}>
              <CardContent className="p-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    <FileText className="mt-0.5 h-5 w-5 text-primary" />
                    <div>
                      <p className="font-medium">{r.title}</p>
                      <p className="text-xs text-muted-foreground">
                        {r.version} · updated {r.updatedAt} · {r.evidenceUsed} evidence items
                      </p>
                      <p className="mt-1 text-xs text-muted-foreground">
                        Generated by: {r.generatedBy.join(", ")}
                      </p>
                    </div>
                  </div>
                  <div className="flex flex-col items-end gap-2">
                    <Badge variant="outline" className={`capitalize ${statusCls[r.status]}`}>
                      {r.status}
                    </Badge>
                    <Badge variant="outline" className={`capitalize ${accessCls[r.accessLevel]}`}>
                      {r.accessLevel}
                    </Badge>
                  </div>
                </div>
                <div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t pt-3">
                  <div className="flex items-center gap-3">
                    <ConfidenceBadge confidence={r.confidence} />
                    <span className="text-xs text-muted-foreground">Reviewer: {r.reviewer}</span>
                  </div>
                  <Button variant="outline" size="sm" className="gap-1">
                    <Download className="h-3.5 w-3.5" />
                    Export
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
          {vReports.length === 0 && (
            <Card>
              <CardContent className="py-8 text-center text-sm text-muted-foreground">
                No reports generated for this venture yet.
              </CardContent>
            </Card>
          )}
        </div>

        <Card className="h-fit">
          <CardHeader>
            <CardTitle className="text-base">Data-room readiness</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="mb-3 flex items-baseline gap-2">
              <span className="text-3xl font-semibold tabular-nums">
                {readyCount}/{dataRoomChecklist.length}
              </span>
              <span className="text-sm text-muted-foreground">items ready</span>
            </div>
            <ul className="space-y-2">
              {dataRoomChecklist.map((c) => (
                <li key={c.label} className="flex items-center justify-between gap-2 text-sm">
                  <span className={c.ready ? "" : "text-muted-foreground"}>{c.label}</span>
                  {c.ready ? (
                    <Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700">
                      Ready
                    </Badge>
                  ) : (
                    <Badge variant="outline" className="gap-1 text-muted-foreground">
                      <Lock className="h-3 w-3" />
                      Pending
                    </Badge>
                  )}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
