// Playbook Library Seed Script — 20 MVP Playbooks
// Run: node server/playbook-seed.mjs
import mysql from "mysql2/promise";
import { config } from "dotenv";
config();

const PLAYBOOKS = [
  {
    playbookId: "PB-001",
    title: "Getting Started with ECOBLEND OS",
    category: "Platform Orientation",
    relatedModule: "command-centre",
    relatedWorkflowStage: "onboarding",
    userRole: "Founder,Venture Team,Studio Director",
    purpose: "Provide new users with a structured introduction to the EcoBlend OS platform, its modules, and the H4 Lean validation methodology.",
    whenToUse: "Use this playbook when a new founder, team member, or advisor joins the platform for the first time, or when onboarding a new venture.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Platform Tour", action: "Navigate the Command Centre and review the sidebar module structure. Identify the 12-stage validation pipeline." },
      { step: 2, title: "Venture Setup", action: "Create your first venture record in Venture Intake. Complete the basic profile: name, sector, tagline, and strategic classification." },
      { step: 3, title: "Understand Readiness Levels", action: "Review the seven readiness dimensions: VRL, TRL, BRL, MRL, SRL, IRL, PRL. Read the scoring guide for each." },
      { step: 4, title: "Set Initial Hypotheses", action: "Navigate to the Hypothesis Register and create at least 3 H4 Lean hypotheses for your venture." },
      { step: 5, title: "Assign Your Coach", action: "If you have an assigned coach, confirm the coaching assignment in the Coaching module." },
      { step: 6, title: "Review Stage-Gate Map", action: "Study the 12-stage validation pipeline and identify which stage your venture is currently in." },
      { step: 7, title: "Complete Orientation Checklist", action: "Mark all items in the completion checklist below before proceeding to Venture Intake." },
    ]),
    requiredInputs: JSON.stringify(["User account created", "Venture name and sector", "Founder profile information"]),
    requiredOutputs: JSON.stringify(["Venture record created", "Initial hypothesis set", "Coaching assignment confirmed", "Stage-gate position identified"]),
    linkedTemplates: JSON.stringify(["Platform Orientation Guide", "H4 Lean Hypothesis Template"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "TRL", "BRL", "MRL", "SRL", "IRL", "PRL"]),
    linkedRiskCategories: JSON.stringify([]),
    evidenceRequired: JSON.stringify(["Completed founder profile", "At least 1 venture record created"]),
    completionChecklist: JSON.stringify(["Platform tour completed", "Venture record created", "3+ hypotheses logged", "Coaching assignment confirmed", "Stage-gate position identified"]),
    accessLevel: "Venture Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-002",
    title: "New Venture Intake Playbook",
    category: "Venture Intake",
    relatedModule: "onboarding",
    relatedWorkflowStage: "intake",
    userRole: "Studio Director,Venture Lead,Founder",
    purpose: "Guide the structured intake of a new venture into the EcoBlend OS validation pipeline, ensuring all required data is captured before progression to Stage 1.",
    whenToUse: "Use when a new venture opportunity has been approved for intake following the Opportunity Pipeline scoring process.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Opportunity Confirmation", action: "Confirm the opportunity record in the Pipeline module shows status 'Approved' before proceeding." },
      { step: 2, title: "Venture Profile Creation", action: "Create the venture record: name, tagline, sector, channel (B2B/D2C/B2B2C), strategic classification, and engine of growth." },
      { step: 3, title: "Founder Profiling", action: "Complete the founder profile for each founding team member: background, domain expertise score (0-10), experience score, commitment score, and equity allocation." },
      { step: 4, title: "Strategic Fit Assessment", action: "Score the venture on the 7-dimension strategic fit matrix. Minimum score of 6.0 required to proceed." },
      { step: 5, title: "BRL Baseline", action: "Complete the 26-task BRL self-assessment to establish the baseline Business Readiness Level." },
      { step: 6, title: "Initial Hypothesis Register", action: "Create the first set of H4 Lean hypotheses covering customer, problem, solution, and business model assumptions." },
      { step: 7, title: "Coach Assignment", action: "Assign a coach from the coaching registry. Set the initial PRL baseline score." },
      { step: 8, title: "Stage-Gate 1 Approval", action: "Submit the venture for Stage-Gate 1 review. Required: complete founder profile, strategic fit score ≥ 6.0, and at least 3 hypotheses." },
    ]),
    requiredInputs: JSON.stringify(["Approved opportunity record", "Founder profiles", "Strategic fit scores", "Initial BRL assessment"]),
    requiredOutputs: JSON.stringify(["Venture record created", "Founder profiles complete", "BRL baseline established", "Initial hypotheses logged", "Coach assigned", "Stage-Gate 1 passed"]),
    linkedTemplates: JSON.stringify(["Venture Intake Form", "Founder Profile Template", "BRL Self-Assessment", "H4 Lean Hypothesis Template"]),
    linkedScoringFrameworks: JSON.stringify(["BRL", "VRL", "PRL"]),
    linkedRiskCategories: JSON.stringify(["People Risk", "Market Risk"]),
    evidenceRequired: JSON.stringify(["Completed founder profiles (all team members)", "Strategic fit score ≥ 6.0", "BRL baseline score", "Minimum 3 H4 hypotheses"]),
    completionChecklist: JSON.stringify(["Venture record created", "All founder profiles complete", "Strategic fit scored", "BRL baseline complete", "3+ hypotheses logged", "Coach assigned", "Stage-Gate 1 approved"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-003",
    title: "Problem Statement Playbook",
    category: "Discovery",
    relatedModule: "interviews",
    relatedWorkflowStage: "discovery",
    userRole: "Founder,Venture Lead",
    purpose: "Guide the founder through the structured articulation of a validated problem statement using the H4 Lean hypothesis framework.",
    whenToUse: "Use at the beginning of the Discovery stage, before conducting customer interviews. The problem statement must be defined before interviews begin.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Identify the Target Customer", action: "Define the specific customer segment: demographics, role, industry, and context. Be as specific as possible — avoid 'everyone'." },
      { step: 2, title: "Articulate the Problem", action: "Write the problem in the customer's language. Describe what they currently do (the workaround) and why it is inadequate." },
      { step: 3, title: "Define the Context", action: "Specify when and where the problem occurs. Context determines urgency and frequency." },
      { step: 4, title: "Write the H4 Hypothesis", action: "Format: 'We believe that [customer] experiences [problem] when [context]. We will know this is true when [criterion] with n ≥ [sample]'." },
      { step: 5, title: "Set Validation Criteria", action: "Define the minimum evidence threshold: how many interviews, what pain score threshold, what demand signal." },
      { step: 6, title: "Log in Hypothesis Register", action: "Enter the hypothesis in the platform with type = 'Problem', status = 'Unvalidated'." },
      { step: 7, title: "Peer Review", action: "Share the problem statement with the assigned coach or Studio Director for review before beginning interviews." },
    ]),
    requiredInputs: JSON.stringify(["Target customer segment definition", "Initial problem hypothesis", "Venture record in platform"]),
    requiredOutputs: JSON.stringify(["Validated H4 problem hypothesis", "Validation criteria defined", "Hypothesis logged in register"]),
    linkedTemplates: JSON.stringify(["H4 Lean Hypothesis Template", "Problem Statement Canvas"]),
    linkedScoringFrameworks: JSON.stringify(["VRL"]),
    linkedRiskCategories: JSON.stringify(["Market Risk"]),
    evidenceRequired: JSON.stringify(["Written H4 hypothesis", "Validation criteria defined", "Coach/Director review sign-off"]),
    completionChecklist: JSON.stringify(["Customer segment defined", "Problem articulated in customer language", "Context specified", "H4 hypothesis written", "Validation criteria set", "Hypothesis logged", "Peer review completed"]),
    accessLevel: "Venture Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-004",
    title: "Customer Discovery Interview Playbook",
    category: "Discovery",
    relatedModule: "interviews",
    relatedWorkflowStage: "discovery",
    userRole: "Founder,Venture Lead",
    purpose: "Guide the founder through the planning, execution, and analysis of customer discovery interviews to validate or invalidate the problem hypothesis.",
    whenToUse: "Use after the Problem Statement Playbook is complete and the H4 hypothesis is logged. Minimum 5 interviews required for VRL evidence.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Prepare Interview Guide", action: "Create an open-ended interview guide. Start with context questions, move to problem exploration, avoid leading questions. Do not pitch your solution." },
      { step: 2, title: "Recruit Participants", action: "Identify and recruit 10-15 target customers. Prioritise early adopters — people who feel the problem most acutely." },
      { step: 3, title: "Conduct Interviews", action: "Run 30-45 minute interviews. Record with consent. Listen for emotional language, workarounds, and frequency of the problem." },
      { step: 4, title: "Log Each Interview", action: "Enter each interview in the Interview Tracker: interviewee details, key insights, pain points, and validation signals." },
      { step: 5, title: "AI Summarisation", action: "Use the AI summarisation feature to extract key themes from raw transcripts." },
      { step: 6, title: "Analyse Patterns", action: "After 5+ interviews, review for recurring pain points. Calculate the pain score across interviews." },
      { step: 7, title: "Update Hypothesis", action: "Based on evidence, update the hypothesis status: Validated, Invalidated, or Pivoted. Log the decision rationale." },
      { step: 8, title: "VRL Evidence Submission", action: "Submit interview evidence to the VRL scoring module. Minimum 5 interviews with pain score ≥ 3.5 required for VRL Stage 1 progression." },
    ]),
    requiredInputs: JSON.stringify(["Validated H4 problem hypothesis", "Interview guide", "Recruited participants (min 5)"]),
    requiredOutputs: JSON.stringify(["Min 5 interview records logged", "Pain score calculated", "Hypothesis status updated", "VRL evidence submitted"]),
    linkedTemplates: JSON.stringify(["Customer Interview Guide Template", "Interview Analysis Framework"]),
    linkedScoringFrameworks: JSON.stringify(["VRL"]),
    linkedRiskCategories: JSON.stringify(["Market Risk"]),
    evidenceRequired: JSON.stringify(["Minimum 5 completed interview records", "Pain score ≥ 3.5 average", "Hypothesis status updated"]),
    completionChecklist: JSON.stringify(["Interview guide prepared", "10+ participants recruited", "5+ interviews conducted", "All interviews logged", "AI summaries reviewed", "Pattern analysis complete", "Hypothesis status updated", "VRL evidence submitted"]),
    accessLevel: "Venture Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-005",
    title: "Market Validation Playbook",
    category: "Market Validation",
    relatedModule: "market-intelligence",
    relatedWorkflowStage: "market-validation",
    userRole: "Founder,Venture Lead",
    purpose: "Guide the structured validation of market size, demand signals, and competitive landscape to support VRL Stage 2 progression.",
    whenToUse: "Use after completing at least 5 customer discovery interviews and confirming the problem hypothesis is validated.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Define Market Boundaries", action: "Define TAM (Total Addressable Market), SAM (Serviceable Addressable Market), and SOM (Serviceable Obtainable Market). Use bottom-up sizing methodology." },
      { step: 2, title: "Gather Market Evidence", action: "Collect at least 3 independent market size data points from credible sources (industry reports, government data, academic research)." },
      { step: 3, title: "Competitor Analysis", action: "Map at least 5 direct and indirect competitors. Score each on price, performance, and customer segment overlap." },
      { step: 4, title: "Demand Signal Validation", action: "Identify at least 3 demand signals: LOIs, waitlist sign-ups, pilot commitments, or pre-orders." },
      { step: 5, title: "Market Timing Assessment", action: "Assess market timing: is the market emerging, growing, mature, or declining? What macro trends are driving it?" },
      { step: 6, title: "Log Market Evidence", action: "Enter all market evidence in the Market Intelligence module with source, date, and confidence rating (1-5)." },
      { step: 7, title: "VRL Stage 2 Submission", action: "Submit market evidence to VRL scoring. Required: TAM/SAM/SOM defined, 3+ demand signals, competitor matrix complete." },
    ]),
    requiredInputs: JSON.stringify(["Validated problem hypothesis", "Customer interview data", "Market research sources"]),
    requiredOutputs: JSON.stringify(["TAM/SAM/SOM analysis", "Competitor matrix", "3+ demand signals", "Market evidence logged", "VRL Stage 2 evidence submitted"]),
    linkedTemplates: JSON.stringify(["Market Sizing Template", "Competitor Analysis Matrix"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "IRL"]),
    linkedRiskCategories: JSON.stringify(["Market Risk"]),
    evidenceRequired: JSON.stringify(["TAM/SAM/SOM with 3+ data sources", "Competitor matrix (5+ competitors)", "3+ demand signals documented"]),
    completionChecklist: JSON.stringify(["Market boundaries defined", "3+ market size data points", "5+ competitors mapped", "3+ demand signals identified", "Market timing assessed", "All evidence logged", "VRL Stage 2 submitted"]),
    accessLevel: "Venture Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-006",
    title: "Value Proposition Playbook",
    category: "Proposition",
    relatedModule: "brl",
    relatedWorkflowStage: "proposition",
    userRole: "Founder,Venture Lead",
    purpose: "Guide the structured development and validation of the venture's value proposition, ensuring alignment between customer pain, solution, and differentiation.",
    whenToUse: "Use after market validation is complete and demand signals are confirmed. This playbook precedes the Business Model Canvas.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Customer Jobs-to-be-Done", action: "List the functional, social, and emotional jobs your target customer is trying to accomplish." },
      { step: 2, title: "Pain Mapping", action: "Map the top 3 pains from your interview data to the jobs-to-be-done. Rank by severity and frequency." },
      { step: 3, title: "Gain Mapping", action: "Define the gains your customer desires: what outcomes would delight them beyond solving the pain." },
      { step: 4, title: "Solution Definition", action: "Define your product/service offering. For each pain, describe how your solution addresses it." },
      { step: 5, title: "Differentiation Statement", action: "Write a one-sentence differentiation statement: 'Unlike [alternative], our solution [unique benefit] because [reason to believe]'." },
      { step: 6, title: "Value Proposition Canvas", action: "Complete the Value Proposition Canvas and log it in the platform." },
      { step: 7, title: "Validation Test", action: "Test the value proposition with 5+ customers from your interview pool. Measure willingness to pay and preference over alternatives." },
    ]),
    requiredInputs: JSON.stringify(["Customer interview insights", "Pain point ranking", "Market validation data"]),
    requiredOutputs: JSON.stringify(["Jobs-to-be-done map", "Value Proposition Canvas", "Differentiation statement", "Validation test results"]),
    linkedTemplates: JSON.stringify(["Value Proposition Canvas", "Jobs-to-be-Done Framework"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "BRL"]),
    linkedRiskCategories: JSON.stringify(["Market Risk", "Business Model Risk"]),
    evidenceRequired: JSON.stringify(["Completed Value Proposition Canvas", "5+ customer validation test results", "Willingness to pay data"]),
    completionChecklist: JSON.stringify(["Jobs-to-be-done mapped", "Top 3 pains identified", "Gains defined", "Solution mapped to pains", "Differentiation statement written", "VPC completed", "5+ validation tests run"]),
    accessLevel: "Venture Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-007",
    title: "Business Model Canvas Playbook",
    category: "Business Model",
    relatedModule: "brl",
    relatedWorkflowStage: "proposition",
    userRole: "Founder,Venture Lead",
    purpose: "Guide the structured completion of the Business Model Canvas (BMC) and the initial revenue model hypothesis, establishing the BRL foundation.",
    whenToUse: "Use after the Value Proposition is validated. The BMC must be complete before BRL scoring can progress beyond Stage 1.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Value Propositions", action: "Transfer your validated value proposition into the BMC. Be specific about which customer segment each proposition serves." },
      { step: 2, title: "Customer Segments", action: "Define your primary and secondary customer segments. Identify early adopters within each segment." },
      { step: 3, title: "Channels", action: "Map your distribution and communication channels. Identify which channels your customers prefer." },
      { step: 4, title: "Customer Relationships", action: "Define the type of relationship you will establish with each segment: self-service, dedicated support, community, co-creation." },
      { step: 5, title: "Revenue Streams", action: "Define your revenue model: subscription, transaction, licensing, freemium, or other. Set initial pricing hypothesis." },
      { step: 6, title: "Key Resources", action: "Identify the critical assets required: IP, technology, people, financial, physical." },
      { step: 7, title: "Key Activities", action: "Define the most important activities the venture must perform to deliver the value proposition." },
      { step: 8, title: "Key Partners", action: "Identify strategic partners, suppliers, and ecosystem players required to operate the model." },
      { step: 9, title: "Cost Structure", action: "Map fixed and variable costs. Calculate unit economics: cost per unit, gross margin, contribution margin." },
      { step: 10, title: "Log BMC in Platform", action: "Enter the completed BMC in the BRL module. Set BRL status to 'Model Defined'." },
    ]),
    requiredInputs: JSON.stringify(["Validated value proposition", "Customer segment data", "Initial pricing hypothesis"]),
    requiredOutputs: JSON.stringify(["Completed Business Model Canvas", "Revenue model defined", "Unit economics calculated", "BRL Stage 1 evidence"]),
    linkedTemplates: JSON.stringify(["Business Model Canvas Template", "Unit Economics Calculator"]),
    linkedScoringFrameworks: JSON.stringify(["BRL", "IRL"]),
    linkedRiskCategories: JSON.stringify(["Business Model Risk", "Financial Risk"]),
    evidenceRequired: JSON.stringify(["All 9 BMC blocks completed", "Revenue model defined", "Unit economics calculated"]),
    completionChecklist: JSON.stringify(["All 9 BMC blocks completed", "Revenue streams defined", "Pricing hypothesis set", "Unit economics calculated", "Cost structure mapped", "BMC logged in platform", "BRL Stage 1 evidence submitted"]),
    accessLevel: "Venture Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-008",
    title: "R&D Project Setup Playbook",
    category: "R&D",
    relatedModule: "experiments",
    relatedWorkflowStage: "technical-validation",
    userRole: "Technical Lead,R&D Lead,Founder",
    purpose: "Guide the structured setup of an R&D project within the EcoBlend OS R&D Hub, including project classification, budget allocation, and TRL baseline.",
    whenToUse: "Use when initiating a new R&D project. All R&D activity must be logged in the platform before any budget is allocated.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Project Classification", action: "Classify the project: Iterative (70% pool), Adjacent (20% pool), or Moonshot (10% pool). Obtain Studio Director approval for Moonshot projects." },
      { step: 2, title: "Technical Requirements Document", action: "Write the Technical Requirements Document (TRD): scope, feasibility assessment, KPI targets (Specific Modulus, Specific Strength, Cycle Time, Delta-Cost, Weight Delta)." },
      { step: 3, title: "IP Clearance Check", action: "Conduct an IP clearance check. Identify any existing patents, trade secrets, or third-party IP that may affect the project." },
      { step: 4, title: "TRL Baseline", action: "Assess the current TRL level (1-9) for the technology. Document the evidence supporting the baseline assessment." },
      { step: 5, title: "Budget Allocation", action: "Allocate budget from the appropriate pool. Log the budget plan in the platform." },
      { step: 6, title: "Stage 1 Gate Approval", action: "Submit the TRD and IP clearance for Stage 1 gate approval by the Technical Lead." },
      { step: 7, title: "Experiment Log Setup", action: "Create the initial experiment records in the Experiment Log module." },
    ]),
    requiredInputs: JSON.stringify(["Project concept brief", "Technical feasibility assessment", "IP clearance check"]),
    requiredOutputs: JSON.stringify(["Technical Requirements Document", "Project classification confirmed", "Budget allocated", "TRL baseline established", "Stage 1 gate approved"]),
    linkedTemplates: JSON.stringify(["Technical Requirements Document Template", "IP Clearance Checklist", "R&D Budget Template"]),
    linkedScoringFrameworks: JSON.stringify(["TRL", "MRL"]),
    linkedRiskCategories: JSON.stringify(["Technical Risk", "IP / Legal Risk"]),
    evidenceRequired: JSON.stringify(["Signed TRD", "IP clearance confirmation", "Budget allocation record", "TRL baseline assessment"]),
    completionChecklist: JSON.stringify(["Project classified", "TRD written and approved", "IP clearance completed", "TRL baseline set", "Budget allocated", "Stage 1 gate approved", "Experiment log created"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Technical Lead",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-009",
    title: "Concept to Simulation Playbook",
    category: "R&D",
    relatedModule: "experiments",
    relatedWorkflowStage: "technical-validation",
    userRole: "Technical Lead,R&D Lead",
    purpose: "Guide the R&D team through Stage 2 of the R&D lifecycle: computational modelling and simulation to validate theoretical performance before physical prototyping.",
    whenToUse: "Use after Stage 1 gate approval. This playbook covers TRL 2-3 progression.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Simulation Model Design", action: "Design the computational model. Define the simulation parameters, boundary conditions, and validation criteria." },
      { step: 2, title: "Digital Twin Setup", action: "Set up the digital twin environment. Document the software tools, version numbers, and configuration." },
      { step: 3, title: "Run Simulations", action: "Execute simulation runs. Log each run as an experiment in the Experiment Log with hypothesis, method, and result." },
      { step: 4, title: "Results vs KPI Targets", action: "Compare simulation results against the KPI targets in the TRD. Document any deviations and their causes." },
      { step: 5, title: "Assumption Validation", action: "Identify which theoretical assumptions were validated and which were invalidated. Update the hypothesis register." },
      { step: 6, title: "Evidence Upload", action: "Upload simulation model files and results to the platform as TRL evidence." },
      { step: 7, title: "Stage 2 Gate Approval", action: "Submit simulation evidence for Stage 2 gate approval by Technical Lead and R&D Lead." },
    ]),
    requiredInputs: JSON.stringify(["Stage 1 gate approval", "Technical Requirements Document", "Simulation software environment"]),
    requiredOutputs: JSON.stringify(["Simulation model files", "Simulation results vs KPI targets", "Validated assumptions", "TRL 2-3 evidence", "Stage 2 gate approved"]),
    linkedTemplates: JSON.stringify(["Simulation Results Template", "TRL Evidence Log"]),
    linkedScoringFrameworks: JSON.stringify(["TRL"]),
    linkedRiskCategories: JSON.stringify(["Technical Risk"]),
    evidenceRequired: JSON.stringify(["Simulation model files uploaded", "Results vs KPI targets documented", "Stage 2 gate sign-off"]),
    completionChecklist: JSON.stringify(["Simulation model designed", "Digital twin configured", "3+ simulation runs completed", "Results vs KPIs documented", "Assumptions updated", "Evidence uploaded", "Stage 2 gate approved"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Technical Lead",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-010",
    title: "Prototype Testing Playbook",
    category: "R&D",
    relatedModule: "experiments",
    relatedWorkflowStage: "technical-validation",
    userRole: "Technical Lead,R&D Lead,Founder",
    purpose: "Guide the R&D team through Stage 3 of the R&D lifecycle: physical or digital prototype build and testing to validate real-world performance.",
    whenToUse: "Use after Stage 2 gate approval. This playbook covers TRL 4-6 progression.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Prototype Specification", action: "Write the prototype specification document: materials, dimensions, manufacturing method, and test protocol." },
      { step: 2, title: "Prototype Build", action: "Build the prototype. Log the build process, materials used, and any deviations from specification." },
      { step: 3, title: "Test Protocol Execution", action: "Execute the test protocol. Log each test as an experiment: hypothesis, method, result, and outcome (Pass/Fail/Inconclusive)." },
      { step: 4, title: "Results vs KPI Targets", action: "Compare test results against KPI targets. Document performance gaps and root cause analysis." },
      { step: 5, title: "Revised Risk Assessment", action: "Update the risk register based on prototype test findings. Identify any new technical risks." },
      { step: 6, title: "Evidence Upload", action: "Upload prototype specifications, test protocol, and test results as TRL evidence." },
      { step: 7, title: "Stage 3 Gate Approval", action: "Submit prototype evidence for Stage 3 gate approval by Technical Lead and Studio Director." },
    ]),
    requiredInputs: JSON.stringify(["Stage 2 gate approval", "Simulation results", "Prototype specification"]),
    requiredOutputs: JSON.stringify(["Prototype build record", "Test results vs KPI targets", "Revised risk assessment", "TRL 4-6 evidence", "Stage 3 gate approved"]),
    linkedTemplates: JSON.stringify(["Prototype Specification Template", "Test Protocol Template", "TRL Evidence Log"]),
    linkedScoringFrameworks: JSON.stringify(["TRL", "MRL"]),
    linkedRiskCategories: JSON.stringify(["Technical Risk", "Operational Risk"]),
    evidenceRequired: JSON.stringify(["Prototype specification document", "Test results uploaded", "Risk register updated", "Stage 3 gate sign-off"]),
    completionChecklist: JSON.stringify(["Prototype spec written", "Prototype built", "Test protocol executed", "Results vs KPIs documented", "Risk register updated", "Evidence uploaded", "Stage 3 gate approved"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Technical Lead",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-011",
    title: "Risk Assessment Playbook",
    category: "Risk Intelligence",
    relatedModule: "risk",
    relatedWorkflowStage: "risk-assessment",
    userRole: "Venture Lead,Studio Director,Founder",
    purpose: "Guide the structured identification, scoring, and logging of venture risks using the FMEA-based Risk Priority Number (RPN) methodology.",
    whenToUse: "Use at the start of each validation stage and whenever a new risk is identified. Risk assessment is a mandatory gate requirement at Stages 5, 8, and 11.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Risk Identification", action: "Systematically identify risks across all 10 risk types: Market, Technical, Business Model, Financial, Operational, People, IP/Legal, Supply Chain, Sustainability, Reputational." },
      { step: 2, title: "Risk Description", action: "For each risk, write a clear description: what could go wrong, what triggers it, and what the impact would be." },
      { step: 3, title: "Severity Scoring", action: "Score Severity (1-5): 1 = negligible impact, 5 = venture-ending impact." },
      { step: 4, title: "Probability Scoring", action: "Score Probability (1-5): 1 = very unlikely, 5 = near certain." },
      { step: 5, title: "Detectability Scoring", action: "Score Detectability (1-5): 1 = easily detected, 5 = very difficult to detect." },
      { step: 6, title: "RPN Calculation", action: "Calculate RPN = Severity × Probability × Detectability. Critical: 75-125. High: 40-74. Medium: 15-39. Low: 1-14." },
      { step: 7, title: "Log in Risk Register", action: "Enter all risks in the Risk Intelligence module with full scoring and owner assignment." },
      { step: 8, title: "Critical Risk Escalation", action: "Any risk with RPN ≥ 75 must be escalated to the Studio Director immediately and a mitigation plan initiated within 48 hours." },
    ]),
    requiredInputs: JSON.stringify(["Current venture stage", "Previous risk register (if exists)", "Input from all module leads"]),
    requiredOutputs: JSON.stringify(["Complete risk register", "RPN scores for all risks", "Critical risks escalated", "Risk owners assigned"]),
    linkedTemplates: JSON.stringify(["Risk Register Template", "FMEA Scoring Guide"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "TRL", "BRL"]),
    linkedRiskCategories: JSON.stringify(["Market Risk", "Technical Risk", "Business Model Risk", "Financial Risk", "Operational Risk", "People Risk", "IP / Legal Risk", "Supply Chain Risk", "Sustainability Risk", "Reputational Risk"]),
    evidenceRequired: JSON.stringify(["All 10 risk types assessed", "RPN calculated for each risk", "Critical risks escalated"]),
    completionChecklist: JSON.stringify(["All 10 risk types reviewed", "RPN scored for each risk", "Risk register updated", "Critical risks escalated", "Risk owners assigned", "Risk register submitted to stage-gate"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-012",
    title: "Mitigation Planning Playbook",
    category: "Risk Intelligence",
    relatedModule: "risk",
    relatedWorkflowStage: "risk-assessment",
    userRole: "Venture Lead,Studio Director",
    purpose: "Guide the development of structured mitigation plans for High and Critical risks identified in the Risk Assessment.",
    whenToUse: "Use immediately after Risk Assessment for any risk with RPN ≥ 40. Critical risks (RPN ≥ 75) require a mitigation plan within 48 hours.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Prioritise by RPN", action: "Sort risks by RPN descending. Begin mitigation planning with Critical risks, then High risks." },
      { step: 2, title: "Mitigation Strategy Selection", action: "For each risk, select a mitigation strategy: Avoid, Reduce, Transfer, or Accept. Document the rationale." },
      { step: 3, title: "Action Plan", action: "Define specific actions to implement the mitigation strategy. Assign an owner and due date for each action." },
      { step: 4, title: "Residual Risk Assessment", action: "After defining the mitigation plan, reassess Severity, Probability, and Detectability. Calculate Residual RPN." },
      { step: 5, title: "Mitigation Quality Rating", action: "Rate the quality of the mitigation plan (1-5). A rating < 3 requires review by Studio Director." },
      { step: 6, title: "Log Mitigation Plans", action: "Enter all mitigation plans in the Risk Intelligence module, linked to the corresponding risk record." },
      { step: 7, title: "Monitor and Update", action: "Review mitigation plan progress weekly. Update residual RPN as actions are completed." },
    ]),
    requiredInputs: JSON.stringify(["Completed risk register", "RPN scores", "Risk owners identified"]),
    requiredOutputs: JSON.stringify(["Mitigation plans for all High/Critical risks", "Residual RPN calculated", "Action owners assigned", "Review schedule set"]),
    linkedTemplates: JSON.stringify(["Mitigation Plan Template", "Residual Risk Calculator"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "TRL", "BRL"]),
    linkedRiskCategories: JSON.stringify(["Market Risk", "Technical Risk", "Business Model Risk", "Financial Risk", "Operational Risk"]),
    evidenceRequired: JSON.stringify(["Mitigation plan for each High/Critical risk", "Residual RPN < original RPN", "Action owners confirmed"]),
    completionChecklist: JSON.stringify(["All Critical risks have mitigation plans", "All High risks have mitigation plans", "Residual RPN calculated", "Action owners assigned", "Due dates set", "Plans logged in platform"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-013",
    title: "VRL Scoring Playbook",
    category: "Readiness Scoring",
    relatedModule: "vrl",
    relatedWorkflowStage: "readiness-scoring",
    userRole: "Venture Lead,Studio Director",
    purpose: "Guide the structured scoring of the Venture Readiness Level (VRL) dimension using validated customer and market evidence.",
    whenToUse: "Use at each stage-gate review and whenever new market or customer evidence is added. VRL scoring requires minimum evidence thresholds to be met.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Evidence Review", action: "Review all customer interview records, market evidence, and demand signals logged in the platform." },
      { step: 2, title: "VRL Stage Assessment", action: "Assess which VRL stage (1-4) the evidence supports: Stage 1 = Demand signal confirmed; Stage 2 = Paying customers; Stage 3 = Scaled revenue; Stage 4 = Market leadership." },
      { step: 3, title: "Evidence Confidence Rating", action: "Rate the confidence of each evidence item (1-5). Flag any items with confidence < 3 as 'Low Confidence'." },
      { step: 4, title: "Evidence Confidence Score", action: "Calculate the Evidence Confidence Score: weighted average of all evidence confidence ratings. Minimum 3.0 required." },
      { step: 5, title: "Missing Evidence Check", action: "Check minimum evidence thresholds: VRL requires 5+ customer interviews. Flag any gaps." },
      { step: 6, title: "Score Submission", action: "Submit the VRL score with evidence confidence rating. The system will flag Low Confidence scores with an amber indicator." },
      { step: 7, title: "Composite Score Update", action: "Confirm the VRL contribution to the composite readiness score (default weight: 20%)." },
    ]),
    requiredInputs: JSON.stringify(["Minimum 5 customer interview records", "Market evidence records", "Demand signals"]),
    requiredOutputs: JSON.stringify(["VRL stage score (1-4)", "Evidence confidence score", "Missing evidence flags resolved", "Composite score updated"]),
    linkedTemplates: JSON.stringify(["VRL Evidence Checklist", "Evidence Confidence Rating Guide"]),
    linkedScoringFrameworks: JSON.stringify(["VRL"]),
    linkedRiskCategories: JSON.stringify(["Market Risk"]),
    evidenceRequired: JSON.stringify(["5+ customer interviews", "3+ market evidence records", "Evidence confidence score ≥ 3.0"]),
    completionChecklist: JSON.stringify(["All evidence reviewed", "VRL stage assessed", "Evidence confidence rated", "Missing evidence resolved", "Score submitted", "Composite score updated"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-014",
    title: "TRL Scoring Playbook",
    category: "Readiness Scoring",
    relatedModule: "trl",
    relatedWorkflowStage: "readiness-scoring",
    userRole: "Technical Lead,Venture Lead",
    purpose: "Guide the structured scoring of the Technology Readiness Level (TRL) dimension using R&D project evidence.",
    whenToUse: "Use at each R&D stage gate and whenever new technical evidence is added. TRL scoring requires minimum evidence: 1 simulation + 1 prototype.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Evidence Review", action: "Review all R&D project records, experiment logs, simulation results, and prototype test results." },
      { step: 2, title: "TRL Level Assessment", action: "Assess the current TRL level (1-9): 1 = Basic principles; 3 = Proof of concept; 6 = Prototype validated; 9 = Production-proven." },
      { step: 3, title: "Evidence Confidence Rating", action: "Rate the confidence of each technical evidence item (1-5). Simulation evidence typically rates 3-4; prototype evidence rates 4-5." },
      { step: 4, title: "Missing Evidence Check", action: "Minimum requirements: TRL ≥ 3 requires 1 simulation record; TRL ≥ 5 requires 1 prototype test record." },
      { step: 5, title: "PRL Composite Update", action: "After updating TRL, trigger a PRL composite recalculation (PRL = 0.5 × TRL + 0.5 × MRL)." },
      { step: 6, title: "Score Submission", action: "Submit the TRL score with evidence confidence rating." },
    ]),
    requiredInputs: JSON.stringify(["R&D project records", "Experiment log entries", "Simulation results", "Prototype test results"]),
    requiredOutputs: JSON.stringify(["TRL level score (1-9)", "Evidence confidence score", "PRL composite updated", "Missing evidence flags resolved"]),
    linkedTemplates: JSON.stringify(["TRL Evidence Checklist", "TRL Scale Reference Guide"]),
    linkedScoringFrameworks: JSON.stringify(["TRL", "PRL (composite)"]),
    linkedRiskCategories: JSON.stringify(["Technical Risk"]),
    evidenceRequired: JSON.stringify(["1+ simulation record (for TRL ≥ 3)", "1+ prototype test record (for TRL ≥ 5)"]),
    completionChecklist: JSON.stringify(["All R&D evidence reviewed", "TRL level assessed", "Evidence confidence rated", "Missing evidence resolved", "PRL composite updated", "Score submitted"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Technical Lead",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-015",
    title: "BRL Scoring Playbook",
    category: "Readiness Scoring",
    relatedModule: "brl",
    relatedWorkflowStage: "readiness-scoring",
    userRole: "Venture Lead,Studio Director,Founder",
    purpose: "Guide the structured scoring of the Business Readiness Level (BRL) dimension using business model and commercial evidence.",
    whenToUse: "Use after the Business Model Canvas is complete. BRL requires BMC completion + pricing hypothesis as minimum evidence.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Evidence Review", action: "Review the Business Model Canvas, revenue model, unit economics, and channel validation evidence." },
      { step: 2, title: "BRL Stage Assessment", action: "Assess the BRL stage (0-9): 0 = No model; 3 = Model defined; 6 = Revenue generating; 9 = Scalable model proven." },
      { step: 3, title: "Revenue Model Validation", action: "Confirm the revenue model is validated: pricing hypothesis tested, willingness to pay confirmed, unit economics positive." },
      { step: 4, title: "Evidence Confidence Rating", action: "Rate the confidence of each business evidence item (1-5)." },
      { step: 5, title: "Missing Evidence Check", action: "Minimum requirements: BMC completed + pricing hypothesis. Flag any gaps." },
      { step: 6, title: "Score Submission", action: "Submit the BRL score with evidence confidence rating." },
    ]),
    requiredInputs: JSON.stringify(["Completed Business Model Canvas", "Revenue model", "Unit economics", "Pricing hypothesis test results"]),
    requiredOutputs: JSON.stringify(["BRL stage score (0-9)", "Evidence confidence score", "Missing evidence flags resolved"]),
    linkedTemplates: JSON.stringify(["BRL Evidence Checklist", "Unit Economics Template"]),
    linkedScoringFrameworks: JSON.stringify(["BRL"]),
    linkedRiskCategories: JSON.stringify(["Business Model Risk", "Financial Risk"]),
    evidenceRequired: JSON.stringify(["Completed BMC", "Pricing hypothesis tested", "Unit economics calculated"]),
    completionChecklist: JSON.stringify(["BMC reviewed", "Revenue model validated", "Unit economics confirmed", "Evidence confidence rated", "Score submitted"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-016",
    title: "Evidence Confidence Playbook",
    category: "Readiness Scoring",
    relatedModule: "vrl",
    relatedWorkflowStage: "readiness-scoring",
    userRole: "Venture Lead,Studio Director",
    purpose: "Guide the structured rating of evidence confidence across all readiness dimensions, ensuring scoring integrity and identifying missing evidence gaps.",
    whenToUse: "Use whenever submitting readiness scores. Evidence confidence rating is mandatory for all score submissions.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Understand the Confidence Scale", action: "1 = Anecdotal/unverified; 2 = Single source, unvalidated; 3 = Multiple sources, partially validated; 4 = Validated by independent party; 5 = Peer-reviewed or externally audited." },
      { step: 2, title: "Rate Each Evidence Item", action: "For each evidence record, assign a confidence rating (1-5). Document the rationale for ratings of 1-2." },
      { step: 3, title: "Calculate Dimension Score", action: "Evidence Confidence Score = Sum(evidence_weight × confidence_rating) / Sum(evidence_weights). Minimum 3.0 required." },
      { step: 4, title: "Flag Low Confidence", action: "Any dimension with confidence < 3.0 is flagged as 'Low Confidence'. The system generates a missing evidence warning." },
      { step: 5, title: "Resolve Missing Evidence", action: "For each missing evidence warning, create an action plan to gather the required evidence. Assign an owner and due date." },
      { step: 6, title: "Proceed/Pause Decision", action: "If confidence < 3.0 on any dimension, the system recommends 'Pause' regardless of the raw score." },
    ]),
    requiredInputs: JSON.stringify(["Evidence records for all dimensions", "Evidence source documentation"]),
    requiredOutputs: JSON.stringify(["Confidence ratings for all evidence", "Evidence confidence scores per dimension", "Missing evidence action plan"]),
    linkedTemplates: JSON.stringify(["Evidence Confidence Rating Guide", "Missing Evidence Action Plan Template"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "TRL", "BRL", "MRL", "SRL", "IRL", "PRL"]),
    linkedRiskCategories: JSON.stringify([]),
    evidenceRequired: JSON.stringify(["All evidence items rated", "Confidence score ≥ 3.0 per dimension"]),
    completionChecklist: JSON.stringify(["All evidence items rated", "Confidence scores calculated", "Low confidence flags reviewed", "Missing evidence action plans created", "Proceed/Pause decision documented"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-017",
    title: "Pitch Deck Preparation Playbook",
    category: "Investment Readiness",
    relatedModule: "investment-module",
    relatedWorkflowStage: "investment-readiness",
    userRole: "Founder,Venture Lead,Studio Director",
    purpose: "Guide the structured preparation of an investor pitch deck that is grounded in validated evidence from the EcoBlend OS platform.",
    whenToUse: "Use when the composite readiness score reaches ≥ 6.0 and the venture is approaching Stage 9 (Investment Readiness Gate).",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Readiness Check", action: "Confirm composite readiness score ≥ 6.0, evidence confidence ≥ 3.5, and no open Critical risks before beginning." },
      { step: 2, title: "Slide Structure", action: "Follow the 12-slide structure: Problem, Solution, Market, Product, Business Model, Traction, Team, Financials, Use of Funds, Competitive Advantage, Impact, Ask." },
      { step: 3, title: "Evidence-Backed Claims", action: "Every quantitative claim must be traceable to a platform evidence record. No unsubstantiated numbers." },
      { step: 4, title: "Traction Slide", action: "Pull traction data from the platform: interview count, demand signals, pilot customers, revenue (if any)." },
      { step: 5, title: "Financial Projections", action: "Use the Financial Model Builder to generate 3-year projections. Base case, bull case, and bear case." },
      { step: 6, title: "Impact Narrative", action: "Include the social impact thesis linked to the IRL evidence and nominated charity/SDG alignment." },
      { step: 7, title: "Studio Director Review", action: "Submit the draft pitch deck for Studio Director review before any investor presentation." },
      { step: 8, title: "Investor Data Room Preparation", action: "Proceed to the Investor Data Room Playbook (PB-018) to prepare supporting documentation." },
    ]),
    requiredInputs: JSON.stringify(["Composite readiness score ≥ 6.0", "Evidence confidence ≥ 3.5", "No open Critical risks", "Financial model"]),
    requiredOutputs: JSON.stringify(["12-slide pitch deck", "Evidence-backed claims", "Studio Director sign-off", "Investor data room initiated"]),
    linkedTemplates: JSON.stringify(["Pitch Deck Template", "Financial Projections Template", "Impact Narrative Framework"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "TRL", "BRL", "IRL"]),
    linkedRiskCategories: JSON.stringify(["Financial Risk", "Reputational Risk"]),
    evidenceRequired: JSON.stringify(["Composite score ≥ 6.0", "Evidence confidence ≥ 3.5", "Zero open Critical risks", "Studio Director sign-off"]),
    completionChecklist: JSON.stringify(["Readiness check passed", "12-slide structure followed", "All claims evidence-backed", "Traction data pulled", "Financial projections included", "Impact narrative included", "Studio Director reviewed", "Data room initiated"]),
    accessLevel: "Venture Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-018",
    title: "Investor Data Room Playbook",
    category: "Investment Readiness",
    relatedModule: "investor-data-room",
    relatedWorkflowStage: "investment-readiness",
    userRole: "Founder,Venture Lead,Studio Director",
    purpose: "Guide the structured assembly of an investor data room using evidence and documents from the EcoBlend OS platform.",
    whenToUse: "Use alongside or immediately after the Pitch Deck Preparation Playbook. The data room must be complete before investor meetings.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Data Room Structure", action: "Create the data room folder structure: Company Overview, Financials, Legal, Product/Technology, Market, Team, Impact." },
      { step: 2, title: "Company Overview", action: "Include: pitch deck, executive summary, cap table, corporate structure." },
      { step: 3, title: "Financials", action: "Include: 3-year financial model, historical financials (if any), unit economics analysis, use of funds breakdown." },
      { step: 4, title: "Legal", action: "Include: incorporation documents, IP filings, key contracts, IP clearance records." },
      { step: 5, title: "Product/Technology", action: "Include: TRL evidence summary, prototype documentation, technical KPI results, R&D roadmap." },
      { step: 6, title: "Market", action: "Include: TAM/SAM/SOM analysis, competitor matrix, customer interview summary, demand signals." },
      { step: 7, title: "Team", action: "Include: founder profiles, advisor profiles, org chart, ESOP structure." },
      { step: 8, title: "Impact", action: "Include: IRL evidence summary, SDG alignment, nominated charity documentation, B Corp progress (if applicable)." },
      { step: 9, title: "Access Control", action: "Set appropriate access levels for each section. Investor View access for standard data room; Admin Only for sensitive legal documents." },
      { step: 10, title: "Studio Director Sign-off", action: "Obtain Studio Director sign-off before sharing the data room link with any investor." },
    ]),
    requiredInputs: JSON.stringify(["Completed pitch deck", "Financial model", "Legal documents", "TRL evidence", "Market evidence", "Team profiles"]),
    requiredOutputs: JSON.stringify(["Complete investor data room", "Access controls set", "Studio Director sign-off", "Data room link ready to share"]),
    linkedTemplates: JSON.stringify(["Data Room Checklist", "Executive Summary Template"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "TRL", "BRL", "IRL"]),
    linkedRiskCategories: JSON.stringify(["Financial Risk", "IP / Legal Risk", "Reputational Risk"]),
    evidenceRequired: JSON.stringify(["All 7 data room sections populated", "Studio Director sign-off"]),
    completionChecklist: JSON.stringify(["Company overview complete", "Financials complete", "Legal documents uploaded", "Product/technology section complete", "Market section complete", "Team section complete", "Impact section complete", "Access controls set", "Studio Director sign-off obtained"]),
    accessLevel: "Investor View",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-019",
    title: "Execution Roadmap Playbook",
    category: "Execution Planning",
    relatedModule: "project-management",
    relatedWorkflowStage: "execution-planning",
    userRole: "Founder,Venture Lead,Studio Director",
    purpose: "Guide the structured development of an execution roadmap with milestones, budget plan, and hiring plan following investment gate approval.",
    whenToUse: "Use after Stage 9 (Investment Readiness Gate) is passed. The execution roadmap is a mandatory deliverable for Stage 10.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Milestone Definition", action: "Define 12-month milestones across all active modules. Each milestone must have: title, owner, due date, success criteria, and budget." },
      { step: 2, title: "Critical Path Analysis", action: "Identify the critical path: the sequence of milestones that determines the minimum time to reach the next stage gate." },
      { step: 3, title: "Budget Plan", action: "Allocate the investment budget across milestones. Use the 70-20-10 model for R&D budget allocation." },
      { step: 4, title: "Hiring Plan", action: "Define the hiring plan: roles required, timeline, and budget. Link to the People & ESOP module." },
      { step: 5, title: "Risk Integration", action: "Map open risks to milestones. Identify which risks could block milestone completion." },
      { step: 6, title: "KPI Dashboard Setup", action: "Define the KPIs that will be tracked on the Command Centre dashboard for this execution phase." },
      { step: 7, title: "Studio Director Approval", action: "Submit the execution roadmap for Studio Director approval. Required for Stage 10 gate." },
    ]),
    requiredInputs: JSON.stringify(["Investment gate approval", "Investment amount confirmed", "Open risk register"]),
    requiredOutputs: JSON.stringify(["12-month milestone plan", "Budget allocation", "Hiring plan", "KPI dashboard configured", "Studio Director approval"]),
    linkedTemplates: JSON.stringify(["Execution Roadmap Template", "Budget Plan Template", "Hiring Plan Template"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "TRL", "BRL", "PRL"]),
    linkedRiskCategories: JSON.stringify(["Operational Risk", "Financial Risk", "People Risk"]),
    evidenceRequired: JSON.stringify(["Milestone plan approved", "Budget allocated", "Hiring plan confirmed", "Studio Director sign-off"]),
    completionChecklist: JSON.stringify(["Milestones defined", "Critical path identified", "Budget allocated", "Hiring plan complete", "Risks mapped to milestones", "KPI dashboard configured", "Studio Director approved"]),
    accessLevel: "Internal Team",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
  {
    playbookId: "PB-020",
    title: "Stage-Gate Approval Playbook",
    category: "Governance",
    relatedModule: "impact",
    relatedWorkflowStage: "governance",
    userRole: "Studio Director,Governance Board",
    purpose: "Guide the structured preparation and execution of a stage-gate review, ensuring all required evidence and decisions are documented in the Governance module.",
    whenToUse: "Use before each of the 12 stage-gate reviews. The stage-gate approval process is mandatory for progression between validation stages.",
    stepByStepGuidance: JSON.stringify([
      { step: 1, title: "Readiness Pack Preparation", action: "Compile the stage-gate readiness pack: composite readiness score, evidence confidence scores, open risks, milestone completion status." },
      { step: 2, title: "Proceed/Pause/Pivot Check", action: "Apply the P/P/P/T logic: Proceed (composite ≥ 6.0, confidence ≥ 3.5, 0 critical risks); Pause (4.0-5.9); Pivot (VRL < 3); Terminate (< 3.0 across 3+ dimensions)." },
      { step: 3, title: "Gate Decision Meeting", action: "Convene the gate decision meeting with the required approvers (see stage-gate matrix). Present the readiness pack." },
      { step: 4, title: "Decision Recording", action: "Record the gate decision in the Governance module: Proceed, Pause, Pivot, or Terminate. Document the rationale." },
      { step: 5, title: "Conditions (if Pause)", action: "If Pause: define the specific conditions that must be met before the gate is re-reviewed. Set a review date." },
      { step: 6, title: "Pivot Planning (if Pivot)", action: "If Pivot: initiate the pivot planning process. Update the hypothesis register and restart the relevant validation stages." },
      { step: 7, title: "Audit Log Entry", action: "Confirm the gate decision is logged in the Audit Log with all approver names and timestamps." },
      { step: 8, title: "Next Stage Activation", action: "If Proceed: activate the next stage modules in the sidebar. Notify the venture team." },
    ]),
    requiredInputs: JSON.stringify(["Composite readiness score", "Evidence confidence scores", "Open risk register", "Milestone completion status", "Required approvers available"]),
    requiredOutputs: JSON.stringify(["Gate decision recorded (Proceed/Pause/Pivot/Terminate)", "Decision rationale documented", "Audit log entry confirmed", "Next stage activated (if Proceed)"]),
    linkedTemplates: JSON.stringify(["Stage-Gate Readiness Pack Template", "Gate Decision Record Template"]),
    linkedScoringFrameworks: JSON.stringify(["VRL", "TRL", "BRL", "MRL", "SRL", "IRL", "PRL"]),
    linkedRiskCategories: JSON.stringify(["Market Risk", "Technical Risk", "Business Model Risk", "Financial Risk"]),
    evidenceRequired: JSON.stringify(["Composite score documented", "Evidence confidence scores documented", "All approvers sign-off recorded"]),
    completionChecklist: JSON.stringify(["Readiness pack prepared", "P/P/P/T logic applied", "Gate meeting convened", "Decision recorded", "Conditions set (if Pause)", "Pivot plan initiated (if Pivot)", "Audit log confirmed", "Next stage activated (if Proceed)"]),
    approvalRequired: true,
    accessLevel: "Admin Only",
    status: "Published",
    owner: "Studio Director",
    reviewDate: "2026-12-31",
    createdBy: "EcoBlend OS",
  },
];

async function seed() {
  const conn = await mysql.createConnection(process.env.DATABASE_URL);
  let inserted = 0;
  let skipped = 0;
  for (const pb of PLAYBOOKS) {
    const [rows] = await conn.execute("SELECT id FROM playbook_library WHERE playbookId = ?", [pb.playbookId]);
    if (rows.length > 0) { skipped++; continue; }
    await conn.execute(
      `INSERT INTO playbook_library (playbookId, title, category, relatedModule, relatedWorkflowStage, userRole, purpose, whenToUse, stepByStepGuidance, requiredInputs, requiredOutputs, linkedTemplates, linkedScoringFrameworks, linkedRiskCategories, evidenceRequired, completionChecklist, approvalRequired, accessLevel, version, status, owner, reviewDate, createdBy, updatedBy) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
      [pb.playbookId, pb.title, pb.category, pb.relatedModule || null, pb.relatedWorkflowStage || null, pb.userRole || null, pb.purpose || null, pb.whenToUse || null, pb.stepByStepGuidance || null, pb.requiredInputs || null, pb.requiredOutputs || null, pb.linkedTemplates || null, pb.linkedScoringFrameworks || null, pb.linkedRiskCategories || null, pb.evidenceRequired || null, pb.completionChecklist || null, pb.approvalRequired ? 1 : 0, pb.accessLevel, "1.0", pb.status, pb.owner || null, pb.reviewDate || null, pb.createdBy || null, null]
    );
    inserted++;
  }
  console.log(`Seed complete: ${inserted} inserted, ${skipped} skipped`);
  await conn.end();
}
seed().catch(console.error);
