/**
 * Production venture seed — runs at server startup ONLY when the ventures
 * table is empty.  Safe to leave in permanently; the early-exit guard ensures
 * it is a no-op after the first successful run.
 */
import { getDb } from "./db";
import { sql } from "drizzle-orm";

// ─── Seed data ────────────────────────────────────────────────────────────────

const VENTURES = [
  { id: "bebus",       name: "BEBUS",               tagline: "Demand-responsive rural transport",          sector: "Mobility",           channel: "B2B", status: "Pre-Launch", vrl: 2, vrlPercent: 0, trl: 3, trlPercent: 0, color: "#3B85BA", investmentReady: false, isInternalLab: false, lifecycleStage: "Opportunity", strategicClassification: "Sustaining", productMarketFitSignal: "Not Yet", currentStage: "market_validation",    validationStatus: "validating", ventureType: "B2B SaaS",          owner: "A. Okafor", workflowStage: "customer_discovery", pivotRequired: false, canvasVersion: 1, createdAt: new Date("2026-06-02T15:42:50.228Z"), updatedAt: new Date("2026-06-02T16:41:18.736Z") },
  { id: "ecocomp",     name: "ECOCOMP",              tagline: "Bio-based composite materials",              sector: "Advanced Materials", channel: "B2B", status: "Pre-Launch", vrl: 2, vrlPercent: 0, trl: 3, trlPercent: 0, color: "#56A837", investmentReady: false, isInternalLab: false, lifecycleStage: "Opportunity", strategicClassification: "Sustaining", productMarketFitSignal: "Not Yet", currentStage: "commercial_validation", validationStatus: "building",   ventureType: "Deep Tech",         owner: "L. Nguyen", workflowStage: null,               pivotRequired: false, canvasVersion: 1, createdAt: new Date("2026-06-02T15:42:50.368Z"), updatedAt: new Date("2026-06-02T16:41:18.963Z") },
  { id: "real",        name: "REAL",                 tagline: "Real-time emissions accounting",             sector: "Climate Tech",       channel: "B2B", status: "Pre-Launch", vrl: 2, vrlPercent: 0, trl: 3, trlPercent: 0, color: "#F69111", investmentReady: false, isInternalLab: false, lifecycleStage: "Opportunity", strategicClassification: "Sustaining", productMarketFitSignal: "Not Yet", currentStage: "mvp_validation",        validationStatus: "piloting",   ventureType: "Consumer Brand",    owner: "M. Rossi",  workflowStage: "build_prototype",    pivotRequired: false, canvasVersion: 2, createdAt: new Date("2026-06-02T15:42:50.372Z"), updatedAt: new Date("2026-06-06T13:35:40.038Z") },
  { id: "tone",        name: "TONE",                 tagline: "Modular sustainable creative equipment",     sector: "Creative Industries",channel: "B2B", status: "Pre-Launch", vrl: 1, vrlPercent: 0, trl: 1, trlPercent: 0, color: "#8B5CF6", investmentReady: false, isInternalLab: false, lifecycleStage: "Opportunity", strategicClassification: "Sustaining", productMarketFitSignal: "Not Yet", currentStage: "problem_validation",    validationStatus: "validating", ventureType: "Hardware / Rental", owner: "S. Patel",  workflowStage: null,               pivotRequired: false, canvasVersion: 1, createdAt: new Date("2026-06-02T16:41:19.083Z"), updatedAt: new Date("2026-06-02T16:41:19.082Z") },
  { id: "ECOCOMP-002", name: "ECOCOMP BioForm",      tagline: null,                                         sector: null,                 channel: "B2B", status: "Pre-Launch", vrl: 1, vrlPercent: 0, trl: 1, trlPercent: 0, color: "#51AF37", investmentReady: false, isInternalLab: false, lifecycleStage: "Opportunity", strategicClassification: "Sustaining", productMarketFitSignal: "Not Yet", currentStage: null,                    validationStatus: "building",   ventureType: null,                owner: null,        workflowStage: "operations_mrl",     pivotRequired: false, canvasVersion: 3, createdAt: new Date("2026-06-06T14:12:25.321Z"), updatedAt: new Date("2026-06-06T14:22:00.856Z") },
  { id: "ECOSHIELD-001",name: "EcoShield Materials Ltd", tagline: null,                                      sector: null,                 channel: "B2B", status: "active",     vrl: 1, vrlPercent: 0, trl: 1, trlPercent: 0, color: "#51AF37", investmentReady: false, isInternalLab: false, lifecycleStage: "Opportunity", strategicClassification: "Sustaining", productMarketFitSignal: "Not Yet", currentStage: null,                    validationStatus: null,         ventureType: null,                owner: null,        workflowStage: "pre_seed",           pivotRequired: false, canvasVersion: 0, createdAt: new Date("2026-06-06T16:28:37.220Z"), updatedAt: new Date("2026-06-06T16:28:37.220Z") },
] as const;

const CC_HYPOTHESES = [
  { id: 12, ventureId: "bebus",       moduleSource: "discovery_market",  hypothesisType: "problem",          assumptionRiskLevel: "high",     status: "testing",   confidenceScore: 45, evidenceSummary: "8 interviews with procurement managers confirm the standards gap.",                                                                  hypothesisStatement: "UK construction procurement managers struggle to find bio-based composite materials that meet BS EN ISO structural standards, leading to spec sheet rewrites and project delays." },
  { id: 13, ventureId: "bebus",       moduleSource: "proposition_model", hypothesisType: "pricing",          assumptionRiskLevel: "critical", status: "untested",  confidenceScore: 20, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "Structural architects will pay a 12–18 % premium for bio-sourced composites if a certified ISO compliance data pack is bundled at point of sale." },
  { id: 14, ventureId: "bebus",       moduleSource: "brand_gtm",         hypothesisType: "channel",          assumptionRiskLevel: "medium",   status: "untested",  confidenceScore: 10, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "Tier-2 builders merchants are the most efficient route to market, reducing customer acquisition cost below £45 per £1 K of GMV." },
  { id: 15, ventureId: "ecocomp",     moduleSource: "discovery_market",  hypothesisType: "value_proposition",assumptionRiskLevel: "critical", status: "testing",   confidenceScore: 62, evidenceSummary: "3 interviews completed — 2 buyers expressed strong interest conditional on ASTM safety certifications.",                               hypothesisStatement: "Enterprise procurement managers in motorsport and industrial sectors will pay a 15 % premium for bio-based composite materials that carry a full LCA (lifecycle assessment) certificate." },
  { id: 16, ventureId: "ecocomp",     moduleSource: "rd_hub",            hypothesisType: "solution",         assumptionRiskLevel: "high",     status: "testing",   confidenceScore: 55, evidenceSummary: "First prototype batch shows 91 % tensile parity — additional cure-cycle optimisation required.",                                       hypothesisStatement: "A drop-in bio-resin formulation can achieve 95 % of the tensile strength of standard epoxy at equivalent cure temperatures, validated by ISO 527 testing." },
  { id: 17, ventureId: "ecocomp",     moduleSource: "discovery_market",  hypothesisType: "customer_segment", assumptionRiskLevel: "medium",   status: "validated", confidenceScore: 78, evidenceSummary: "Two LOI-level commitments from Formula E teams; confirmed sustainability mandate in technical regulations.",                              hypothesisStatement: "Formula E and sustainable motorsport teams form the beachhead segment — they have sustainability mandates AND budget to pay for premium materials." },
  { id: 18, ventureId: "real",        moduleSource: "discovery_market",  hypothesisType: "problem",          assumptionRiskLevel: "high",     status: "validated", confidenceScore: 73, evidenceSummary: "12 interviews with indie brand founders confirm lead-time as the #1 pain point.",                                                        hypothesisStatement: "Independent fashion brands sourcing sustainable fabric face a 6–10 week lead time penalty vs conventional fabric, blocking seasonal collection timelines." },
  { id: 19, ventureId: "real",        moduleSource: "proposition_model", hypothesisType: "business_model",   assumptionRiskLevel: "high",     status: "testing",   confidenceScore: 38, evidenceSummary: "Pilot of 3 brands on subscription model — churn rate 33 % after first drop.",                                                          hypothesisStatement: "A fabric-as-a-service subscription (min. 500m per drop) reduces buyer risk and creates predictable demand for our production planning." },
  { id: 20, ventureId: "tone",        moduleSource: "venture_intake",    hypothesisType: "problem",          assumptionRiskLevel: "critical", status: "untested",  confidenceScore: 15, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "SME food brands cannot access compostable packaging that passes UK WRAP standards at under £0.08 per unit — forcing them to use conventional plastic." },
  { id: 21, ventureId: "tone",        moduleSource: "venture_intake",    hypothesisType: "customer_segment", assumptionRiskLevel: "medium",   status: "untested",  confidenceScore:  8, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "Artisan bakeries (50–500 units/week) are the most price-tolerant segment for sustainable packaging because they can pass the cost on as a premium brand signal." },
  { id: 22, ventureId: "bebus",       moduleSource: "venture_intake",    hypothesisType: "customer_segment", assumptionRiskLevel: "high",     status: "untested",  confidenceScore:  0, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "We believe that engineering directors and fleet maintenance managers at UK bus operators are the primary buyers and decision-makers for reliability intelligence tools. We will know this when 3+ EDs engage in a structured paid discovery conversation." },
  { id: 23, ventureId: "bebus",       moduleSource: "venture_intake",    hypothesisType: "problem",          assumptionRiskLevel: "critical", status: "untested",  confidenceScore:  0, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "We believe that UK bus operators lose measurable revenue due to avoidable downtime caused by fragmented reliability data. We will know this when 5+ fleet managers confirm downtime cost as a top-3 operational priority." },
  { id: 24, ventureId: "bebus",       moduleSource: "venture_intake",    hypothesisType: "value_proposition",assumptionRiskLevel: "high",     status: "untested",  confidenceScore:  0, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "We believe that structured reliability intelligence will reduce avoidable downtime by >15% within 12 months. We will know this when paid pilot operators demonstrate measurable improvement within a structured pilot period." },
  { id: 25, ventureId: "ecocomp",     moduleSource: "venture_intake",    hypothesisType: "customer_segment", assumptionRiskLevel: "critical", status: "untested",  confidenceScore:  0, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "We believe that R&D and procurement leads at European manufacturers seeking lower-carbon materials are willing to pay for validated eco-material formulations before full-scale production proof." },
  { id: 26, ventureId: "ecocomp",     moduleSource: "venture_intake",    hypothesisType: "problem",          assumptionRiskLevel: "high",     status: "untested",  confidenceScore:  0, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "We believe that manufacturers cannot independently validate eco-material performance and compliance risk within acceptable development timelines. We will know this when 5+ R&D leads confirm this as a blocking problem." },
  { id: 27, ventureId: "real",        moduleSource: "venture_intake",    hypothesisType: "customer_segment", assumptionRiskLevel: "critical", status: "untested",  confidenceScore:  0, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "We believe that performance-first combat sports athletes aged 18–35 will pay a premium for sustainable equipment if performance matches or exceeds conventional alternatives." },
  { id: 28, ventureId: "real",        moduleSource: "venture_intake",    hypothesisType: "problem",          assumptionRiskLevel: "medium",   status: "untested",  confidenceScore:  0, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "We believe that no credible sustainable combat sports brand exists that athletes trust for performance. We will know this when research shows <5% brand awareness for sustainable alternatives among target athletes." },
  { id: 29, ventureId: "tone",        moduleSource: "venture_intake",    hypothesisType: "customer_segment", assumptionRiskLevel: "critical", status: "untested",  confidenceScore:  0, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "We believe that creative production operators will switch to modular sustainable equipment if it reduces cost, storage burden, and environmental impact simultaneously." },
  { id: 30, ventureId: "tone",        moduleSource: "venture_intake",    hypothesisType: "problem",          assumptionRiskLevel: "high",     status: "untested",  confidenceScore:  0, evidenceSummary: null,                                                                                                                                 hypothesisStatement: "We believe that creative production operators waste >20% of equipment budget on single-use or rapidly obsolete conventional systems. We will know this when 5+ operators confirm this cost pattern." },
];

const CC_EXPERIMENTS = [
  { id: 12, ventureId: "bebus",   hypothesisId: 12, experimentName: "Procurement Manager Pain Interview — Round 1", experimentType: "customer_interview", moduleSource: "discovery_market",  experimentStatus: "completed", method: "30-min structured interviews with 10 procurement managers at Tier-1 UK contractors.",                  successThreshold: "7/10 confirm standards-gap as a blocking pain point.", startDate: "2026-02-01", dueDate: "2026-02-28", result: "8/10 confirmed; 3 mentioned BREEAM certification as linked requirement.",                                                       learningSummary: "Standards gap is real and blocking. BREEAM angle is an unanticipated opportunity.",       decisionRecommendation: "Continue testing" },
  { id: 13, ventureId: "bebus",   hypothesisId: 13, experimentName: "ISO Bundle Pricing Test — Conjoint Survey",    experimentType: "pricing_test",        moduleSource: "proposition_model", experimentStatus: "running",   method: "Online conjoint survey (n=80) presenting 5 pricing bundles with/without ISO data pack.",            successThreshold: "≥50 % of respondents choose bundle with ISO pack at 15 % premium.",                    startDate: "2026-04-01", dueDate: "2026-06-15", result: null,                                                                                                          learningSummary: null,                                                                                       decisionRecommendation: null },
  { id: 14, ventureId: "ecocomp", hypothesisId: 15, experimentName: "Formula E Procurement LOI Test",               experimentType: "loi_test",            moduleSource: "discovery_market",  experimentStatus: "completed", method: "Present bio-composite spec sheet + LCA certificate to 5 Formula E teams and request non-binding LOI.",  successThreshold: "2 of 5 teams sign LOI.",                                                               startDate: "2026-01-15", dueDate: "2026-02-28", result: "2 LOIs received; 1 conditional on ASTM F3502-21 certification by Q3 2026.",                           learningSummary: "Demand validated in beachhead. ASTM certification is the next gate.",                      decisionRecommendation: "Advance to ASTM certification sprint." },
  { id: 15, ventureId: "ecocomp", hypothesisId: 16, experimentName: "ISO 527 Tensile Strength Lab Test — Batch 2",  experimentType: "manufacturing_test",  moduleSource: "rd_hub",            experimentStatus: "running",   method: "Run 3 cure-cycle variants through ISO 527 tensile testing at Cardiff University composite lab.",      successThreshold: "At least 1 variant achieves ≥95 % tensile parity with standard epoxy.",                startDate: "2026-05-01", dueDate: "2026-07-31", result: null,                                                                                                          learningSummary: null,                                                                                       decisionRecommendation: null },
  { id: 16, ventureId: "ecocomp", hypothesisId: 17, experimentName: "Industrial Sector Cold Outreach — Aerospace MRO", experimentType: "channel_test",    moduleSource: "brand_gtm",         experimentStatus: "proposed",  method: "Cold outreach to 20 aerospace MRO procurement contacts with a 1-page LCA summary.",                  successThreshold: "≥3 replies requesting a follow-up call.",                                              startDate: "2026-07-01", dueDate: "2026-07-31", result: null,                                                                                                          learningSummary: null,                                                                                       decisionRecommendation: null },
  { id: 17, ventureId: "real",    hypothesisId: 18, experimentName: "Fabric Lead-Time Discovery Sprint",            experimentType: "customer_interview", moduleSource: "discovery_market",  experimentStatus: "completed", method: "12 structured interviews with indie fashion brands (< 500 units/season).",                             successThreshold: "8/12 cite lead time as #1 or #2 supplier pain.",                                       startDate: "2026-01-10", dueDate: "2026-02-10", result: "11/12 cited lead time as primary pain; 6 mentioned sustainability credential as secondary value driver.",    learningSummary: "Problem strongly validated. Sustainability + speed is the core value proposition.",        decisionRecommendation: "Advance to subscription model experiment." },
  { id: 18, ventureId: "real",    hypothesisId: 19, experimentName: "FaaS Subscription Pilot — 3 Brands",          experimentType: "paid_pilot",          moduleSource: "proposition_model", experimentStatus: "running",   method: "Enrol 3 indie brands on a 3-drop subscription at 500 m minimum per drop.",                           successThreshold: "All 3 brands renew after drop 1; churn ≤ 10 %.",                                       startDate: "2026-03-01", dueDate: "2026-08-31", result: null,                                                                                                          learningSummary: null,                                                                                       decisionRecommendation: null },
  { id: 19, ventureId: "tone",    hypothesisId: 20, experimentName: "Bakery Pain Discovery — 5 Artisan Bakeries",  experimentType: "customer_interview", moduleSource: "venture_intake",    experimentStatus: "proposed",  method: "5 in-person interviews at artisan bakeries in London to surface packaging cost and compliance pain.", successThreshold: "4/5 confirm price-per-unit as primary barrier to sustainable packaging adoption.",       startDate: "2026-06-10", dueDate: "2026-06-30", result: null,                                                                                                          learningSummary: null,                                                                                       decisionRecommendation: null },
  { id: 20, ventureId: "tone",    hypothesisId: 21, experimentName: "WRAP-Compliant Compostable Unit Cost Benchmark", experimentType: "supplier_test",   moduleSource: "operations_mfg",    experimentStatus: "proposed",  method: "RFQ to 3 compostable packaging suppliers for WRAP-certified pouches at 500-unit MOQ.",              successThreshold: "At least 1 supplier quotes ≤ £0.10 per unit at 500-unit MOQ.",                         startDate: "2026-06-15", dueDate: "2026-07-15", result: null,                                                                                                          learningSummary: null,                                                                                       decisionRecommendation: null },
];

const CC_STAGE_GATE_REVIEWS = [
  { id: 5,  ventureId: "bebus",       fromStage: "problem_validation", toStage: "market_validation",    reviewStatus: "conditional_approval", evidenceScore: 65, marketScore: 58, commercialScore: 40, technicalScore: 55, operationalScore: 45, riskScore: 55, investmentReadinessScore: 38, approvalDecision: "request_more_evidence", reviewDate: "2026-03-15", nextReviewDate: "2026-07-15", gateType: null,               humanReviewRequired: true, humanReviewedBy: null,        humanReviewedAt: null,                              reviewerNotes: "Problem validation is solid. Market validation score below 60 threshold. Pricing test must be completed and WTP confirmed before full progression.",            requiredActions: "Complete conjoint pricing survey; achieve >60 % WTP confirmation at ≥12 % premium; resubmit for market validation gate." },
  { id: 6,  ventureId: "ecocomp",     fromStage: "market_validation",  toStage: "commercial_validation",reviewStatus: "approved",             evidenceScore: 78, marketScore: 75, commercialScore: 68, technicalScore: 62, operationalScore: 55, riskScore: 60, investmentReadinessScore: 58, approvalDecision: "approve_progression",  reviewDate: "2026-04-15", nextReviewDate: "2026-10-01", gateType: null,               humanReviewRequired: true, humanReviewedBy: null,        humanReviewedAt: null,                              reviewerNotes: "Strong evidence base. LOIs validate market demand. ASTM certification progress is on track. Approved to advance to commercial validation stage with ASTM cert as a condition of stage close.", requiredActions: "Deliver ASTM F3502-21 certification by 30 Sep 2026." },
  { id: 7,  ventureId: "real",        fromStage: "market_validation",  toStage: "commercial_validation",reviewStatus: "under_review",         evidenceScore: 80, marketScore: 82, commercialScore: 50, technicalScore: 70, operationalScore: 60, riskScore: 52, investmentReadinessScore: 45, approvalDecision: null,                   reviewDate: "2026-06-01", nextReviewDate: "2026-08-01", gateType: null,               humanReviewRequired: true, humanReviewedBy: null,        humanReviewedAt: null,                              reviewerNotes: "Problem-solution fit is strongly validated. Business model pivot underway — commercial score will be re-assessed once new MOQ pricing is modelled. Review on hold pending pivot outcome.",     requiredActions: "Complete business model pivot (MOQ reduction); remodel unit economics; resubmit commercial score." },
  { id: 8,  ventureId: "tone",        fromStage: "intake",             toStage: "problem_validation",   reviewStatus: "not_started",          evidenceScore: 15, marketScore: 12, commercialScore:  5, technicalScore: 10, operationalScore:  5, riskScore: 20, investmentReadinessScore:  5, approvalDecision: null,                   reviewDate: null,         nextReviewDate: "2026-09-01", gateType: null,               humanReviewRequired: true, humanReviewedBy: null,        humanReviewedAt: null,                              reviewerNotes: "Venture is at intake stage. Minimum evidence threshold not met. Stage-gate review will be scheduled once 10 discovery interviews and supplier RFQ benchmark are complete.",                    requiredActions: "Complete 10 bakery discovery interviews; complete 3 supplier RFQs; return with evidence pack." },
  { id: 9,  ventureId: "ECOCOMP-002", fromStage: null,                 toStage: null,                   reviewStatus: "not_started",          evidenceScore:  0, marketScore:  0, commercialScore:  0, technicalScore:  0, operationalScore:  0, riskScore:  0, investmentReadinessScore:  0, approvalDecision: "approved",             reviewDate: "2026-06-06", nextReviewDate: null,          gateType: "mvp_evidence_strong", humanReviewRequired: true, humanReviewedBy: "test_runner", humanReviewedAt: new Date("2026-06-06T14:18:21.400Z"), reviewerNotes: null,                                                                                                                                                                                                       requiredActions: null },
  { id: 10, ventureId: "ECOCOMP-002", fromStage: null,                 toStage: null,                   reviewStatus: "not_started",          evidenceScore:  0, marketScore:  0, commercialScore:  0, technicalScore:  0, operationalScore:  0, riskScore:  0, investmentReadinessScore:  0, approvalDecision: "approved",             reviewDate: "2026-06-06", nextReviewDate: null,          gateType: "mvp_evidence_strong", humanReviewRequired: true, humanReviewedBy: "test_runner", humanReviewedAt: new Date("2026-06-06T14:21:06.950Z"), reviewerNotes: "Step-3 test: validated post-pivot, 67% rate acceptable",                                                                                                                                    requiredActions: null },
  { id: 11, ventureId: "ECOCOMP-002", fromStage: null,                 toStage: null,                   reviewStatus: "not_started",          evidenceScore:  0, marketScore:  0, commercialScore:  0, technicalScore:  0, operationalScore:  0, riskScore:  0, investmentReadinessScore:  0, approvalDecision: "approved",             reviewDate: "2026-06-06", nextReviewDate: null,          gateType: "mvp_evidence_strong", humanReviewRequired: true, humanReviewedBy: "test_runner", humanReviewedAt: new Date("2026-06-06T14:22:00.817Z"), reviewerNotes: "Step-3 test: validated post-pivot, 67% rate acceptable",                                                                                                                                    requiredActions: null },
];

const CC_EVIDENCE = [
  { id: 12, ventureId: "bebus",   hypothesisId: 12, experimentId: 12,   moduleSource: "discovery_market",  evidenceType: "interview",            contradictsHypothesis: false, evidenceStrengthScore: 4, evidenceRelevanceScore: 5, evidenceRecencyScore: 5, evidenceConfidenceScore: 75, sourceReference: "Interview batch BEB-INT-001 to BEB-INT-010, Feb 2026",           evidenceTitle: "10 Procurement Manager Interviews — Standards Gap Confirmed",   evidenceSummary: "8 of 10 UK Tier-1 contractor procurement managers identified the absence of BS EN ISO compliant bio-composite datasheets as a recurring specification barrier. Average project delay attributed: 3.2 weeks." },
  { id: 13, ventureId: "bebus",   hypothesisId: 13, experimentId: 13,   moduleSource: "discovery_market",  evidenceType: "demand_signal",        contradictsHypothesis: false, evidenceStrengthScore: 3, evidenceRelevanceScore: 4, evidenceRecencyScore: 4, evidenceConfidenceScore: 58, sourceReference: "ASL confirmations, Mar 2026",                                     evidenceTitle: "3 Contractors Added to Approved Supplier List",                evidenceSummary: "Three contractors added BEBUS to their approved supplier list pending ISO data pack delivery." },
  { id: 14, ventureId: "bebus",   hypothesisId: 14, experimentId: null, moduleSource: "discovery_market",  evidenceType: "competitor_signal",    contradictsHypothesis: false, evidenceStrengthScore: 3, evidenceRelevanceScore: 4, evidenceRecencyScore: 3, evidenceConfidenceScore: 52, sourceReference: "Competitor mapping, Mar 2026",                                    evidenceTitle: "Competitor Analysis: No UK Supplier Offers ISO Bundle",        evidenceSummary: "Desk research across 12 UK bio-composite suppliers shows none currently bundle an ISO compliance data pack with purchase. BEBUS has a 6–12 month first-mover window." },
  { id: 15, ventureId: "ecocomp", hypothesisId: 15, experimentId: 14,   moduleSource: "discovery_market",  evidenceType: "customer_commitment",  contradictsHypothesis: false, evidenceStrengthScore: 4, evidenceRelevanceScore: 5, evidenceRecencyScore: 5, evidenceConfidenceScore: 80, sourceReference: "LOI-ECOCOMP-001 and LOI-ECOCOMP-002, Feb 2026",               evidenceTitle: "2 Formula E Teams — Non-Binding LOI Signed",                   evidenceSummary: "Team Envision and Mahindra Racing signed non-binding LOIs for bio-composite trial kits at the stated 15 % premium. Both conditional on ASTM F3502-21 certification by Q3 2026." },
  { id: 16, ventureId: "ecocomp", hypothesisId: 16, experimentId: 15,   moduleSource: "rd_hub",            evidenceType: "prototype_result",     contradictsHypothesis: false, evidenceStrengthScore: 4, evidenceRelevanceScore: 5, evidenceRecencyScore: 5, evidenceConfidenceScore: 70, sourceReference: "Cardiff Composites Lab Report ISO527-ECOCOMP-B1, Apr 2026",    evidenceTitle: "ISO 527 Batch 1 — 91 % Tensile Parity Achieved",              evidenceSummary: "First batch of bio-resin composite coupons tested at Cardiff University: mean tensile strength 91 % of control epoxy (target: 95 %). Cure-cycle C2 showed best result. Batch 2 cure-cycle optimisation underway." },
  { id: 17, ventureId: "ecocomp", hypothesisId: 17, experimentId: 16,   moduleSource: "discovery_market",  evidenceType: "interview",            contradictsHypothesis: true,  evidenceStrengthScore: 2, evidenceRelevanceScore: 3, evidenceRecencyScore: 4, evidenceConfidenceScore: 35, sourceReference: "Exploratory call, May 2026",                                     evidenceTitle: "Industrial Aerospace MRO Buyer — No Immediate Demand",         evidenceSummary: "Preliminary discussion with a Tier-2 aerospace MRO buyer indicated bio-composite adoption blocked by AS9100D supply-chain audit requirement. Price premium irrelevant until certification achieved." },
  { id: 18, ventureId: "real",    hypothesisId: 18, experimentId: 17,   moduleSource: "discovery_market",  evidenceType: "interview",            contradictsHypothesis: false, evidenceStrengthScore: 5, evidenceRelevanceScore: 5, evidenceRecencyScore: 5, evidenceConfidenceScore: 88, sourceReference: "Interview batch REAL-INT-001 to REAL-INT-012, Jan–Feb 2026",   evidenceTitle: "12 Indie Brand Interviews — Lead-Time Pain Confirmed",         evidenceSummary: "11 of 12 indie fashion brand founders cited sustainable fabric lead time (6–10 weeks) as their primary supplier pain. 6 cited sustainability credentials as a secondary value driver. Strong problem-solution fit signal." },
  { id: 19, ventureId: "real",    hypothesisId: 19, experimentId: 18,   moduleSource: "proposition_model", evidenceType: "pilot_result",         contradictsHypothesis: true,  evidenceStrengthScore: 3, evidenceRelevanceScore: 4, evidenceRecencyScore: 5, evidenceConfidenceScore: 55, sourceReference: "FaaS Pilot Report DROP-1-REAL, May 2026",                      evidenceTitle: "FaaS Pilot Drop 1 — 33 % Churn After First Delivery",          evidenceSummary: "Of the 3 pilot brands, 1 churned after Drop 1 citing minimum order quantity (500 m) as too high for their seasonal volume. The 2 remaining brands rated quality 4.5/5 and lead time as met." },
  { id: 20, ventureId: "tone",    hypothesisId: 20, experimentId: 19,   moduleSource: "venture_intake",    evidenceType: "academic_research",    contradictsHypothesis: true,  evidenceStrengthScore: 4, evidenceRelevanceScore: 5, evidenceRecencyScore: 5, evidenceConfidenceScore: 72, sourceReference: "WRAP Sustainable Packaging Market Report 2025, Mar 2026",     evidenceTitle: "WRAP 2025 Report: SME Food Packaging Compostable Costs",       evidenceSummary: "WRAP 2025 market report shows average unit cost for UK WRAP-certified compostable pouches is £0.12–0.18 at sub-1000 unit MOQ. TONE's £0.08 target requires a 33–55 % cost reduction — achievable only at 5000+ unit volumes." },
  { id: 21, ventureId: "tone",    hypothesisId: 21, experimentId: 20,   moduleSource: "venture_intake",    evidenceType: "demand_signal",        contradictsHypothesis: false, evidenceStrengthScore: 2, evidenceRelevanceScore: 3, evidenceRecencyScore: 5, evidenceConfidenceScore: 32, sourceReference: "Borough Market intercept survey, Jun 2026",                   evidenceTitle: "3 Bakeries Express Interest in Sustainable Packaging Switch",  evidenceSummary: "3 of 5 artisan bakeries surveyed at a London food market expressed interest in switching to compostable packaging if price was within 20 % of current spend. None aware of WRAP certification requirement." },
];

const CC_DECISIONS = [
  { id: 5,  ventureId: "bebus",       decisionType: "persevere",             decisionStatus: "approved",          evidenceConfidenceScore: 65, riskScore: 35, recommendedAction: "Run conjoint pricing survey (n=80) to validate the 12–18 % premium hypothesis.",                                                             approvedBy: "EcoRace Studio Review Board", decisionDate: "2026-03-15", nextReviewDate: "2026-07-01", reviewerNotes: "Approved at VRL Gate Review 2. Pricing test must complete by end of Q2 2026.",              decisionTitle: "Persevere: Advance ISO Bundle Concept to Pricing Test",          decisionSummary: "Evidence from 8 procurement interviews confirms the standards-gap pain point. ISO bundle concept validated directionally. Move to conjoint pricing survey to confirm willingness-to-pay before product investment." },
  { id: 6,  ventureId: "ecocomp",     decisionType: "persevere",             decisionStatus: "implemented",       evidenceConfidenceScore: 72, riskScore: 28, recommendedAction: "Prioritise ASTM F3502-21 certification sprint; de-prioritise aerospace outreach until Formula E beachhead is secured.",                approvedBy: "EcoRace Studio Review Board", decisionDate: "2026-04-01", nextReviewDate: "2026-09-01", reviewerNotes: "Certification sprint approved. Budget of £35 K allocated. Aerospace deferred to Q4.",       decisionTitle: "Persevere: Accelerate ASTM Certification Sprint",                decisionSummary: "2 LOIs from Formula E teams confirm WTP at the 15 % premium, conditional on ASTM F3502-21. ISO 527 batch 1 at 91 % tensile parity — near target. Aerospace route blocked by AS9100D. Focus on motorsport beachhead and deliver ASTM cert by Q3." },
  { id: 7,  ventureId: "real",        decisionType: "pivot",                 decisionStatus: "pending_approval",  evidenceConfidenceScore: 60, riskScore: 45, recommendedAction: "Reduce minimum subscription drop to 200 m. Model impact on unit economics. Requalify churned pilot brand.",                              approvedBy: null,                          decisionDate: "2026-06-01", nextReviewDate: "2026-07-15", reviewerNotes: "Needs finance sign-off to confirm gross margin at 200 m MOQ.",                          decisionTitle: "Pivot: Reduce Subscription MOQ from 500 m to 200 m",            decisionSummary: "FaaS pilot churn of 33 % after Drop 1 attributed to MOQ being too high for small brands. Problem validation is strong (11/12 interviews), but the business model requires adjustment. Reduce MOQ to 200 m to re-qualify churned brand and broaden addressable segment." },
  { id: 8,  ventureId: "tone",        decisionType: "request_more_evidence", decisionStatus: "recommended",       evidenceConfidenceScore: 22, riskScore: 75, recommendedAction: "Complete 10 bakery interviews and 3 supplier RFQs before any further commitment.",                                                        approvedBy: null,                          decisionDate: "2026-06-05", nextReviewDate: "2026-08-01", reviewerNotes: "Venture too early for major investment. Discovery sprint is the right next move.",        decisionTitle: "Hold: Run Discovery Sprint Before Any Product Investment",       decisionSummary: "WRAP report shows current unit-cost target (£0.08) only reachable at 5000+ units — far above current demand signals. Customer validation is nascent. No product investment until 10 interviews confirm WTP and realistic volume." },
  { id: 10, ventureId: "ECOCOMP-002", decisionType: "persevere",             decisionStatus: "recommended",       evidenceConfidenceScore:  0, riskScore:  0, recommendedAction: "advance",                                                                                                                               approvedBy: null,                          decisionDate: null,         nextReviewDate: null,          reviewerNotes: null,                                                                                       decisionTitle: "Advance to MVP Evidence Gate — post-pivot validation cleared",   decisionSummary: null },
  { id: 11, ventureId: "ECOCOMP-002", decisionType: "persevere",             decisionStatus: "approved",          evidenceConfidenceScore:  0, riskScore:  0, recommendedAction: "advance",                                                                                                                               approvedBy: null,                          decisionDate: null,         nextReviewDate: null,          reviewerNotes: null,                                                                                       decisionTitle: "Advance to MVP Evidence Gate — post-pivot validation cleared",   decisionSummary: null },
  { id: 12, ventureId: "ECOCOMP-002", decisionType: "persevere",             decisionStatus: "approved",          evidenceConfidenceScore:  0, riskScore:  0, recommendedAction: "advance",                                                                                                                               approvedBy: null,                          decisionDate: null,         nextReviewDate: null,          reviewerNotes: null,                                                                                       decisionTitle: "Advance to Operations MRL — MVP evidence gate cleared",          decisionSummary: null },
];

const CC_PIVOT_LOGS = [
  { id: 2, ventureId: "real", pivotType: "business_model", decisionId: 7, hypothesisId: 19, dateLogged: "2026-06-01",
    previousHypothesis: "A fabric-as-a-service subscription (min. 500m per drop) reduces buyer risk and creates predictable demand for our production planning.",
    newHypothesis:       "A fabric-as-a-service subscription (min. 200m per drop) is the right entry point for indie brands with seasonal volumes under 1000 m/season, improving retention without critically damaging unit economics.",
    reasonForPivot:      "33 % churn after FaaS Drop 1 attributed to minimum order quantity (500 m) exceeding typical indie brand seasonal volume. Reducing MOQ to 200 m requalifies churned segment.",
    evidenceTrigger:     "FaaS Pilot Report DROP-1-REAL: 1 of 3 brands churned citing MOQ as sole barrier." },
];

const LEAN_CANVASES = [
  { id: 1,  ventureId: "real",        version: 1, status: "archived", overallStatus: "draft",          createdBy: "priya.okafor@real.group", createdAt: new Date("2026-06-06T13:34:15.653Z"), updatedAt: new Date("2026-06-06T13:34:50.294Z"), canvasTitle: null, versionLabel: null, changeSummary: null, reasonForChange: null, evidenceTrigger: null, problem: "Current EPS foam helmet liners absorb linear impacts but fail to dissipate rotational forces — the primary biomechanical cause of concussion. OEMs have no certified composite alternative that maintains weight and cost parity.", solution: "Reengineered multi-layer composite liner: outer TPU energy-dispersal shell + inner carbon-fibre honeycomb absorber + bio-resin matrix. REAL proprietary formulation developed in partnership with St Mary's materials lab.", uniqueValueProp: "First composite liner with independently validated 40%+ rotational impact absorption improvement AND EN 960 / NOCSAE dual certification pathway — certified safety, not just performance claims.", customerSegments: "Helmet OEM R&D directors and procurement leads at Tier 1 sports protection manufacturers (Riddell, Schutt, Xenith, UK equivalents). Secondary: sports governing bodies (World Rugby, RFL) who approve certification pathways.", channels: "Direct OEM R&D partnership (primary). World Rugby supplier qualification programme (secondary). Sports safety governing body endorsement as commercial trust signal.", revenueStreams: "B2B composite component supply: £28–£45 per liner unit at OEM volume (10,000+ units/year). IP licensing of formulation for non-competing product categories. Certification testing services (secondary).", costStructure: "Materials: ~£9–£14/unit at scale. Certification testing: £40k–£80k one-time per standard. R&D lab partnership: £2k–£5k/month. Manufacturing tooling: £15k–£25k one-time.", keyMetrics: "Rotational impact absorption improvement vs EN 960 baseline (target: ≥40%). Liner weight vs EPS baseline (target: ±5% weight parity). Time to first OEM qualification test (target: <6 months). LOI conversion rate.", unfairAdvantage: "REAL composite formulation developed within the ECORACE STUDIO IP framework — Lambert Agreement in place, PCT patent filing in progress. St Mary's University materials lab as Tier 2 academic partner provides independent TRL validation. ECOBLEND OS evidence vault generates independently verifiable TRL progression.", mvpFormat: "concierge", hypothesisTested: "Rugby and contact sport helmet OEMs need a reengineered composite liner that absorbs rotational impact forces 40% more efficiently than current EPS foam.", successCriteria: "Minimum 2 signed paid qualification trial agreements (500 units each at ≥£28/unit) within 12 weeks.", existingAlternatives: null, highLevelConcept: null },
  { id: 3,  ventureId: "real",        version: 2, status: "active",   overallStatus: "draft",          createdBy: "priya.okafor@real.group", createdAt: new Date("2026-06-06T13:34:54.629Z"), updatedAt: new Date("2026-06-06T13:34:54.629Z"), canvasTitle: null, versionLabel: null, changeSummary: null, reasonForChange: null, evidenceTrigger: null, problem: "Current EPS foam helmet liners absorb linear impacts but fail to dissipate rotational forces — the primary biomechanical cause of concussion. OEMs have no certified composite alternative that maintains weight and cost parity.", solution: "Reengineered multi-layer composite liner: outer TPU energy-dispersal shell + inner carbon-fibre honeycomb absorber + bio-resin matrix. REAL proprietary formulation developed in partnership with St Mary's materials lab.", uniqueValueProp: "First composite liner with independently validated 40%+ rotational impact absorption improvement AND EN 960 / NOCSAE dual certification pathway — certified safety, not just performance claims.", customerSegments: "Procurement directors at Tier 1 helmet OEMs — not R&D. R&D acts as technical validator but does not hold budget authority. Target buyer: procurement director with annual components budget >£500k. Secondary: World Rugby preferred supplier programme as qualification gateway.", channels: "Direct OEM R&D partnership (primary). World Rugby supplier qualification programme (secondary). Sports safety governing body endorsement as commercial trust signal.", revenueStreams: "B2B composite component supply: £28–£45 per liner unit at OEM volume (10,000+ units/year). IP licensing of formulation for non-competing product categories. Certification testing services (secondary).", costStructure: "Materials: ~£9–£14/unit at scale. Certification testing: £40k–£80k one-time per standard. R&D lab partnership: £2k–£5k/month. Manufacturing tooling: £15k–£25k one-time.", keyMetrics: "Rotational impact absorption improvement vs EN 960 baseline (target: ≥40%). Liner weight vs EPS baseline (target: ±5% weight parity). Time to first OEM qualification test (target: <6 months). LOI conversion rate.", unfairAdvantage: "REAL composite formulation developed within the ECORACE STUDIO IP framework — Lambert Agreement in place, PCT patent filing in progress. St Mary's University materials lab as Tier 2 academic partner provides independent TRL validation. ECOBLEND OS evidence vault generates independently verifiable TRL progression.", mvpFormat: "concierge", hypothesisTested: "Rugby and contact sport helmet OEMs need a reengineered composite liner that absorbs rotational impact forces 40% more efficiently than current EPS foam.", successCriteria: "Minimum 2 signed paid qualification trial agreements (500 units each at ≥£28/unit) within 12 weeks.", existingAlternatives: null, highLevelConcept: null },
  { id: 6,  ventureId: "ECOCOMP-002", version: 1, status: "active",   overallStatus: "draft",          createdBy: "test_runner",             createdAt: new Date("2026-06-06T14:12:31.310Z"), updatedAt: new Date("2026-06-06T14:12:31.310Z"), canvasTitle: null, versionLabel: null, changeSummary: null, reasonForChange: null, evidenceTrigger: null, problem: "Industrial bio-waste processing requires costly manual sorting", solution: "AI-driven enzymatic separation + concierge validation with pilot customers", uniqueValueProp: null, customerSegments: "Mid-size food manufacturers (50-500 employees)", channels: null, revenueStreams: "Per-tonne processing fee + annual SaaS licence", costStructure: null, keyMetrics: null, unfairAdvantage: null, mvpFormat: null, hypothesisTested: null, successCriteria: null, existingAlternatives: null, highLevelConcept: null },
  { id: 7,  ventureId: "ECOCOMP-002", version: 2, status: "active",   overallStatus: "draft",          createdBy: "test_runner",             createdAt: new Date("2026-06-06T14:18:21.343Z"), updatedAt: new Date("2026-06-06T14:18:21.343Z"), canvasTitle: null, versionLabel: null, changeSummary: null, reasonForChange: null, evidenceTrigger: null, problem: "Industrial bio-waste processing requires costly manual sorting", solution: "AI-driven enzymatic separation + concierge validation with pilot customers", uniqueValueProp: null, customerSegments: "Mid-size food manufacturers (50-500 employees)", channels: null, revenueStreams: "Per-tonne processing fee + annual SaaS licence", costStructure: null, keyMetrics: null, unfairAdvantage: null, mvpFormat: null, hypothesisTested: null, successCriteria: null, existingAlternatives: null, highLevelConcept: null },
  { id: 8,  ventureId: "ECOCOMP-002", version: 3, status: "active",   overallStatus: "draft",          createdBy: "test_runner",             createdAt: new Date("2026-06-06T14:18:21.352Z"), updatedAt: new Date("2026-06-06T14:18:21.352Z"), canvasTitle: null, versionLabel: null, changeSummary: null, reasonForChange: null, evidenceTrigger: null, problem: "Industrial bio-waste processing requires costly manual sorting", solution: "Per-tonne variable-rate processing service with enzymatic sorting + outcome guarantee", uniqueValueProp: null, customerSegments: "Mid-size food manufacturers (50-500 employees)", channels: null, revenueStreams: "Per-tonne variable fee (replaces per-seat SaaS)", costStructure: null, keyMetrics: null, unfairAdvantage: null, mvpFormat: null, hypothesisTested: null, successCriteria: null, existingAlternatives: null, highLevelConcept: null },
  { id: 9,  ventureId: "bebus",       version: 1, status: "active",   overallStatus: "assumption_led", createdBy: null,                      createdAt: new Date("2026-06-08T08:54:57.681Z"), updatedAt: new Date("2026-06-08T08:54:57.681Z"), canvasTitle: "BEBUS Initial Canvas",   versionLabel: "Founder Assumption Canvas", changeSummary: null, reasonForChange: "new_canvas", evidenceTrigger: null, problem: "Zero-emission bus operators experience avoidable downtime because reliability data is fragmented across OEMs, suppliers, and maintenance teams.", solution: "Reliability intelligence workflow combining defect capture, root-cause tracking, supplier evidence, and readiness scoring.", uniqueValueProp: "Reduce avoidable downtime and improve supplier accountability through structured reliability intelligence.", customerSegments: "UK bus operators, fleet engineering teams, engineering directors, maintenance managers, supplier quality teams.", channels: "Founder-led sales, bus operator network, industry partnerships, reliability engineering case studies.", revenueStreams: "Paid pilot followed by consultancy-plus-platform subscription.", costStructure: "Engineering analysis, platform development, data onboarding, customer support, supplier engagement.", keyMetrics: "Paid pilot conversion, downtime issue resolution rate, WTP evidence level, budget-holder introductions, reliability data access.", unfairAdvantage: "Founder reliability engineering expertise, BEBUS domain knowledge, proprietary operational learning, repeatable reliability intelligence templates.", mvpFormat: null, hypothesisTested: null, successCriteria: null, existingAlternatives: "OEM support, internal maintenance teams, Excel reliability logs, consultancy reports, supplier meetings.", highLevelConcept: "Reliability intelligence for zero-emission bus operators." },
  { id: 10, ventureId: "ecocomp",     version: 1, status: "active",   overallStatus: "assumption_led", createdBy: null,                      createdAt: new Date("2026-06-08T08:54:57.681Z"), updatedAt: new Date("2026-06-08T08:54:57.681Z"), canvasTitle: "ECOCOMP Initial Canvas", versionLabel: "Founder Assumption Canvas", changeSummary: null, reasonForChange: "new_canvas", evidenceTrigger: null, problem: "Manufacturers need lower-carbon materials that meet performance, compliance, and production requirements without increasing technical risk.", solution: "Formulation intelligence, material validation workflow, supplier evidence, performance data capture, compliance readiness scoring.", uniqueValueProp: "Validated sustainable composite formulations that reduce development uncertainty and compliance risk.", customerSegments: "Manufacturers seeking sustainable composite materials, product designers, sustainability leads, innovation teams.", channels: "Industry partnerships, university links, manufacturer pilots, sustainability innovation programmes.", revenueStreams: "Formulation development fee, licensing, paid validation sprint, data partnership.", costStructure: "Materials testing, formulation development, supplier coordination, certification support, platform data capture.", keyMetrics: "Paid formulation sprint conversion, formulation validation pass rate, licensing interest, WTP evidence level, customer technical data shared.", unfairAdvantage: "Proprietary formulation data, trade secrets, repeatability knowledge, controlled access to materials intelligence.", mvpFormat: null, hypothesisTested: null, successCriteria: null, existingAlternatives: "Conventional composites, supplier material sheets, internal R&D, sustainability consultants, university research.", highLevelConcept: "Sustainable formulation intelligence for composite manufacturers." },
  { id: 11, ventureId: "real",        version: 1, status: "active",   overallStatus: "assumption_led", createdBy: null,                      createdAt: new Date("2026-06-08T08:54:57.681Z"), updatedAt: new Date("2026-06-08T08:54:57.681Z"), canvasTitle: "REAL Initial Canvas",    versionLabel: "Founder Assumption Canvas", changeSummary: null, reasonForChange: "new_canvas", evidenceTrigger: null, problem: "Combat sports customers want credible sustainable protective equipment but will not compromise on performance, durability, or brand trust.", solution: "Prototype protective equipment, sustainable material selection, athlete testing, performance validation, gym partner feedback.", uniqueValueProp: "High-performance combat sports equipment using credible sustainable materials without compromising durability.", customerSegments: "Combat sports athletes, gyms, coaches, specialist retailers, performance-focused customers.", channels: "D2C, gym partnerships, athlete ambassadors, combat sports events, specialist retailers.", revenueStreams: "Product sales, gym bundles, limited edition drops, wholesale partnerships.", costStructure: "Product design, prototyping, materials, manufacturing, athlete testing, D2C marketing.", keyMetrics: "Prototype test pass rate, pre-order conversion, repeat purchase intent, gym partner interest, WTP premium evidence.", unfairAdvantage: "REAL brand ownership, sustainable material intelligence, founder product development experience, sport-specific validation data.", mvpFormat: null, hypothesisTested: null, successCriteria: null, existingAlternatives: "Traditional synthetic protective equipment, established fight brands, low-cost imports, gym supplier relationships.", highLevelConcept: "Sustainable high-performance equipment for combat sports." },
  { id: 12, ventureId: "tone",        version: 1, status: "active",   overallStatus: "assumption_led", createdBy: null,                      createdAt: new Date("2026-06-08T08:54:57.681Z"), updatedAt: new Date("2026-06-08T08:54:57.681Z"), canvasTitle: "TONE Initial Canvas",    versionLabel: "Founder Assumption Canvas", changeSummary: null, reasonForChange: "new_canvas", evidenceTrigger: null, problem: "Creative operators face cost, storage, transport, and environmental pressure from conventional production equipment systems.", solution: "Modular equipment system, sustainable materials, rental/product hybrid, repair-extend service.", uniqueValueProp: "Modular sustainable creative equipment that reduces cost, storage burden, and environmental footprint.", customerSegments: "Creative production operators, film and TV production companies, event production teams, studios, sustainable production specialists.", channels: "Industry partnerships, production company pilots, sustainable production networks, rental platform distribution.", revenueStreams: "Equipment sales, rental/subscription model, repair and extend service, sustainability certification.", costStructure: "Equipment design, prototyping, sustainable materials, manufacturing, logistics, customer support.", keyMetrics: "Pilot customer retention, rental revenue per unit, WTP evidence level, production company partnerships, sustainability impact metrics.", unfairAdvantage: "TONE brand ownership, sustainable production network, modular design knowledge, circular economy operational model.", mvpFormat: null, hypothesisTested: null, successCriteria: null, existingAlternatives: "Conventional production equipment suppliers, rental companies, second-hand equipment markets, standard equipment hire.", highLevelConcept: "Modular sustainable equipment for creative production operators." },
];

const PRODUCT_MILESTONES = [
  { id: 2, ventureId: "real",        milestoneTitle: "ImpactShield Concierge MVP — Lab Validation",       milestoneType: "mvp_definition", mvpFormat: "concierge", stage: "build_prototype", status: "planned", assignedTo: "priya.okafor@real.group", userTestCount: 5, userResponseCaptured: false, participants: 5, validated: 0, invalidated: 0, leanCanvasVersionAtMvp: 2, linkedMvpDefinitionId: null, targetDate: null, completedDate: null, description: "REAL engineers will manually fabricate the first 5 prototype liners by hand, test them in ISO-accredited lab, and present results directly to OEM R&D and procurement contacts. No automated production line at this stage.", hypothesisTested: "If we present an OEM procurement director with independent ISO lab results showing ≥40% rotational impact absorption improvement AND a cost model at £32/unit at 10k volume, they will agree to a paid qualification trial of 500 units", successCriteria: "Minimum 2 signed paid qualification trial agreements (500 units each at ≥£28/unit) within 12 weeks of presenting lab results to OEM contacts. At least 1 must be a Tier 1 OEM (Riddell, Schutt, or equivalent). Trial must include OEM's own certification test protocol.", failureCriteria: "Zero qualification trials signed after presenting to 5+ qualified OEM procurement contacts. OR: lab results show <30% rotational improvement — below the minimum viable threshold for OEM interest.", createdAt: new Date("2026-06-06T13:35:35.663Z"), updatedAt: new Date("2026-06-06T13:35:35.663Z") },
  { id: 3, ventureId: "real",        milestoneTitle: "ImpactShield Prototype Build — 5 Hand-fabricated Liners", milestoneType: "concierge_mvp", mvpFormat: "concierge", stage: "build_prototype", status: "planned", assignedTo: "priya.okafor@real.group", userTestCount: 5, userResponseCaptured: false, participants: 5, validated: 0, invalidated: 0, leanCanvasVersionAtMvp: 2, linkedMvpDefinitionId: 2, targetDate: "2026-06-27", completedDate: null, description: "5 prototype liners hand-fabricated by REAL engineering team. TPU outer shell compression-moulded. Carbon honeycomb core cut to EN 960 liner geometry. Bio-resin matrix cured at 80C for 4 hours. Total build time: 3 days.", hypothesisTested: "Rugby and contact sport helmet OEMs need a reengineered composite liner that absorbs rotational impact forces 40% more efficiently than current EPS foam.", successCriteria: "Each prototype independently tested at SATRA Technology Centre, Kettering - ISO 17025 accredited lab. Min 40% rotational impact absorption improvement vs EN 960 baseline.", failureCriteria: null, createdAt: new Date("2026-06-06T13:36:17.190Z"), updatedAt: new Date("2026-06-06T13:36:17.190Z") },
  { id: 6, ventureId: "ECOCOMP-002", milestoneTitle: "Concierge MVP — Enzymatic Sorting Pilot",            milestoneType: "concierge_mvp", mvpFormat: "concierge", stage: null,             status: "completed", assignedTo: null,                         userTestCount: 0, userResponseCaptured: false, participants: 0, validated: 0, invalidated: 0, leanCanvasVersionAtMvp: null, linkedMvpDefinitionId: null, targetDate: "2026-06-06", completedDate: "2026-06-06", description: null, hypothesisTested: null, successCriteria: "At least 3 pilot customers validate sorting accuracy ≥ 85%", failureCriteria: "If < 2 pilot customers complete the trial, the concierge approach is not scalable", createdAt: new Date("2026-06-06T14:12:55.209Z"), updatedAt: new Date("2026-06-06T14:12:59.497Z") },
];

const EXPERIMENTS_DATA = [
  { id: 2, ventureId: "ECOCOMP-002", title: "E1 — Enzymatic Sorting Accuracy",   hypothesis: "Enzymatic sorting achieves ≥85% accuracy on food-waste feedstock",            method: "Pilot batch with 3 customers, 10 samples each",       result: "87% accuracy achieved across all 3 customers",                                   outcome: "validated",    confidenceLevel: 8, evidenceUri: "https://lab.ecocomp.io/results/e1-sorting.pdf",   conductedAt: null, createdAt: new Date("2026-06-06T14:13:46.455Z") },
  { id: 3, ventureId: "ECOCOMP-002", title: "E2 — Customer Willingness to Pay",  hypothesis: "Mid-size food manufacturers will pay ≥$120/tonne for BioForm service",         method: "Telephone survey of 12 procurement managers",          result: "9 of 12 confirmed budget approval at $150/tonne",                                outcome: "validated",    confidenceLevel: 7, evidenceUri: null,                                                conductedAt: null, createdAt: new Date("2026-06-06T14:13:50.768Z") },
  { id: 4, ventureId: "ECOCOMP-002", title: "E3 — Per-Seat Pricing Rejection",   hypothesis: "Per-seat SaaS licence is the preferred pricing model for processors",          method: "A/B interview study with 8 procurement leads",         result: "Only 1 of 8 preferred per-seat; 7 preferred per-tonne variable pricing",        outcome: "invalidated",  confidenceLevel: 9, evidenceUri: "https://lab.ecocomp.io/results/e3-pricing.pdf",   conductedAt: null, createdAt: new Date("2026-06-06T14:13:56.425Z") },
  { id: 5, ventureId: "ECOCOMP-002", title: "E4 — Scale-up Processing Speed",    hypothesis: "BioForm process can handle 500kg/hour in commercial setting",                  method: "Controlled lab simulation at 60% of commercial load",  result: "Achieved 310kg/hr — insufficient data to confirm 500kg/hr target",             outcome: "inconclusive", confidenceLevel: 6, evidenceUri: null,                                                conductedAt: null, createdAt: new Date("2026-06-06T14:14:09.279Z") },
  { id: 6, ventureId: "ECOCOMP-002", title: "E5 — Per-Tonne Pricing Acceptance", hypothesis: "Per-tonne variable pricing is preferred by ≥70% of processors",               method: "Structured pricing interview — 15 prospects",          result: "12 of 15 (80%) confirmed preference for per-tonne model",                      outcome: "validated",    confidenceLevel: 8, evidenceUri: "https://lab.ecocomp.io/results/e5-pricing.pdf",   conductedAt: null, createdAt: new Date("2026-06-06T14:18:21.385Z") },
  { id: 7, ventureId: "ECOCOMP-002", title: "E6 — Outcome Guarantee Adoption",   hypothesis: "Outcome guarantee increases close rate by ≥20%",                              method: "A/B offer test with 10 qualified prospects",           result: "Guarantee group: 7/10 closed vs control 5/10 — +40% lift",                    outcome: "validated",    confidenceLevel: 7, evidenceUri: "https://lab.ecocomp.io/results/e6-guarantee.pdf", conductedAt: null, createdAt: new Date("2026-06-06T14:18:21.390Z") },
];

// ─── Main export ──────────────────────────────────────────────────────────────

export async function seedProductionIfEmpty(): Promise<void> {
  try {
    const db = await getDb();
    if (!db) return;

    const countRows = await db.execute(sql`SELECT COUNT(*) AS cnt FROM ventures`);
    const cnt = Number((countRows.rows ?? countRows)[0]?.cnt ?? 0);
    if (cnt > 0) {
      console.log("[seed] Ventures already present — skipping.");
      return;
    }

    console.log("[seed] Seeding production venture data...");

    // 1. ventures
    for (const v of VENTURES) {
      await db.execute(sql`
        INSERT INTO ventures (id, name, tagline, sector, channel, status, vrl, "vrlPercent", trl, "trlPercent",
          color, "investmentReady", "isInternalLab", "lifecycleStage", "strategicClassification",
          "productMarketFitSignal", "currentStage", "validationStatus", "ventureType", owner,
          "workflowStage", "pivotRequired", "canvasVersion", "createdAt", "updatedAt")
        VALUES (${v.id}, ${v.name}, ${v.tagline ?? null}, ${v.sector ?? null}, ${v.channel},
          ${v.status}, ${v.vrl}, ${v.vrlPercent}, ${v.trl}, ${v.trlPercent},
          ${v.color}, ${v.investmentReady}, ${v.isInternalLab}, ${v.lifecycleStage},
          ${v.strategicClassification}, ${v.productMarketFitSignal},
          ${v.currentStage ?? null}, ${v.validationStatus ?? null}, ${v.ventureType ?? null},
          ${v.owner ?? null}, ${v.workflowStage ?? null}, ${v.pivotRequired},
          ${v.canvasVersion}, ${v.createdAt}, ${v.updatedAt})
        ON CONFLICT (id) DO NOTHING
      `);
    }
    console.log(`  ✓ ventures (${VENTURES.length})`);

    // 2. cc_hypotheses
    for (const h of CC_HYPOTHESES) {
      await db.execute(sql`
        INSERT INTO cc_hypotheses (id, "ventureId", "moduleSource", "hypothesisType", "hypothesisStatement",
          "assumptionRiskLevel", status, "confidenceScore", "evidenceSummary", "createdAt", "updatedAt")
        VALUES (${h.id}, ${h.ventureId}, ${h.moduleSource}, ${h.hypothesisType},
          ${h.hypothesisStatement}, ${h.assumptionRiskLevel}, ${h.status},
          ${h.confidenceScore}, ${h.evidenceSummary ?? null}, NOW(), NOW())
        ON CONFLICT (id) DO NOTHING
      `);
    }
    await db.execute(sql`SELECT setval('cc_hypotheses_id_seq', (SELECT MAX(id) FROM cc_hypotheses))`);
    console.log(`  ✓ cc_hypotheses (${CC_HYPOTHESES.length})`);

    // 3. cc_experiments
    for (const e of CC_EXPERIMENTS) {
      await db.execute(sql`
        INSERT INTO cc_experiments (id, "ventureId", "hypothesisId", "experimentName", "experimentType",
          "moduleSource", "experimentStatus", method, "successThreshold", "startDate", "dueDate",
          result, "learningSummary", "decisionRecommendation", "createdAt", "updatedAt")
        VALUES (${e.id}, ${e.ventureId}, ${e.hypothesisId}, ${e.experimentName},
          ${e.experimentType}, ${e.moduleSource}, ${e.experimentStatus},
          ${e.method}, ${e.successThreshold}, ${e.startDate}, ${e.dueDate},
          ${e.result ?? null}, ${e.learningSummary ?? null}, ${e.decisionRecommendation ?? null},
          NOW(), NOW())
        ON CONFLICT (id) DO NOTHING
      `);
    }
    await db.execute(sql`SELECT setval('cc_experiments_id_seq', (SELECT MAX(id) FROM cc_experiments))`);
    console.log(`  ✓ cc_experiments (${CC_EXPERIMENTS.length})`);

    // 4. cc_stage_gate_reviews
    for (const r of CC_STAGE_GATE_REVIEWS) {
      await db.execute(sql`
        INSERT INTO cc_stage_gate_reviews (id, "ventureId", "fromStage", "toStage", "reviewStatus",
          "evidenceScore", "marketScore", "commercialScore", "technicalScore", "operationalScore",
          "riskScore", "investmentReadinessScore", "reviewerNotes", "approvalDecision",
          "requiredActions", "reviewDate", "nextReviewDate", "humanReviewRequired",
          "humanReviewedBy", "humanReviewedAt", "gateType", "createdAt", "updatedAt")
        VALUES (${r.id}, ${r.ventureId}, ${r.fromStage ?? null}, ${r.toStage ?? null},
          ${r.reviewStatus}, ${r.evidenceScore}, ${r.marketScore}, ${r.commercialScore},
          ${r.technicalScore}, ${r.operationalScore}, ${r.riskScore}, ${r.investmentReadinessScore},
          ${r.reviewerNotes ?? null}, ${r.approvalDecision ?? null}, ${r.requiredActions ?? null},
          ${r.reviewDate ?? null}, ${r.nextReviewDate ?? null}, ${r.humanReviewRequired},
          ${r.humanReviewedBy ?? null}, ${r.humanReviewedAt ?? null}, ${r.gateType ?? null},
          NOW(), NOW())
        ON CONFLICT (id) DO NOTHING
      `);
    }
    await db.execute(sql`SELECT setval('cc_stage_gate_reviews_id_seq', (SELECT MAX(id) FROM cc_stage_gate_reviews))`);
    console.log(`  ✓ cc_stage_gate_reviews (${CC_STAGE_GATE_REVIEWS.length})`);

    // 5. cc_evidence
    for (const e of CC_EVIDENCE) {
      await db.execute(sql`
        INSERT INTO cc_evidence (id, "ventureId", "hypothesisId", "experimentId", "moduleSource",
          "evidenceType", "evidenceTitle", "evidenceSummary", "evidenceStrengthScore",
          "evidenceRelevanceScore", "evidenceRecencyScore", "evidenceConfidenceScore",
          "contradictsHypothesis", "sourceReference", "createdAt", "updatedAt")
        VALUES (${e.id}, ${e.ventureId}, ${e.hypothesisId}, ${e.experimentId ?? null},
          ${e.moduleSource}, ${e.evidenceType}, ${e.evidenceTitle}, ${e.evidenceSummary},
          ${e.evidenceStrengthScore}, ${e.evidenceRelevanceScore}, ${e.evidenceRecencyScore},
          ${e.evidenceConfidenceScore}, ${e.contradictsHypothesis}, ${e.sourceReference},
          NOW(), NOW())
        ON CONFLICT (id) DO NOTHING
      `);
    }
    await db.execute(sql`SELECT setval('cc_evidence_id_seq', (SELECT MAX(id) FROM cc_evidence))`);
    console.log(`  ✓ cc_evidence (${CC_EVIDENCE.length})`);

    // 6. cc_decisions
    for (const d of CC_DECISIONS) {
      await db.execute(sql`
        INSERT INTO cc_decisions (id, "ventureId", "decisionType", "decisionTitle", "decisionSummary",
          "evidenceConfidenceScore", "riskScore", "recommendedAction", "decisionStatus",
          "reviewerNotes", "approvedBy", "decisionDate", "nextReviewDate", "createdAt", "updatedAt")
        VALUES (${d.id}, ${d.ventureId}, ${d.decisionType}, ${d.decisionTitle},
          ${d.decisionSummary ?? null}, ${d.evidenceConfidenceScore}, ${d.riskScore},
          ${d.recommendedAction}, ${d.decisionStatus}, ${d.reviewerNotes ?? null},
          ${d.approvedBy ?? null}, ${d.decisionDate ?? null}, ${d.nextReviewDate ?? null},
          NOW(), NOW())
        ON CONFLICT (id) DO NOTHING
      `);
    }
    await db.execute(sql`SELECT setval('cc_decisions_id_seq', (SELECT MAX(id) FROM cc_decisions))`);
    console.log(`  ✓ cc_decisions (${CC_DECISIONS.length})`);

    // 7. cc_pivot_logs
    for (const p of CC_PIVOT_LOGS) {
      await db.execute(sql`
        INSERT INTO cc_pivot_logs (id, "ventureId", "previousHypothesis", "newHypothesis",
          "pivotType", "reasonForPivot", "evidenceTrigger", "decisionId", "hypothesisId",
          "dateLogged", "createdAt", "updatedAt")
        VALUES (${p.id}, ${p.ventureId}, ${p.previousHypothesis}, ${p.newHypothesis},
          ${p.pivotType}, ${p.reasonForPivot}, ${p.evidenceTrigger},
          ${p.decisionId}, ${p.hypothesisId}, ${p.dateLogged}, NOW(), NOW())
        ON CONFLICT (id) DO NOTHING
      `);
    }
    await db.execute(sql`SELECT setval('cc_pivot_logs_id_seq', (SELECT MAX(id) FROM cc_pivot_logs))`);
    console.log(`  ✓ cc_pivot_logs (${CC_PIVOT_LOGS.length})`);

    // 8. lean_canvases
    for (const c of LEAN_CANVASES) {
      await db.execute(sql`
        INSERT INTO lean_canvases (id, "ventureId", version, problem, solution, "uniqueValueProp",
          "customerSegments", channels, "revenueStreams", "costStructure", "keyMetrics",
          "unfairAdvantage", "existingAlternatives", "highLevelConcept", "mvpFormat",
          "hypothesisTested", "successCriteria", status, "canvasTitle", "overallStatus",
          "versionLabel", "changeSummary", "reasonForChange", "evidenceTrigger",
          "createdBy", "createdAt", "updatedAt")
        VALUES (${c.id}, ${c.ventureId}, ${c.version}, ${c.problem ?? null}, ${c.solution ?? null},
          ${c.uniqueValueProp ?? null}, ${c.customerSegments ?? null}, ${c.channels ?? null},
          ${c.revenueStreams ?? null}, ${c.costStructure ?? null}, ${c.keyMetrics ?? null},
          ${c.unfairAdvantage ?? null}, ${c.existingAlternatives ?? null}, ${c.highLevelConcept ?? null},
          ${c.mvpFormat ?? null}, ${c.hypothesisTested ?? null}, ${c.successCriteria ?? null},
          ${c.status}, ${c.canvasTitle ?? null}, ${c.overallStatus},
          ${c.versionLabel ?? null}, ${c.changeSummary ?? null}, ${c.reasonForChange ?? null},
          ${c.evidenceTrigger ?? null}, ${c.createdBy ?? null}, ${c.createdAt}, ${c.updatedAt})
        ON CONFLICT (id) DO NOTHING
      `);
    }
    await db.execute(sql`SELECT setval('lean_canvases_id_seq', (SELECT MAX(id) FROM lean_canvases))`);
    console.log(`  ✓ lean_canvases (${LEAN_CANVASES.length})`);

    // 9. product_milestones
    for (const m of PRODUCT_MILESTONES) {
      await db.execute(sql`
        INSERT INTO product_milestones (id, "ventureId", "milestoneTitle", "milestoneType", "mvpFormat",
          stage, description, "hypothesisTested", "successCriteria", "failureCriteria",
          "userTestCount", "userResponseCaptured", participants, validated, invalidated,
          "targetDate", "completedDate", status, "assignedTo",
          "leanCanvasVersionAtMvp", "linkedMvpDefinitionId", "createdAt", "updatedAt")
        VALUES (${m.id}, ${m.ventureId}, ${m.milestoneTitle}, ${m.milestoneType}, ${m.mvpFormat ?? null},
          ${m.stage ?? null}, ${m.description ?? null}, ${m.hypothesisTested ?? null},
          ${m.successCriteria ?? null}, ${m.failureCriteria ?? null},
          ${m.userTestCount}, ${m.userResponseCaptured}, ${m.participants}, ${m.validated}, ${m.invalidated},
          ${m.targetDate ?? null}, ${m.completedDate ?? null}, ${m.status}, ${m.assignedTo ?? null},
          ${m.leanCanvasVersionAtMvp ?? null}, ${m.linkedMvpDefinitionId ?? null},
          ${m.createdAt}, ${m.updatedAt})
        ON CONFLICT (id) DO NOTHING
      `);
    }
    await db.execute(sql`SELECT setval('product_milestones_id_seq', (SELECT MAX(id) FROM product_milestones))`);
    console.log(`  ✓ product_milestones (${PRODUCT_MILESTONES.length})`);

    // 10. experiments
    for (const e of EXPERIMENTS_DATA) {
      await db.execute(sql`
        INSERT INTO experiments (id, "ventureId", title, hypothesis, method, result, outcome,
          "confidenceLevel", "evidenceUri", "conductedAt", "createdAt", "updatedAt")
        VALUES (${e.id}, ${e.ventureId}, ${e.title}, ${e.hypothesis}, ${e.method},
          ${e.result ?? null}, ${e.outcome ?? null}, ${e.confidenceLevel ?? null},
          ${e.evidenceUri ?? null}, ${e.conductedAt ?? null}, ${e.createdAt}, ${e.createdAt})
        ON CONFLICT (id) DO NOTHING
      `);
    }
    await db.execute(sql`SELECT setval('experiments_id_seq', (SELECT MAX(id) FROM experiments))`);
    console.log(`  ✓ experiments (${EXPERIMENTS_DATA.length})`);

    console.log("[seed] ✓ All venture data seeded successfully.");
  } catch (err) {
    console.error("[seed] Error during venture seed:", (err as Error).message);
  }
}
