/**
 * Module C (Discovery & Market) — WTP Assessment
 * Structured Lean Startup commercial-validation engine. Tests real buying
 * commitment (money, budget, procurement, LOIs, paid pilots), not enthusiasm.
 *
 * Reuses the extended `wtp_tests` table plus four dedicated tables
 * (wtp_commitments, pricing_experiments, budget_validations,
 * procurement_pathways). Pure scoring lives in shared/wtp.ts.
 *
 * Writes auto-feed market_risks (linkedModule "wtp") and cc_alerts
 * (linkedModule "wtp"), both idempotent by record.
 *
 * Auth model matches the sibling Discovery & Market router: reads stay public
 * (anyone may view evidence) but every create/update/delete is venture-scoped
 * via `ventureProcedure` (authenticated + `assertVentureAccess`), preventing
 * unauthenticated or cross-venture mutation of portfolio data.
 */
import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { router, publicProcedure, protectedProcedure } from "./_core/trpc";
import { assertVentureAccess } from "./discoveryMarket.router";
import { getDb } from "./db";
import { and, eq, desc } from "drizzle-orm";
import {
  ventures,
  wtpTests,
  marketRisks,
  ccAlerts,
  wtpCommitments,
  pricingExperiments,
  budgetValidations,
  procurementPathways,
} from "../drizzle/schema";
import { calculateMarketRiskScore } from "@shared/discoveryMarket";
import {
  calculateWTPScore,
  calculateEvidenceLevelScore,
  interpretWTPScore,
  calculateVentureWTPStatus,
  ventureWTPStatusBand,
  generateWTPDecisionRecommendation,
  generateWTPWarnings,
  wtpMarketRiskSpecs,
  wtpCommandAlertSpecs,
  calculatePricingConversionRate,
  calculateProcurementFrictionScore,
  wtpStageGateChecklist,
  wtpStageGateReady,
  budgetOwnerScore,
  procurementPathwayScore,
  pricingResponseScore,
  WTP_EVIDENCE_LADDER,
  WTP_TEST_STATUSES,
  WTP_PRICING_MODELS,
  WTP_TEST_METHODS,
  WTP_OBJECTION_CATEGORIES,
  BUDGET_OWNER_STATUSES,
  PRICING_RESPONSES,
  COMMITMENT_TYPES,
  COMMITMENT_STATUSES,
  PRICING_EXPERIMENT_STATUSES,
  BUDGET_VALIDATION_STATUSES,
  BUDGET_CATEGORIES,
  PROCUREMENT_ROUTES,
  PROCUREMENT_STATUSES,
  avg,
  type WtpRiskSpec,
} from "@shared/wtp";

function db() {
  return getDb().then((d) => {
    if (!d) throw new Error("DB unavailable");
    return d;
  });
}

type Db = Awaited<ReturnType<typeof db>>;

// Authenticated procedure that verifies the caller is authorised for the target
// venture (from the input's `ventureId`) before any write runs. Mirrors the
// Discovery & Market router's seam so WTP writes cannot be made by
// unauthenticated callers or across ventures (cross-venture IDOR).
const ventureProcedure = protectedProcedure.use(async ({ ctx, next, getRawInput }) => {
  const raw = await getRawInput();
  const ventureId = (raw as { ventureId?: unknown } | null)?.ventureId;
  if (typeof ventureId !== "string" || ventureId.length === 0) {
    throw new TRPCError({ code: "BAD_REQUEST", message: "ventureId is required" });
  }
  await assertVentureAccess(await db(), ctx.user, ventureId, { allowClaim: true });
  return next();
});

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

// ─── Auto-risk sync (market_risks, linkedModule "wtp", scoped per test) ─────────
async function syncWtpRisks(
  d: Db,
  ventureId: string,
  wtpTestId: number,
  specs: WtpRiskSpec[],
) {
  const existing = await d
    .select()
    .from(marketRisks)
    .where(
      and(
        eq(marketRisks.ventureId, ventureId),
        eq(marketRisks.linkedModule, "wtp"),
        eq(marketRisks.linkedRecordId, wtpTestId),
      ),
    );
  const autoExisting = existing.filter((e) => e.autoGenerated);
  const wantedTitles = new Set(specs.map((s) => s.riskTitle));

  // Remove stale auto-risks that no longer apply.
  for (const e of autoExisting) {
    if (!wantedTitles.has(e.riskTitle)) {
      await d.delete(marketRisks).where(eq(marketRisks.id, e.id));
    }
  }

  for (const spec of specs) {
    const match = autoExisting.find((e) => e.riskTitle === spec.riskTitle);
    const marketRiskScore = calculateMarketRiskScore(spec);
    if (match) {
      await d
        .update(marketRisks)
        .set({
          riskCategory: spec.riskCategory,
          probabilityScore: spec.probabilityScore,
          severityScore: spec.severityScore,
          evidenceConfidenceScore: spec.evidenceConfidenceScore,
          requiredExperiment: spec.requiredExperiment,
          marketRiskScore,
          updatedAt: new Date(),
        })
        .where(eq(marketRisks.id, match.id));
    } else {
      await d.insert(marketRisks).values({
        ventureId,
        linkedModule: "wtp",
        linkedRecordId: wtpTestId,
        riskTitle: spec.riskTitle,
        riskCategory: spec.riskCategory,
        riskDescription: "Auto-generated from WTP assessment.",
        probabilityScore: spec.probabilityScore,
        severityScore: spec.severityScore,
        evidenceConfidenceScore: spec.evidenceConfidenceScore,
        marketRiskScore,
        requiredExperiment: spec.requiredExperiment,
        status: "open",
        autoGenerated: true,
      });
    }
  }
}

// ─── Auto-alert sync (cc_alerts, linkedModule "wtp", scoped per test) ───────────
async function syncWtpAlerts(
  d: Db,
  ventureId: string,
  wtpTestId: number,
  ventureStage: string | null | undefined,
  test: typeof wtpTests.$inferSelect,
) {
  const wtpScore = test.wtpScore ?? 0;
  const wanted = wtpCommandAlertSpecs({
    ventureId,
    wtpTestId,
    wtpScore,
    ventureStage,
    testStatus: test.status,
    evidenceLevel: test.evidenceLevel ?? 1,
    nextCommercialAction: test.nextCommercialAction,
    nextActionDueDate: test.nextActionDueDate,
    today: today(),
  });

  const existing = await d
    .select()
    .from(ccAlerts)
    .where(
      and(
        eq(ccAlerts.ventureId, ventureId),
        eq(ccAlerts.linkedModule, "wtp"),
        eq(ccAlerts.linkedRecordId, wtpTestId),
        eq(ccAlerts.autoGenerated, true),
      ),
    );
  const existingByKey = new Map(existing.map((a) => [a.dedupeKey ?? "", a]));
  const wantedKeys = new Set(wanted.map((w) => w.dedupeKey));

  for (const w of wanted) {
    const prev = existingByKey.get(w.dedupeKey);
    if (prev) {
      await d
        .update(ccAlerts)
        .set({
          alertTitle: w.alertTitle,
          alertDescription: w.alertDescription,
          severity: w.severity,
          recommendedAction: w.recommendedAction,
          alertType: w.alertType,
          updatedAt: new Date(),
        })
        .where(eq(ccAlerts.id, prev.id));
    } else {
      await d.insert(ccAlerts).values({
        ventureId,
        alertType: w.alertType,
        alertTitle: w.alertTitle,
        alertDescription: w.alertDescription,
        severity: w.severity,
        linkedModule: "wtp",
        linkedRecordId: wtpTestId,
        recommendedAction: w.recommendedAction,
        status: "open",
        autoGenerated: true,
        dedupeKey: w.dedupeKey,
      });
    }
  }

  const stale = existing.filter(
    (a) => !wantedKeys.has(a.dedupeKey ?? "") && a.status === "open",
  );
  for (const s of stale) {
    await d
      .update(ccAlerts)
      .set({ status: "resolved", updatedAt: new Date() })
      .where(eq(ccAlerts.id, s.id));
  }
}

// ─── Input schemas ──────────────────────────────────────────────────────────────
const ventureInput = z.object({ ventureId: z.string() });
const recordInput = z.object({ ventureId: z.string(), id: z.number() });

const wtpTestInput = z.object({
  id: z.number().optional(),
  ventureId: z.string(),
  problemHypothesisId: z.number().nullable().optional(),
  customerSegmentId: z.number().nullable().optional(),
  customerName: z.string().optional(),
  organisation: z.string().optional(),
  contactRole: z.string().optional(),
  buyerRole: z.string().optional(),
  economicBuyer: z.boolean().optional(),
  budgetOwnerConfirmed: z.boolean().optional(),
  budgetOwnerStatus: z.enum(BUDGET_OWNER_STATUSES).optional(),
  budgetOwnerName: z.string().optional(),
  budgetOwnerRole: z.string().optional(),
  currentSpend: z.string().optional(),
  currentSpendCurrency: z.string().optional(),
  currentSpendPeriod: z.string().optional(),
  valueDriver: z.string().optional(),
  pricingModelTested: z.string().optional(),
  priceTested: z.string().optional(),
  priceCurrency: z.string().optional(),
  pricePeriod: z.string().optional(),
  testMethod: z.enum(WTP_TEST_METHODS).optional(),
  responseSummary: z.string().optional(),
  evidenceLevel: z.number().min(1).max(7).optional(),
  pricingResponse: z.enum(PRICING_RESPONSES).optional(),
  procurementPathway: z.string().optional(),
  procurementPathwayStatus: z.enum(PROCUREMENT_STATUSES).optional(),
  procurementPathwayNotes: z.string().optional(),
  decisionProcessNotes: z.string().optional(),
  objections: z.string().optional(),
  objectionCategory: z.enum(WTP_OBJECTION_CATEGORIES).optional(),
  recommendedPricingModel: z.string().optional(),
  nextCommercialAction: z.string().optional(),
  nextActionDueDate: z.string().optional(),
  status: z.enum(WTP_TEST_STATUSES).optional(),
});

// ─── Router ──────────────────────────────────────────────────────────────────────
export const wtpRouter = router({
  // ── Reference data ─────────────────────────────────────────────────────────
  evidenceLadder: publicProcedure.query(() => WTP_EVIDENCE_LADDER),
  options: publicProcedure.query(() => ({
    testStatuses: WTP_TEST_STATUSES,
    pricingModels: WTP_PRICING_MODELS,
    testMethods: WTP_TEST_METHODS,
    objectionCategories: WTP_OBJECTION_CATEGORIES,
    budgetOwnerStatuses: BUDGET_OWNER_STATUSES,
    pricingResponses: PRICING_RESPONSES,
    commitmentTypes: COMMITMENT_TYPES,
    commitmentStatuses: COMMITMENT_STATUSES,
    pricingExperimentStatuses: PRICING_EXPERIMENT_STATUSES,
    budgetValidationStatuses: BUDGET_VALIDATION_STATUSES,
    budgetCategories: BUDGET_CATEGORIES,
    procurementRoutes: PROCUREMENT_ROUTES,
    procurementStatuses: PROCUREMENT_STATUSES,
  })),

  // ── WTP Tests (core commercial-validation record) ────────────────────────────
  tests: router({
    list: publicProcedure
      .input(
        z.object({
          ventureId: z.string(),
          problemHypothesisId: z.number().optional(),
        }),
      )
      .query(async ({ input }) => {
        const d = await db();
        const rows = await d
          .select()
          .from(wtpTests)
          .where(eq(wtpTests.ventureId, input.ventureId))
          .orderBy(desc(wtpTests.createdAt));
        return input.problemHypothesisId
          ? rows.filter((r) => r.problemHypothesisId === input.problemHypothesisId)
          : rows;
      }),
    upsert: ventureProcedure.input(wtpTestInput).mutation(async ({ input }) => {
      const d = await db();
      const { id, ...vals } = input;
      const evidenceLevel = vals.evidenceLevel ?? 1;
      const wtpScore = calculateWTPScore({
        evidenceLevel,
        budgetOwnerStatus: vals.budgetOwnerStatus,
        budgetOwnerConfirmed: vals.budgetOwnerConfirmed ?? false,
        procurementPathwayStatus: vals.procurementPathwayStatus,
        pricingResponse: vals.pricingResponse,
      });
      const evidenceStrengthScore = calculateEvidenceLevelScore(evidenceLevel);

      let recordId: number;
      let row: typeof wtpTests.$inferSelect;
      if (id) {
        const [updated] = await d
          .update(wtpTests)
          .set({ ...vals, wtpScore, evidenceStrengthScore, updatedAt: new Date() })
          .where(and(eq(wtpTests.id, id), eq(wtpTests.ventureId, input.ventureId)))
          .returning();
        if (!updated) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
        recordId = id;
        row = updated;
      } else {
        const [inserted] = await d
          .insert(wtpTests)
          .values({ ...vals, wtpScore, evidenceStrengthScore })
          .returning();
        recordId = inserted.id;
        row = inserted;
      }

      // Auto-feed market_risks + cc_alerts.
      await syncWtpRisks(
        d,
        input.ventureId,
        recordId,
        wtpMarketRiskSpecs({
          wtpScore,
          evidenceLevel,
          budgetOwnerStatus: vals.budgetOwnerStatus,
          budgetOwnerConfirmed: vals.budgetOwnerConfirmed ?? false,
          procurementPathwayStatus: vals.procurementPathwayStatus,
          objectionCategory: vals.objectionCategory,
        }),
      );
      const [venture] = await d
        .select()
        .from(ventures)
        .where(eq(ventures.id, input.ventureId));
      await syncWtpAlerts(d, input.ventureId, recordId, venture?.currentStage, row);

      return { id: recordId, wtpScore, evidenceStrengthScore };
    }),
    delete: ventureProcedure.input(recordInput).mutation(async ({ input }) => {
      const d = await db();
      const [row] = await d
        .delete(wtpTests)
        .where(and(eq(wtpTests.id, input.id), eq(wtpTests.ventureId, input.ventureId)))
        .returning({ id: wtpTests.id });
      if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
      await d
        .delete(marketRisks)
        .where(
          and(
            eq(marketRisks.ventureId, input.ventureId),
            eq(marketRisks.linkedModule, "wtp"),
            eq(marketRisks.linkedRecordId, input.id),
            eq(marketRisks.autoGenerated, true),
          ),
        );
      await d
        .delete(ccAlerts)
        .where(
          and(
            eq(ccAlerts.ventureId, input.ventureId),
            eq(ccAlerts.linkedModule, "wtp"),
            eq(ccAlerts.linkedRecordId, input.id),
            eq(ccAlerts.autoGenerated, true),
          ),
        );
      return { success: true };
    }),
  }),

  // ── Customer Commitment Log ──────────────────────────────────────────────────
  commitments: router({
    list: publicProcedure.input(ventureInput).query(async ({ input }) => {
      const d = await db();
      return d
        .select()
        .from(wtpCommitments)
        .where(eq(wtpCommitments.ventureId, input.ventureId))
        .orderBy(desc(wtpCommitments.createdAt));
    }),
    upsert: ventureProcedure
      .input(
        z.object({
          id: z.number().optional(),
          ventureId: z.string(),
          wtpTestId: z.number().nullable().optional(),
          commitmentType: z.enum(COMMITMENT_TYPES).optional(),
          commitmentDescription: z.string().optional(),
          commitmentValue: z.string().optional(),
          commitmentCurrency: z.string().optional(),
          commitmentDate: z.string().optional(),
          evidenceReference: z.string().optional(),
          status: z.enum(COMMITMENT_STATUSES).optional(),
        }),
      )
      .mutation(async ({ input }) => {
        const d = await db();
        const { id, ...vals } = input;
        if (id) {
          const [updated] = await d
            .update(wtpCommitments)
            .set({ ...vals, updatedAt: new Date() })
            .where(and(eq(wtpCommitments.id, id), eq(wtpCommitments.ventureId, input.ventureId)))
            .returning({ id: wtpCommitments.id });
          if (!updated) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
          return { id };
        }
        const [row] = await d.insert(wtpCommitments).values(vals).returning({ id: wtpCommitments.id });
        return { id: row.id };
      }),
    delete: ventureProcedure.input(recordInput).mutation(async ({ input }) => {
      const d = await db();
      const [row] = await d
        .delete(wtpCommitments)
        .where(and(eq(wtpCommitments.id, input.id), eq(wtpCommitments.ventureId, input.ventureId)))
        .returning({ id: wtpCommitments.id });
      if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
      return { success: true };
    }),
  }),

  // ── Pricing Experiments ──────────────────────────────────────────────────────
  pricingExperiments: router({
    list: publicProcedure.input(ventureInput).query(async ({ input }) => {
      const d = await db();
      return d
        .select()
        .from(pricingExperiments)
        .where(eq(pricingExperiments.ventureId, input.ventureId))
        .orderBy(desc(pricingExperiments.createdAt));
    }),
    upsert: ventureProcedure
      .input(
        z.object({
          id: z.number().optional(),
          ventureId: z.string(),
          hypothesisId: z.number().nullable().optional(),
          pricingModel: z.enum(WTP_PRICING_MODELS).optional(),
          pricePoint: z.string().optional(),
          currency: z.string().optional(),
          billingPeriod: z.string().optional(),
          targetCustomerSegment: z.string().optional(),
          valueMetric: z.string().optional(),
          testMethod: z.enum(WTP_TEST_METHODS).optional(),
          testSampleSize: z.number().optional(),
          positiveResponses: z.number().optional(),
          negativeResponses: z.number().optional(),
          learningSummary: z.string().optional(),
          recommendedPriceRange: z.string().optional(),
          recommendedNextTest: z.string().optional(),
          status: z.enum(PRICING_EXPERIMENT_STATUSES).optional(),
        }),
      )
      .mutation(async ({ input }) => {
        const d = await db();
        const { id, ...vals } = input;
        const conversionRate = calculatePricingConversionRate(
          vals.positiveResponses ?? 0,
          vals.negativeResponses ?? 0,
          vals.testSampleSize,
        );
        if (id) {
          const [updated] = await d
            .update(pricingExperiments)
            .set({ ...vals, conversionRate, updatedAt: new Date() })
            .where(and(eq(pricingExperiments.id, id), eq(pricingExperiments.ventureId, input.ventureId)))
            .returning({ id: pricingExperiments.id });
          if (!updated) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
          return { id, conversionRate };
        }
        const [row] = await d
          .insert(pricingExperiments)
          .values({ ...vals, conversionRate })
          .returning({ id: pricingExperiments.id });
        return { id: row.id, conversionRate };
      }),
    delete: ventureProcedure.input(recordInput).mutation(async ({ input }) => {
      const d = await db();
      const [row] = await d
        .delete(pricingExperiments)
        .where(and(eq(pricingExperiments.id, input.id), eq(pricingExperiments.ventureId, input.ventureId)))
        .returning({ id: pricingExperiments.id });
      if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
      return { success: true };
    }),
  }),

  // ── Budget Owner Validation ──────────────────────────────────────────────────
  budgetValidations: router({
    list: publicProcedure.input(ventureInput).query(async ({ input }) => {
      const d = await db();
      return d
        .select()
        .from(budgetValidations)
        .where(eq(budgetValidations.ventureId, input.ventureId))
        .orderBy(desc(budgetValidations.createdAt));
    }),
    upsert: ventureProcedure
      .input(
        z.object({
          id: z.number().optional(),
          ventureId: z.string(),
          wtpTestId: z.number().nullable().optional(),
          organisation: z.string().optional(),
          budgetOwnerKnown: z.boolean().optional(),
          budgetOwnerRole: z.string().optional(),
          budgetCategory: z.string().optional(),
          budgetCycle: z.string().optional(),
          currentBudgetAvailable: z.string().optional(),
          estimatedBudgetRange: z.string().optional(),
          approvalRequired: z.boolean().optional(),
          approvalStakeholders: z.string().optional(),
          financialDecisionCriteria: z.string().optional(),
          notes: z.string().optional(),
          validationStatus: z.enum(BUDGET_VALIDATION_STATUSES).optional(),
        }),
      )
      .mutation(async ({ input }) => {
        const d = await db();
        const { id, ...vals } = input;
        if (id) {
          const [updated] = await d
            .update(budgetValidations)
            .set({ ...vals, updatedAt: new Date() })
            .where(and(eq(budgetValidations.id, id), eq(budgetValidations.ventureId, input.ventureId)))
            .returning({ id: budgetValidations.id });
          if (!updated) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
          return { id };
        }
        const [row] = await d.insert(budgetValidations).values(vals).returning({ id: budgetValidations.id });
        return { id: row.id };
      }),
    delete: ventureProcedure.input(recordInput).mutation(async ({ input }) => {
      const d = await db();
      const [row] = await d
        .delete(budgetValidations)
        .where(and(eq(budgetValidations.id, input.id), eq(budgetValidations.ventureId, input.ventureId)))
        .returning({ id: budgetValidations.id });
      if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
      return { success: true };
    }),
  }),

  // ── Procurement Pathways ─────────────────────────────────────────────────────
  procurementPathways: router({
    list: publicProcedure.input(ventureInput).query(async ({ input }) => {
      const d = await db();
      const rows = await d
        .select()
        .from(procurementPathways)
        .where(eq(procurementPathways.ventureId, input.ventureId))
        .orderBy(desc(procurementPathways.createdAt));
      return rows.map((r) => ({
        ...r,
        frictionScore: calculateProcurementFrictionScore({
          complexityScore: r.procurementComplexityScore ?? 1,
          expectedSalesCycleDays: r.expectedSalesCycleDays ?? 0,
          legalReviewRequired: r.legalReviewRequired ?? false,
          dataSecurityReviewRequired: r.dataSecurityReviewRequired ?? false,
          pilotPossibleWithoutFullProcurement: r.pilotPossibleWithoutFullProcurement ?? false,
          route: r.procurementRoute,
        }),
      }));
    }),
    upsert: ventureProcedure
      .input(
        z.object({
          id: z.number().optional(),
          ventureId: z.string(),
          wtpTestId: z.number().nullable().optional(),
          organisation: z.string().optional(),
          procurementRoute: z.enum(PROCUREMENT_ROUTES).optional(),
          procurementComplexityScore: z.number().min(1).max(5).optional(),
          expectedSalesCycleDays: z.number().optional(),
          requiredDocuments: z.string().optional(),
          complianceRequirements: z.string().optional(),
          legalReviewRequired: z.boolean().optional(),
          dataSecurityReviewRequired: z.boolean().optional(),
          pilotPossibleWithoutFullProcurement: z.boolean().optional(),
          procurementRisks: z.string().optional(),
          nextProcurementStep: z.string().optional(),
          status: z.enum(PROCUREMENT_STATUSES).optional(),
        }),
      )
      .mutation(async ({ input }) => {
        const d = await db();
        const { id, ...vals } = input;
        if (id) {
          const [updated] = await d
            .update(procurementPathways)
            .set({ ...vals, updatedAt: new Date() })
            .where(and(eq(procurementPathways.id, id), eq(procurementPathways.ventureId, input.ventureId)))
            .returning({ id: procurementPathways.id });
          if (!updated) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
          return { id };
        }
        const [row] = await d.insert(procurementPathways).values(vals).returning({ id: procurementPathways.id });
        return { id: row.id };
      }),
    delete: ventureProcedure.input(recordInput).mutation(async ({ input }) => {
      const d = await db();
      const [row] = await d
        .delete(procurementPathways)
        .where(and(eq(procurementPathways.id, input.id), eq(procurementPathways.ventureId, input.ventureId)))
        .returning({ id: procurementPathways.id });
      if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Record not found" });
      return { success: true };
    }),
  }),

  // ── Commercial Objections aggregate ──────────────────────────────────────────
  objections: publicProcedure.input(ventureInput).query(async ({ input }) => {
    const d = await db();
    const rows = await d
      .select()
      .from(wtpTests)
      .where(eq(wtpTests.ventureId, input.ventureId));
    const counts = new Map<string, number>();
    const examples = new Map<string, string[]>();
    for (const r of rows) {
      if (!r.objectionCategory) continue;
      counts.set(r.objectionCategory, (counts.get(r.objectionCategory) ?? 0) + 1);
      if (r.objections) {
        const list = examples.get(r.objectionCategory) ?? [];
        if (list.length < 5) list.push(r.objections);
        examples.set(r.objectionCategory, list);
      }
    }
    return Array.from(counts.entries())
      .map(([category, count]) => ({
        category,
        count,
        examples: examples.get(category) ?? [],
      }))
      .sort((a, b) => b.count - a.count);
  }),

  // ── Overview aggregate (WTP Overview + Scorecard + Next Action tabs) ─────────
  overview: publicProcedure.input(ventureInput).query(async ({ input }) => {
    const d = await db();
    const [venture] = await d
      .select()
      .from(ventures)
      .where(eq(ventures.id, input.ventureId));

    const [tests, commitments, pricing, budgets, procurement] = await Promise.all([
      d.select().from(wtpTests).where(eq(wtpTests.ventureId, input.ventureId)).orderBy(desc(wtpTests.createdAt)),
      d.select().from(wtpCommitments).where(eq(wtpCommitments.ventureId, input.ventureId)),
      d.select().from(pricingExperiments).where(eq(pricingExperiments.ventureId, input.ventureId)),
      d.select().from(budgetValidations).where(eq(budgetValidations.ventureId, input.ventureId)),
      d.select().from(procurementPathways).where(eq(procurementPathways.ventureId, input.ventureId)),
    ]);

    const scores = tests.map((t) => t.wtpScore ?? 0);
    const averageScore = avg(scores);
    const highestEvidenceLevel = tests.reduce((m, t) => Math.max(m, t.evidenceLevel ?? 1), 0);
    const ventureStatus = calculateVentureWTPStatus({
      testCount: tests.length,
      averageScore,
      highestEvidenceLevel,
    });

    // Per-test scorecard breakdown.
    const scorecard = tests.map((t) => {
      const evidenceLevel = t.evidenceLevel ?? 1;
      const budgetStatus = t.budgetOwnerStatus ?? (t.budgetOwnerConfirmed ? "confirmed" : "unknown");
      return {
        id: t.id,
        customerName: t.customerName,
        organisation: t.organisation,
        evidenceLevel,
        wtpScore: t.wtpScore ?? 0,
        interpretation: interpretWTPScore(t.wtpScore ?? 0),
        components: {
          evidence: calculateEvidenceLevelScore(evidenceLevel),
          budgetOwner: budgetOwnerScore(budgetStatus),
          procurement: procurementPathwayScore(t.procurementPathwayStatus),
          pricingResponse: pricingResponseScore(t.pricingResponse),
        },
        warnings: generateWTPWarnings({
          evidenceLevel,
          budgetOwnerStatus: t.budgetOwnerStatus,
          budgetOwnerConfirmed: t.budgetOwnerConfirmed,
          procurementPathwayStatus: t.procurementPathwayStatus,
          pricingResponse: t.pricingResponse,
          objectionCategory: t.objectionCategory,
        }),
        nextCommercialAction: t.nextCommercialAction,
        nextActionDueDate: t.nextActionDueDate,
        status: t.status,
      };
    });

    // Stage-gate readiness (Commercial Validation → MVP Validation).
    const budgetOwnerIdentified =
      tests.some((t) => (t.budgetOwnerStatus ?? "unknown") !== "unknown") ||
      budgets.some((b) => b.budgetOwnerKnown);
    const pricingModelTested =
      pricing.length > 0 || tests.some((t) => !!t.pricingModelTested);
    const procurementPathwayMapped =
      procurement.some((p) => p.status !== "unknown") ||
      tests.some((t) => (t.procurementPathwayStatus ?? "unknown") !== "unknown");
    const criticalRisks = await d
      .select()
      .from(marketRisks)
      .where(and(eq(marketRisks.ventureId, input.ventureId), eq(marketRisks.linkedModule, "wtp")));
    const unresolvedCriticalRiskCount = criticalRisks.filter(
      (r) => r.status === "open" && (r.marketRiskScore ?? 0) >= 48,
    ).length;

    const stageGateInput = {
      averageWtpScore: averageScore,
      budgetOwnerIdentified,
      pricingModelTested,
      procurementPathwayMapped,
      unresolvedCriticalRiskCount,
    };

    // Next commercial actions (sorted: overdue first, then by due date).
    const t = today();
    const nextActions = tests
      .filter((x) => x.nextCommercialAction && x.nextCommercialAction.trim().length > 0)
      .map((x) => ({
        id: x.id,
        customerName: x.customerName,
        organisation: x.organisation,
        action: x.nextCommercialAction,
        dueDate: x.nextActionDueDate,
        overdue: !!x.nextActionDueDate && x.nextActionDueDate < t,
        wtpScore: x.wtpScore ?? 0,
      }))
      .sort((a, b) => {
        if (a.overdue !== b.overdue) return a.overdue ? -1 : 1;
        return (a.dueDate ?? "9999").localeCompare(b.dueDate ?? "9999");
      });

    return {
      venture: venture
        ? { id: venture.id, name: venture.name, currentStage: venture.currentStage, validationStatus: venture.validationStatus }
        : null,
      counts: {
        tests: tests.length,
        commitments: commitments.length,
        pricingExperiments: pricing.length,
        budgetValidations: budgets.length,
        procurementPathways: procurement.length,
      },
      averageScore,
      highestEvidenceLevel,
      ventureStatus,
      ventureStatusBand: ventureWTPStatusBand(ventureStatus),
      interpretation: interpretWTPScore(averageScore),
      decisionRecommendation: generateWTPDecisionRecommendation(averageScore),
      scorecard,
      nextActions,
      stageGate: {
        ...stageGateInput,
        checklist: wtpStageGateChecklist(stageGateInput),
        ready: wtpStageGateReady(stageGateInput),
      },
    };
  }),
});
